//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CirclePercentLayer, UIColor;

@interface CirclePercentView : UIView
{
    _Bool _isActivity;
    _Bool _isFromUp;
    float _percent;
    float _currentAngle;
    UIColor *_circleColor;
    CirclePercentLayer *_percentLayer;
    CirclePercentLayer *_anmationLayer;
}

@property(retain, nonatomic) CirclePercentLayer *anmationLayer; // @synthesize anmationLayer=_anmationLayer;
@property(retain, nonatomic) CirclePercentLayer *percentLayer; // @synthesize percentLayer=_percentLayer;
@property(nonatomic) _Bool isFromUp; // @synthesize isFromUp=_isFromUp;
@property(retain, nonatomic) UIColor *circleColor; // @synthesize circleColor=_circleColor;
@property(nonatomic) float currentAngle; // @synthesize currentAngle=_currentAngle;
@property(nonatomic) float percent; // @synthesize percent=_percent;
@property(nonatomic) _Bool isActivity; // @synthesize isActivity=_isActivity;
- (void).cxx_destruct;
- (void)stopAnimating;
- (void)startAnimating;
- (void)showPercent:(float)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

