//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface DirectoryUtils : NSObject
{
}

+ (id)chatRootDir;
+ (id)chatDirForChatter:(id)arg1 type:(unsigned long long)arg2;
+ (id)chatVideoDirForChatter:(id)arg1;
+ (id)chatAudioDirForChatter:(id)arg1;
+ (id)chatImageDirForChatter:(id)arg1;
+ (id)chatFileDirForChatter:(id)arg1;
+ (id)_chatRootDir;
+ (id)chatBufferDir;
+ (void)_createDir:(id)arg1;
+ (id)generateTrimmedUUID;
+ (id)generateUUID;
+ (long long)randomNumber:(long long)arg1 to:(long long)arg2;
+ (long long)randomNumber;
+ (id)generateTimeBasedFileNameForUser:(id)arg1 andFileName:(id)arg2;
+ (id)generateTimeBasedStringForString:(id)arg1;
+ (id)applicationLogDirectory;
+ (id)applicationTemporaryDirectory;
+ (id)applicationLibraryDirectory;
+ (id)applicationDocumentsDirectory;
+ (id)applicationHomeDirectory;

@end

