//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <MediaPlayer/MPMoviePlayerController.h>

@class DWHTTPRequest, DWLocalTime, DWPlayInfo, DWUtils, NSDate, NSDictionary, NSString, NSTimer, NSURL;

@interface DWMoviePlayerController : MPMoviePlayerController
{
    _Bool _isReplay;
    _Bool _isPause;
    unsigned short _drmServerPort;
    int _action;
    int _playNum;
    float _videoduration;
    int _play_num;
    NSString *_userId;
    NSString *_videoId;
    NSString *_key;
    double _timeoutSeconds;
    double _seekStartTime;
    NSURL *_sourceURL;
    NSString *_playaction;
    CDUnknownBlockType _getPlayUrlsBlock;
    CDUnknownBlockType _failBlock;
    NSURL *_originalContentURL;
    DWHTTPRequest *_request;
    DWPlayInfo *_playinfo;
    DWLocalTime *_localtime;
    DWUtils *_utils;
    NSDictionary *_playUrls;
    NSString *_playUrl;
    NSDictionary *_dict;
    NSDate *_startTime;
    NSDate *_startTime1;
    NSTimer *_timer;
    NSString *_adId;
    long long _videosize;
    long long _load_start_time;
    NSString *_responseToken;
    NSString *_dynamicKey;
}

@property(copy, nonatomic) NSString *dynamicKey; // @synthesize dynamicKey=_dynamicKey;
@property(retain, nonatomic) NSString *responseToken; // @synthesize responseToken=_responseToken;
@property(nonatomic) _Bool isPause; // @synthesize isPause=_isPause;
@property(nonatomic) int play_num; // @synthesize play_num=_play_num;
@property(nonatomic) long long load_start_time; // @synthesize load_start_time=_load_start_time;
@property(nonatomic) float videoduration; // @synthesize videoduration=_videoduration;
@property(nonatomic) long long videosize; // @synthesize videosize=_videosize;
@property(retain, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSDate *startTime1; // @synthesize startTime1=_startTime1;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
@property(retain, nonatomic) NSDictionary *dict; // @synthesize dict=_dict;
@property(retain, nonatomic) NSString *playUrl; // @synthesize playUrl=_playUrl;
@property(retain, nonatomic) NSDictionary *playUrls; // @synthesize playUrls=_playUrls;
@property(retain, nonatomic) DWUtils *utils; // @synthesize utils=_utils;
@property(retain, nonatomic) DWLocalTime *localtime; // @synthesize localtime=_localtime;
@property(retain, nonatomic) DWPlayInfo *playinfo; // @synthesize playinfo=_playinfo;
@property(retain, nonatomic) DWHTTPRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) NSURL *originalContentURL; // @synthesize originalContentURL=_originalContentURL;
@property(nonatomic) unsigned short drmServerPort; // @synthesize drmServerPort=_drmServerPort;
@property(copy, nonatomic) CDUnknownBlockType failBlock; // @synthesize failBlock=_failBlock;
@property(copy, nonatomic) CDUnknownBlockType getPlayUrlsBlock; // @synthesize getPlayUrlsBlock=_getPlayUrlsBlock;
@property(nonatomic) _Bool isReplay; // @synthesize isReplay=_isReplay;
@property(nonatomic) int playNum; // @synthesize playNum=_playNum;
@property(retain, nonatomic) NSString *playaction; // @synthesize playaction=_playaction;
@property(nonatomic) int action; // @synthesize action=_action;
@property(retain, nonatomic) NSURL *sourceURL; // @synthesize sourceURL=_sourceURL;
@property(nonatomic) double seekStartTime; // @synthesize seekStartTime=_seekStartTime;
@property(nonatomic) double timeoutSeconds; // @synthesize timeoutSeconds=_timeoutSeconds;
@property(copy, nonatomic) NSString *key; // @synthesize key=_key;
@property(copy, nonatomic) NSString *videoId; // @synthesize videoId=_videoId;
@property(copy, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (id)sha1;
- (void)pause;
- (void)stop;
- (void)play;
- (void)timeFired:(id)arg1;
- (void)removeTimer;
- (void)startTimer;
- (id)ConvertTo36:(int)arg1;
- (id)verote;
- (void)heart;
- (void)play_over;
- (void)swith_quality;
- (void)drag_action;
- (void)pause_replay;
- (void)load_fail;
- (void)replay;
- (void)playlog;
- (void)play_start;
- (void)ready_start;
- (void)playlog_php;
- (void)first_load;
- (void)play_action;
- (void)prepareToPlay;
- (void)rewriteContentURL;
- (_Bool)isPcmFile:(id)arg1;
- (void)callErrorBlockWithString:(id)arg1;
- (void)callErrorBlockWithError:(id)arg1;
- (void)createTokenKey;
- (_Bool)parsePlayInfoResponse:(id)arg1;
- (void)cancelRequestPlayInfo;
- (void)startRequestPlayInfo;
- (id)initWithUserId:(id)arg1 key:(id)arg2;
- (id)initWithUserId:(id)arg1 andVideoId:(id)arg2 key:(id)arg3;

@end

