//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "IEMChatObject-Protocol.h"

@class CLLocation, EMChatLocationInternal, NSString;
@protocol IEMMessageBody;

@interface EMChatLocation : NSObject <IEMChatObject>
{
    EMChatLocationInternal *_internal;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)initWithCLLocation:(id)arg1;
- (id)initWithLatitude:(double)arg1 longitude:(double)arg2 address:(id)arg3;
- (id)init;
@property(nonatomic) __weak id <IEMMessageBody> messageBody; // @dynamic messageBody;
@property(retain, nonatomic) CLLocation *location; // @dynamic location;
@property(retain, nonatomic) NSString *address; // @dynamic address;
@property(nonatomic) double longitude; // @dynamic longitude;
@property(nonatomic) double latitude; // @dynamic latitude;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

