//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWObject.h"

@class NSArray, NSString;

@interface FuturMonth : GWObject
{
    NSString *_futureMonth;
    NSArray *_futureDayList;
}

@property(retain, nonatomic) NSArray *futureDayList; // @synthesize futureDayList=_futureDayList;
@property(retain, nonatomic) NSString *futureMonth; // @synthesize futureMonth=_futureMonth;
- (void).cxx_destruct;

@end

