//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "GWLoadingViewControllerDelegate-Protocol.h"
#import "RESideMenuDelegate-Protocol.h"
#import "UIApplicationDelegate-Protocol.h"
#import "WXApiDelegate-Protocol.h"

@class CMMotionManager, GWAdImageButtonView, GWLogingViewController, GWPayManager, GWRESideMenu, GWUserBindViewController, NSBlockOperation, NSDictionary, NSString, NSURL, UIImageView, UIWindow;

@interface GWAppDelegate : UIResponder <RESideMenuDelegate, GWLoadingViewControllerDelegate, WXApiDelegate, UIApplicationDelegate>
{
    CMMotionManager *motionmanager;
    UIWindow *_window;
    UIWindow *_exWindow;
    GWRESideMenu *_sideMenuViewController;
    GWPayManager *_finalGWPayManager;
    GWLogingViewController *_loginViewController;
    GWUserBindViewController *_bingViewController;
    NSDictionary *_gwLaunchOptions;
    NSString *_appOpenUrl;
    UIImageView *_screenImageView;
    NSURL *_mlinkURl;
    NSDictionary *_shortItemDic;
    NSBlockOperation *_myOperation;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSBlockOperation *myOperation; // @synthesize myOperation=_myOperation;
@property(retain, nonatomic) NSDictionary *shortItemDic; // @synthesize shortItemDic=_shortItemDic;
@property(retain, nonatomic) NSURL *mlinkURl; // @synthesize mlinkURl=_mlinkURl;
@property(retain, nonatomic) UIImageView *screenImageView; // @synthesize screenImageView=_screenImageView;
@property(copy, nonatomic) NSString *appOpenUrl; // @synthesize appOpenUrl=_appOpenUrl;
@property(retain, nonatomic) NSDictionary *gwLaunchOptions; // @synthesize gwLaunchOptions=_gwLaunchOptions;
@property(nonatomic) __weak GWUserBindViewController *bingViewController; // @synthesize bingViewController=_bingViewController;
@property(nonatomic) __weak GWLogingViewController *loginViewController; // @synthesize loginViewController=_loginViewController;
@property(nonatomic) __weak GWPayManager *finalGWPayManager; // @synthesize finalGWPayManager=_finalGWPayManager;
@property(retain, nonatomic) GWRESideMenu *sideMenuViewController; // @synthesize sideMenuViewController=_sideMenuViewController;
@property(retain, nonatomic) UIWindow *exWindow; // @synthesize exWindow=_exWindow;
@property(retain, nonatomic) UIWindow *window; // @synthesize window=_window;
- (void).cxx_destruct;
- (void)sideMenu:(id)arg1 didHideMenuViewController:(id)arg2;
- (void)sideMenu:(id)arg1 willHideMenuViewController:(id)arg2;
- (void)sideMenu:(id)arg1 didShowMenuViewController:(id)arg2;
- (void)sideMenu:(id)arg1 willShowMenuViewController:(id)arg2;
- (void)onResp:(id)arg1;
- (void)onReq:(id)arg1;
- (void)loadingViewControllerDidFinished:(id)arg1;
- (void)handleExternalEntrance;
- (void)simulateNotification;
- (_Bool)processApp:(id)arg1 openURL:(id)arg2;
- (_Bool)application:(id)arg1 openURL:(id)arg2 sourceApplication:(id)arg3 annotation:(id)arg4;
- (_Bool)application:(id)arg1 openURL:(id)arg2 options:(id)arg3;
- (void)application:(id)arg1 didUpdateUserActivity:(id)arg2;
- (void)application:(id)arg1 didFailToContinueUserActivityWithType:(id)arg2 error:(id)arg3;
- (_Bool)application:(id)arg1 continueUserActivity:(id)arg2 restorationHandler:(CDUnknownBlockType)arg3;
- (_Bool)application:(id)arg1 willContinueUserActivityWithType:(id)arg2;
- (void)application:(id)arg1 performActionForShortcutItem:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)showActionMessageWithDict:(id)arg1;
- (void)application:(id)arg1 didReceiveLocalNotification:(id)arg2;
- (void)userNotificationCenter:(id)arg1 didReceiveNotificationResponse:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)userNotificationCenter:(id)arg1 willPresentNotification:(id)arg2 withCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2 fetchCompletionHandler:(CDUnknownBlockType)arg3;
- (void)application:(id)arg1 didReceiveRemoteNotification:(id)arg2;
- (void)application:(id)arg1 didFailToRegisterForRemoteNotificationsWithError:(id)arg2;
- (void)application:(id)arg1 performFetchWithCompletionHandler:(CDUnknownBlockType)arg2;
- (void)application:(id)arg1 didRegisterForRemoteNotificationsWithDeviceToken:(id)arg2;
- (unsigned long long)application:(id)arg1 supportedInterfaceOrientationsForWindow:(id)arg2;
- (void)applicationWillTerminate:(id)arg1;
- (void)applicationDidBecomeActive:(id)arg1;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)applicationWillResignActive:(id)arg1;
- (void)registerXGPushWithOptions:(id)arg1;
- (_Bool)application:(id)arg1 didFinishLaunchingWithOptions:(id)arg2;
- (void)startNotificationObservers;
- (void)handleUserError:(id)arg1;
- (void)resetAppRootViewControllers;
- (void)setRootViewController;
- (void)initWindowIfNeed;
- (void)dealloc;
- (id)init;
- (void)handleUserActivity:(id)arg1;
- (void)showExWindowWithPageParamaDict:(id)arg1;
- (void)pushActionWithPushDict:(id)arg1;
- (void)pushActionWithPushDict_900:(id)arg1;
- (void)gotoUrl:(id)arg1;
- (void)analyseUrlFromOtherApp:(id)arg1;
- (void)createExWindowWithRootController:(id)arg1;
- (void)showAdImageView:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)checkToShowAdImageViewIfNeed;
- (id)adImageViewWithImage:(id)arg1;
@property(retain, nonatomic) GWAdImageButtonView *buttonView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

