//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseCell.h"

@class GWImagePolicyView, UIButton, UILabel, UIView;
@protocol GWBindCellDelegate;

@interface GWBindingCell : GWBaseCell
{
    id <GWBindCellDelegate> _bindDelegate;
    GWImagePolicyView *_logoView;
    UIView *_bgView;
    UILabel *_nameLabel;
    UIButton *_bindButton;
    UILabel *_bindLabel;
    UIView *_topView;
    UIView *_bottomView;
    UILabel *_userNameLabel;
}

@property(retain, nonatomic) UILabel *userNameLabel; // @synthesize userNameLabel=_userNameLabel;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) UILabel *bindLabel; // @synthesize bindLabel=_bindLabel;
@property(retain, nonatomic) UIButton *bindButton; // @synthesize bindButton=_bindButton;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *bgView; // @synthesize bgView=_bgView;
@property(retain, nonatomic) GWImagePolicyView *logoView; // @synthesize logoView=_logoView;
@property(nonatomic) __weak id <GWBindCellDelegate> bindDelegate; // @synthesize bindDelegate=_bindDelegate;
- (void).cxx_destruct;
- (id)loginUserNickName:(id)arg1;
- (void)showCellWithModel:(id)arg1;
- (void)bindButtonClicked:(id)arg1;
- (void)loadAllViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

