//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWObject.h"

@class NSString;

@interface GWBindAuthModel : GWObject
{
    _Bool _bindFlag;
    _Bool _bindGewaraFlag;
    NSString *_uid;
    NSString *_bindType;
    NSString *_accessToken;
    NSString *_username;
    NSString *_password;
}

@property(copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(copy, nonatomic) NSString *accessToken; // @synthesize accessToken=_accessToken;
@property(copy, nonatomic) NSString *bindType; // @synthesize bindType=_bindType;
@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(nonatomic) _Bool bindGewaraFlag; // @synthesize bindGewaraFlag=_bindGewaraFlag;
@property(nonatomic) _Bool bindFlag; // @synthesize bindFlag=_bindFlag;
- (void).cxx_destruct;

@end

