//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class GWProtocolInterceptor, NSString, UIButton, UILabel, UIScrollView;
@protocol GWBottomToolBarViewDelegate;

@interface GWBottomToolBarView : UIView <UIScrollViewDelegate>
{
    UILabel *_favorCountView;
    GWProtocolInterceptor *_interceptor;
    _Bool _needDrawLine;
    UIButton *_shareButton;
    UIButton *_walaButton;
    UIButton *_likeButton;
    UIButton *_customBtn;
    UILabel *_walaTitleView;
    id <GWBottomToolBarViewDelegate> _delegate;
    UIScrollView *_observerScrollView;
    NSString *_countNumber;
    unsigned long long _showType;
    CDUnknownBlockType _updateFrameBlock;
    UIView *_dividedVerticalLine;
}

+ (id)createBottomToolBarWithView:(id)arg1;
+ (id)createBottomToolBarWithView:(id)arg1 withShowType:(unsigned long long)arg2;
@property(retain, nonatomic) UIView *dividedVerticalLine; // @synthesize dividedVerticalLine=_dividedVerticalLine;
@property(copy, nonatomic) CDUnknownBlockType updateFrameBlock; // @synthesize updateFrameBlock=_updateFrameBlock;
@property(readonly, nonatomic) unsigned long long showType; // @synthesize showType=_showType;
@property(nonatomic) _Bool needDrawLine; // @synthesize needDrawLine=_needDrawLine;
@property(copy, nonatomic) NSString *countNumber; // @synthesize countNumber=_countNumber;
@property(retain, nonatomic) UIScrollView *observerScrollView; // @synthesize observerScrollView=_observerScrollView;
@property(nonatomic) __weak id <GWBottomToolBarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) UILabel *walaTitleView; // @synthesize walaTitleView=_walaTitleView;
@property(readonly, nonatomic) UIButton *customBtn; // @synthesize customBtn=_customBtn;
@property(readonly, nonatomic) UIButton *likeButton; // @synthesize likeButton=_likeButton;
@property(readonly, nonatomic) UIButton *walaButton; // @synthesize walaButton=_walaButton;
@property(readonly, nonatomic) UIButton *shareButton; // @synthesize shareButton=_shareButton;
- (void).cxx_destruct;
- (void)buttonClick:(id)arg1;
- (unsigned long long)buttonTypeWithButton:(id)arg1;
- (void)likeButtonStateChangedWithAnimation:(_Bool)arg1;
- (void)animationForHeartBroken;
- (void)animationForHeart;
- (void)changedLikeStatus;
- (void)hideWithAnimated:(_Bool)arg1;
- (void)showWithAnimated:(_Bool)arg1;
- (void)updateFrameForAnimate:(struct CGRect)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)minusFavorCount;
- (void)plusFavorCount;
- (void)customButtonEnable:(_Bool)arg1;
- (void)hiddenCustomButtonWithShareFunc:(_Bool)arg1;
- (void)hiddenCustomButton:(_Bool)arg1;
- (void)loadLikeAndShareButton;
- (void)loadChangciNavi;
- (void)loadAllControl;
- (void)loadBottomWalaControl;
- (id)createTipsLabel;
- (void)reloadData;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withShowType:(unsigned long long)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

