//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class GWCalendarDateBlockView, NSString, UIScrollView;

@interface GWCalendarDateScrollView : UIView <UIScrollViewDelegate>
{
    _Bool _isOpened;
    CDUnknownBlockType _dateButtonClickCallBack;
    CDUnknownBlockType _heightChanged;
    GWCalendarDateBlockView *_dateBlockView;
    UIScrollView *_backScrollView;
}

@property(retain, nonatomic) UIScrollView *backScrollView; // @synthesize backScrollView=_backScrollView;
@property(retain, nonatomic) GWCalendarDateBlockView *dateBlockView; // @synthesize dateBlockView=_dateBlockView;
@property(nonatomic) _Bool isOpened; // @synthesize isOpened=_isOpened;
@property(copy, nonatomic) CDUnknownBlockType heightChanged; // @synthesize heightChanged=_heightChanged;
@property(copy, nonatomic) CDUnknownBlockType dateButtonClickCallBack; // @synthesize dateButtonClickCallBack=_dateButtonClickCallBack;
- (void).cxx_destruct;
- (void)adjustScrollView:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)changeByOpenStatus;
- (void)openButtonClick:(id)arg1;
- (void)clickFirstDate;
- (void)scrollToShowFirstOrSelectedDate;
- (void)showCalanderWithMonthData:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

