//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class GWStarDetail;
@protocol GWAppTypeDelegate;

@interface GWCollectionButton : UIButton
{
    CDUnknownBlockType _collectionStatusChanged;
    id <GWAppTypeDelegate> _relatedInfo;
    GWStarDetail *_starDetail;
}

@property(retain, nonatomic) GWStarDetail *starDetail; // @synthesize starDetail=_starDetail;
@property(nonatomic) __weak id <GWAppTypeDelegate> relatedInfo; // @synthesize relatedInfo=_relatedInfo;
@property(copy, nonatomic) CDUnknownBlockType collectionStatusChanged; // @synthesize collectionStatusChanged=_collectionStatusChanged;
- (void).cxx_destruct;
- (void)showCollectionButton;
- (void)attentionButtonClick:(id)arg1;
- (void)setSelected:(_Bool)arg1;
- (id)initWithFrame:(struct CGRect)arg1 relatedInfo:(id)arg2;

@end

