//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWDBCondition.h"

@class NSArray;

@interface GWDBSearchCondition : GWDBCondition
{
    _Bool _ascSort;
    NSArray *_columnList;
    NSArray *_groupByList;
    NSArray *_orderByList;
    long long _limit;
    long long _offset;
}

@property(nonatomic) long long offset; // @synthesize offset=_offset;
@property(nonatomic) long long limit; // @synthesize limit=_limit;
@property(nonatomic) _Bool ascSort; // @synthesize ascSort=_ascSort;
@property(retain, nonatomic) NSArray *orderByList; // @synthesize orderByList=_orderByList;
@property(retain, nonatomic) NSArray *groupByList; // @synthesize groupByList=_groupByList;
@property(retain, nonatomic) NSArray *columnList; // @synthesize columnList=_columnList;
- (void).cxx_destruct;
- (id)conditionStringAddValues:(id)arg1;
- (id)cloumString;

@end

