//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWDramaDetailBaseCell.h"

@class UIView;
@protocol GWDramaDetailPlayItemDelegate;

@interface GWDramaDetailPlayItemCell : GWDramaDetailBaseCell
{
    id <GWDramaDetailPlayItemDelegate> _delegate;
    UIView *_playItemView;
}

+ (double)rowHeightWithCellObject:(id)arg1;
@property(retain, nonatomic) UIView *playItemView; // @synthesize playItemView=_playItemView;
@property(nonatomic) __weak id <GWDramaDetailPlayItemDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)playItemViewClickEvent:(id)arg1;
- (void)showCellWithObject:(id)arg1;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

