//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CellBaseObject.h"

@class NSMutableArray;

@interface GWDramaTheatreServieTagCellObject : CellBaseObject
{
    NSMutableArray *_serviceTagArray;
    double _viewHeight;
}

@property(nonatomic) double viewHeight; // @synthesize viewHeight=_viewHeight;
@property(retain, nonatomic) NSMutableArray *serviceTagArray; // @synthesize serviceTagArray=_serviceTagArray;
- (void).cxx_destruct;
- (id)init;

@end

