//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWDramaDetailBaseCell.h"

@class UIView, V6MoviePeopleScroller;
@protocol GWDramaDetailStarCellDelegate;

@interface GWDramaDetailStarCell : GWDramaDetailBaseCell
{
    id <GWDramaDetailStarCellDelegate> _delegate;
    V6MoviePeopleScroller *_peopleScrollView;
    UIView *_peopleListView;
}

+ (double)rowHeightWithCellObject:(id)arg1;
@property(retain, nonatomic) UIView *peopleListView; // @synthesize peopleListView=_peopleListView;
@property(retain, nonatomic) V6MoviePeopleScroller *peopleScrollView; // @synthesize peopleScrollView=_peopleScrollView;
@property(nonatomic) __weak id <GWDramaDetailStarCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)adjustHeadImageView:(id)arg1;
- (id)peopleInfoView:(id)arg1 withNeedBottomLine:(_Bool)arg2;
- (void)peopleViewClick:(id)arg1;
- (void)showCellWithObject:(id)arg1;

@end

