//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseCellObject.h"

@class NSString;

@interface GWGeDiaoAuthorCellObject : GWBaseCellObject
{
    NSString *_authorName;
    NSString *_authorDesc;
}

+ (id)createTestData;
@property(copy, nonatomic) NSString *authorDesc; // @synthesize authorDesc=_authorDesc;
@property(copy, nonatomic) NSString *authorName; // @synthesize authorName=_authorName;
- (void).cxx_destruct;
- (id)init;

@end

