//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWObject.h"

@class GWDrama, NSArray, NSString;

@interface GWHomeCountDownModel : GWObject
{
    GWDrama *_GWdrama;
    NSArray *_playItemID;
    NSArray *_theatreID;
    NSString *_logo;
    NSString *_title;
    NSString *_countdownTime_diff;
    NSString *_relatedid;
    NSString *_countdownTime;
    NSString *_currentTime;
}

+ (id)convertFromWDateDic:(id)arg1;
@property(copy, nonatomic) NSString *currentTime; // @synthesize currentTime=_currentTime;
@property(copy, nonatomic) NSString *countdownTime; // @synthesize countdownTime=_countdownTime;
@property(copy, nonatomic) NSString *relatedid; // @synthesize relatedid=_relatedid;
@property(copy, nonatomic) NSString *countdownTime_diff; // @synthesize countdownTime_diff=_countdownTime_diff;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *logo; // @synthesize logo=_logo;
@property(retain, nonatomic) NSArray *theatreID; // @synthesize theatreID=_theatreID;
@property(retain, nonatomic) NSArray *playItemID; // @synthesize playItemID=_playItemID;
@property(retain, nonatomic) GWDrama *GWdrama; // @synthesize GWdrama=_GWdrama;
- (void).cxx_destruct;
- (_Bool)countdown;
- (id)calculateCountdownTime_diff;
- (long long)calculateTimeIntervalSince1970:(id)arg1;

@end

