//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString, UIView;

@protocol GWHomeBaseClassViewDelegate <NSObject>

@optional
- (void)registPreView:(UIView *)arg1;
- (void)clickWithPost:(NSString *)arg1;
- (void)clickWithMore:(NSString *)arg1;
@end

