//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UICollectionViewCell.h>

@class UIImageView, UILabel;

@interface GWHomeRecommendInfoCell : UICollectionViewCell
{
    UIImageView *_posterView;
    UILabel *_title;
    UIImageView *_imageMaskView;
}

@property(retain, nonatomic) UIImageView *imageMaskView; // @synthesize imageMaskView=_imageMaskView;
@property(retain, nonatomic) UILabel *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImageView *posterView; // @synthesize posterView=_posterView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)updateWithCell:(id)arg1;

@end

