//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseInfoProvider.h"

@class NSString;

@interface GWMemberInfoProvider : GWBaseInfoProvider
{
    NSString *memberid;
    NSString *nickname;
    NSString *citycode;
}

@property(copy, nonatomic) NSString *citycode; // @synthesize citycode;
@property(copy, nonatomic) NSString *nickname; // @synthesize nickname;
@property(copy, nonatomic) NSString *memberid; // @synthesize memberid;
- (void).cxx_destruct;
- (void)requestWithGetMemberInfoHanlder:(CDUnknownBlockType)arg1;
- (id)init;

@end

