//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class GWMidnightPlayItemProvider, GWMoviePlayItemListProvider, NSString;
@protocol GWProviderDelegate;

@interface GWMoviePlayItemListProviderManager : NSObject
{
    id <GWProviderDelegate> _sender;
    NSString *_cinemaid;
    NSString *_movieid;
    NSString *_playdate;
    NSString *_discountid;
    NSString *_characteristic;
    NSString *_mpiFrom;
    GWMoviePlayItemListProvider *_normalProvider;
    GWMidnightPlayItemProvider *_midnightProvider;
}

@property(retain, nonatomic) GWMidnightPlayItemProvider *midnightProvider; // @synthesize midnightProvider=_midnightProvider;
@property(retain, nonatomic) GWMoviePlayItemListProvider *normalProvider; // @synthesize normalProvider=_normalProvider;
@property(copy, nonatomic) NSString *mpiFrom; // @synthesize mpiFrom=_mpiFrom;
@property(copy, nonatomic) NSString *characteristic; // @synthesize characteristic=_characteristic;
@property(copy, nonatomic) NSString *discountid; // @synthesize discountid=_discountid;
@property(copy, nonatomic) NSString *playdate; // @synthesize playdate=_playdate;
@property(copy, nonatomic) NSString *movieid; // @synthesize movieid=_movieid;
@property(copy, nonatomic) NSString *cinemaid; // @synthesize cinemaid=_cinemaid;
@property(nonatomic) __weak id <GWProviderDelegate> sender; // @synthesize sender=_sender;
- (void).cxx_destruct;
- (void)requestMoviePlayItemAndPromotionWithHandler:(CDUnknownBlockType)arg1;
- (void)requestMoviePlayItemListWithHandler:(CDUnknownBlockType)arg1;
- (void)cancel;
- (void)dealloc;
- (id)initWithSender:(id)arg1;

@end

