//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class GWStarDetail, GWStarHeaderImageView, UIImageView, UILabel, UIView;

@interface GWMovieStarCardView : UIControl
{
    _Bool _isSelected;
    GWStarDetail *_starDetail;
    UILabel *_nameLabel;
    UILabel *_infoLabel;
    GWStarHeaderImageView *_headImageView;
    UIImageView *_iconImageView;
    UIView *_maskView;
}

@property(retain, nonatomic) UIView *maskView; // @synthesize maskView=_maskView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(retain, nonatomic) GWStarHeaderImageView *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) UILabel *infoLabel; // @synthesize infoLabel=_infoLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(nonatomic) _Bool isSelected; // @synthesize isSelected=_isSelected;
@property(retain, nonatomic) GWStarDetail *starDetail; // @synthesize starDetail=_starDetail;
- (void).cxx_destruct;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

