//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class GWMoviePolicyImageView, GWNeedComment, NSIndexPath, NSLayoutConstraint, NSObject, UIButton, UIImageView, UILabel, UIView;
@protocol GWMovieCommentDelegate;

@interface GWMovieCommentCell : UITableViewCell
{
    NSObject<GWMovieCommentDelegate> *_delegate;
    NSIndexPath *_indexPath;
    GWMoviePolicyImageView *_coverImageView;
    UIImageView *_timeIconImageView;
    UILabel *_timeLabel;
    UIImageView *_arrowImageView;
    UIButton *_cinemaNameButton;
    UIImageView *_triangleImageView;
    UIView *_baseView;
    UILabel *_titleLabel;
    UILabel *_cntLabel;
    UIButton *_commentButton;
    GWNeedComment *_comment;
    NSLayoutConstraint *_timeIconLeading;
    NSLayoutConstraint *_timeIconTop;
    NSLayoutConstraint *_timeIconHeight;
    NSLayoutConstraint *_timeIconWidth;
    NSLayoutConstraint *_timeLabelLeading;
    NSLayoutConstraint *_timeLabelTop;
    NSLayoutConstraint *_timeLabelWidth;
    NSLayoutConstraint *_timeLabelHeight;
    NSLayoutConstraint *_cinemaNameButtonLeading;
    NSLayoutConstraint *_cinemaNameButtonTop;
    NSLayoutConstraint *_cinemaNameButtonTrailing;
    NSLayoutConstraint *_cinemaNameButtonHeight;
    NSLayoutConstraint *_arrowImageViewLeading;
    NSLayoutConstraint *_arrowImageViewTop;
    NSLayoutConstraint *_arrowImageViewWidth;
    NSLayoutConstraint *_arrowImageViewHeight;
    NSLayoutConstraint *_triangleImageViewLeading;
    NSLayoutConstraint *_triangleImageViewTop;
    NSLayoutConstraint *_triangleImageViewWidth;
    NSLayoutConstraint *_triangleImageViewHeight;
    NSLayoutConstraint *_baseViewLeading;
    NSLayoutConstraint *_baseViewTop;
    NSLayoutConstraint *_baseViewHeight;
    NSLayoutConstraint *_baseViewTrailing;
    NSLayoutConstraint *_baseViewBottom;
    NSLayoutConstraint *_coverImageViewTop;
    NSLayoutConstraint *_coverImageViewLeading;
    NSLayoutConstraint *_coverImageViewHeight;
    NSLayoutConstraint *_coverImageViewWidth;
    NSLayoutConstraint *_titleLabelTop;
    NSLayoutConstraint *_titleLabelLeading;
    NSLayoutConstraint *_titleLabelTrailing;
    NSLayoutConstraint *_cntLabelTop;
    NSLayoutConstraint *_cntLabelLeading;
    NSLayoutConstraint *_cntLabelTrailing;
    NSLayoutConstraint *_commentButtonLeading;
    NSLayoutConstraint *_commentButtonTop;
    NSLayoutConstraint *_commentButtonTrailing;
    NSLayoutConstraint *_commentButtonBottom;
}

@property(nonatomic) __weak NSLayoutConstraint *commentButtonBottom; // @synthesize commentButtonBottom=_commentButtonBottom;
@property(nonatomic) __weak NSLayoutConstraint *commentButtonTrailing; // @synthesize commentButtonTrailing=_commentButtonTrailing;
@property(nonatomic) __weak NSLayoutConstraint *commentButtonTop; // @synthesize commentButtonTop=_commentButtonTop;
@property(nonatomic) __weak NSLayoutConstraint *commentButtonLeading; // @synthesize commentButtonLeading=_commentButtonLeading;
@property(nonatomic) __weak NSLayoutConstraint *cntLabelTrailing; // @synthesize cntLabelTrailing=_cntLabelTrailing;
@property(nonatomic) __weak NSLayoutConstraint *cntLabelLeading; // @synthesize cntLabelLeading=_cntLabelLeading;
@property(nonatomic) __weak NSLayoutConstraint *cntLabelTop; // @synthesize cntLabelTop=_cntLabelTop;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelTrailing; // @synthesize titleLabelTrailing=_titleLabelTrailing;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelLeading; // @synthesize titleLabelLeading=_titleLabelLeading;
@property(nonatomic) __weak NSLayoutConstraint *titleLabelTop; // @synthesize titleLabelTop=_titleLabelTop;
@property(nonatomic) __weak NSLayoutConstraint *coverImageViewWidth; // @synthesize coverImageViewWidth=_coverImageViewWidth;
@property(nonatomic) __weak NSLayoutConstraint *coverImageViewHeight; // @synthesize coverImageViewHeight=_coverImageViewHeight;
@property(nonatomic) __weak NSLayoutConstraint *coverImageViewLeading; // @synthesize coverImageViewLeading=_coverImageViewLeading;
@property(nonatomic) __weak NSLayoutConstraint *coverImageViewTop; // @synthesize coverImageViewTop=_coverImageViewTop;
@property(nonatomic) __weak NSLayoutConstraint *baseViewBottom; // @synthesize baseViewBottom=_baseViewBottom;
@property(nonatomic) __weak NSLayoutConstraint *baseViewTrailing; // @synthesize baseViewTrailing=_baseViewTrailing;
@property(nonatomic) __weak NSLayoutConstraint *baseViewHeight; // @synthesize baseViewHeight=_baseViewHeight;
@property(nonatomic) __weak NSLayoutConstraint *baseViewTop; // @synthesize baseViewTop=_baseViewTop;
@property(nonatomic) __weak NSLayoutConstraint *baseViewLeading; // @synthesize baseViewLeading=_baseViewLeading;
@property(nonatomic) __weak NSLayoutConstraint *triangleImageViewHeight; // @synthesize triangleImageViewHeight=_triangleImageViewHeight;
@property(nonatomic) __weak NSLayoutConstraint *triangleImageViewWidth; // @synthesize triangleImageViewWidth=_triangleImageViewWidth;
@property(nonatomic) __weak NSLayoutConstraint *triangleImageViewTop; // @synthesize triangleImageViewTop=_triangleImageViewTop;
@property(nonatomic) __weak NSLayoutConstraint *triangleImageViewLeading; // @synthesize triangleImageViewLeading=_triangleImageViewLeading;
@property(nonatomic) __weak NSLayoutConstraint *arrowImageViewHeight; // @synthesize arrowImageViewHeight=_arrowImageViewHeight;
@property(nonatomic) __weak NSLayoutConstraint *arrowImageViewWidth; // @synthesize arrowImageViewWidth=_arrowImageViewWidth;
@property(nonatomic) __weak NSLayoutConstraint *arrowImageViewTop; // @synthesize arrowImageViewTop=_arrowImageViewTop;
@property(nonatomic) __weak NSLayoutConstraint *arrowImageViewLeading; // @synthesize arrowImageViewLeading=_arrowImageViewLeading;
@property(nonatomic) __weak NSLayoutConstraint *cinemaNameButtonHeight; // @synthesize cinemaNameButtonHeight=_cinemaNameButtonHeight;
@property(nonatomic) __weak NSLayoutConstraint *cinemaNameButtonTrailing; // @synthesize cinemaNameButtonTrailing=_cinemaNameButtonTrailing;
@property(nonatomic) __weak NSLayoutConstraint *cinemaNameButtonTop; // @synthesize cinemaNameButtonTop=_cinemaNameButtonTop;
@property(nonatomic) __weak NSLayoutConstraint *cinemaNameButtonLeading; // @synthesize cinemaNameButtonLeading=_cinemaNameButtonLeading;
@property(nonatomic) __weak NSLayoutConstraint *timeLabelHeight; // @synthesize timeLabelHeight=_timeLabelHeight;
@property(nonatomic) __weak NSLayoutConstraint *timeLabelWidth; // @synthesize timeLabelWidth=_timeLabelWidth;
@property(nonatomic) __weak NSLayoutConstraint *timeLabelTop; // @synthesize timeLabelTop=_timeLabelTop;
@property(nonatomic) __weak NSLayoutConstraint *timeLabelLeading; // @synthesize timeLabelLeading=_timeLabelLeading;
@property(nonatomic) __weak NSLayoutConstraint *timeIconWidth; // @synthesize timeIconWidth=_timeIconWidth;
@property(nonatomic) __weak NSLayoutConstraint *timeIconHeight; // @synthesize timeIconHeight=_timeIconHeight;
@property(nonatomic) __weak NSLayoutConstraint *timeIconTop; // @synthesize timeIconTop=_timeIconTop;
@property(nonatomic) __weak NSLayoutConstraint *timeIconLeading; // @synthesize timeIconLeading=_timeIconLeading;
@property(retain, nonatomic) GWNeedComment *comment; // @synthesize comment=_comment;
@property(nonatomic) __weak UIButton *commentButton; // @synthesize commentButton=_commentButton;
@property(nonatomic) __weak UILabel *cntLabel; // @synthesize cntLabel=_cntLabel;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak UIView *baseView; // @synthesize baseView=_baseView;
@property(nonatomic) __weak UIImageView *triangleImageView; // @synthesize triangleImageView=_triangleImageView;
@property(nonatomic) __weak UIButton *cinemaNameButton; // @synthesize cinemaNameButton=_cinemaNameButton;
@property(nonatomic) __weak UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(nonatomic) __weak UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(nonatomic) __weak UIImageView *timeIconImageView; // @synthesize timeIconImageView=_timeIconImageView;
@property(nonatomic) __weak GWMoviePolicyImageView *coverImageView; // @synthesize coverImageView=_coverImageView;
@property(nonatomic) __weak NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) __weak NSObject<GWMovieCommentDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)sendWalaOnClick:(id)arg1;
- (void)cinemaOnClick:(id)arg1;
- (void)movieOnClick:(id)arg1;
- (void)showCellWithModel:(id)arg1;
- (void)awakeFromNib;

@end

