//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWObject.h"

@class NSString;

@interface GWMyFriendWalaModel : GWObject
{
    NSString *_movieID;
    NSString *_myFriendsTreasuretotalNum;
    NSString *_myFriendsTreasureDesc;
    NSString *_myFriendsSayTotalNum;
    NSString *_myFriendsSayDesc;
    NSString *_myFriendsSayUnreadNum;
    NSString *_myFriendsSayHeadCount;
    NSString *_myFriendsSayHeadUrls;
    NSString *_myFriendsTotalNum;
}

@property(copy, nonatomic) NSString *myFriendsTotalNum; // @synthesize myFriendsTotalNum=_myFriendsTotalNum;
@property(copy, nonatomic) NSString *myFriendsSayHeadUrls; // @synthesize myFriendsSayHeadUrls=_myFriendsSayHeadUrls;
@property(copy, nonatomic) NSString *myFriendsSayHeadCount; // @synthesize myFriendsSayHeadCount=_myFriendsSayHeadCount;
@property(copy, nonatomic) NSString *myFriendsSayUnreadNum; // @synthesize myFriendsSayUnreadNum=_myFriendsSayUnreadNum;
@property(copy, nonatomic) NSString *myFriendsSayDesc; // @synthesize myFriendsSayDesc=_myFriendsSayDesc;
@property(copy, nonatomic) NSString *myFriendsSayTotalNum; // @synthesize myFriendsSayTotalNum=_myFriendsSayTotalNum;
@property(copy, nonatomic) NSString *myFriendsTreasureDesc; // @synthesize myFriendsTreasureDesc=_myFriendsTreasureDesc;
@property(copy, nonatomic) NSString *myFriendsTreasuretotalNum; // @synthesize myFriendsTreasuretotalNum=_myFriendsTreasuretotalNum;
@property(copy, nonatomic) NSString *movieID; // @synthesize movieID=_movieID;
- (void).cxx_destruct;
- (_Bool)showRedPoint;
- (_Bool)hasFriendFavor;
- (_Bool)hasFriendWala;
- (_Bool)hasUnreadFriendWala;
- (id)init;

@end

