//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWNewWalaMovieListViewController.h"

@class GWGetMyFriendWalaListProvider, NSString;

@interface GWNewMyFriendWalaListViewController : GWNewWalaMovieListViewController
{
    NSString *_relateId;
    NSString *_tag;
    NSString *_showFromNum;
    GWGetMyFriendWalaListProvider *_myFriendWalaListProvider;
}

@property(retain, nonatomic) GWGetMyFriendWalaListProvider *myFriendWalaListProvider; // @synthesize myFriendWalaListProvider=_myFriendWalaListProvider;
@property(copy, nonatomic) NSString *showFromNum; // @synthesize showFromNum=_showFromNum;
@property(copy, nonatomic) NSString *tag; // @synthesize tag=_tag;
@property(copy, nonatomic) NSString *relateId; // @synthesize relateId=_relateId;
- (void).cxx_destruct;
- (void)requeatWalaList:(_Bool)arg1 isClear:(_Bool)arg2;
- (void)viewDidLoad;
- (void)finishLoading;
- (void)beginRequest;
- (void)beginRefreshFromFooter;
- (void)beginRefreshFromHeader;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

@end

