//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWLoginBaseControl.h"

#import "GWPhoneCheckTextFieldDelegate-Protocol.h"
#import "UITextFieldDelegate-Protocol.h"

@class CALayer, GWPasswordTextField, GWPhoneCheckTextField, NSString, UITextField;
@protocol GWPasswordFindViewDelegate;

@interface GWPasswordFindView : GWLoginBaseControl <GWPhoneCheckTextFieldDelegate, UITextFieldDelegate>
{
    CALayer *phoneLayer;
    CALayer *checkLayer;
    CALayer *newPasswordLayer;
    id <GWPasswordFindViewDelegate> _delegate;
    UITextField *_phoneField;
    GWPhoneCheckTextField *_checkField;
    GWPasswordTextField *_newpasswordField;
}

@property(retain, nonatomic) GWPasswordTextField *newpasswordField; // @synthesize newpasswordField=_newpasswordField;
@property(retain, nonatomic) GWPhoneCheckTextField *checkField; // @synthesize checkField=_checkField;
@property(retain, nonatomic) UITextField *phoneField; // @synthesize phoneField=_phoneField;
@property(nonatomic) __weak id <GWPasswordFindViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)endLoading;
- (void)startLoading;
- (void)clickWithVoiceCodeButton;
- (void)defaultLayer;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (_Bool)checkTextLength;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)enterButtonClick:(id)arg1;
- (void)resignALL;
- (void)layoutSubviews;
- (void)loadAllControlers;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

