//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseTransistion.h"

@class UIImage, UIImageView, UIView;

@interface GWPushInTransistion : GWBaseTransistion
{
    UIImage *_shotImage;
    UIView *_backMaskView;
    UIImageView *_lastScreenShotView;
}

@property(retain, nonatomic) UIImageView *lastScreenShotView; // @synthesize lastScreenShotView=_lastScreenShotView;
@property(retain, nonatomic) UIView *backMaskView; // @synthesize backMaskView=_backMaskView;
@property(retain, nonatomic) UIImage *shotImage; // @synthesize shotImage=_shotImage;
- (void).cxx_destruct;
- (void)animateTransition:(id)arg1 From:(id)arg2 ToVC:(id)arg3 FromView:(id)arg4 ToView:(id)arg5;
- (id)init;

@end

