//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "Movie.h"

@class NSString;

@interface GWRankMovie : Movie
{
    NSString *_yesterday;
    NSString *_todayRank;
    NSString *_yesterdayRank;
    NSString *_showDays;
    NSString *_total;
    NSString *_today;
    NSString *_boxrank;
}

@property(retain, nonatomic) NSString *boxrank; // @synthesize boxrank=_boxrank;
@property(retain, nonatomic) NSString *today; // @synthesize today=_today;
@property(retain, nonatomic) NSString *total; // @synthesize total=_total;
@property(retain, nonatomic) NSString *showDays; // @synthesize showDays=_showDays;
@property(retain, nonatomic) NSString *yesterdayRank; // @synthesize yesterdayRank=_yesterdayRank;
@property(retain, nonatomic) NSString *todayRank; // @synthesize todayRank=_todayRank;
@property(retain, nonatomic) NSString *yesterday; // @synthesize yesterday=_yesterday;
- (void).cxx_destruct;

@end

