//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class GWImagePolicyView, UIImageView, UILabel;
@protocol GWAppTypeDelegate;

@interface GWRelationInfoView : UIView
{
    _Bool _hideMark;
    id <GWAppTypeDelegate> _releatedInfo;
    GWImagePolicyView *_postImageView;
    UILabel *_relationNameLabel;
    UILabel *_relationEngNameLabel;
    UILabel *_descriptionLabel;
    UILabel *_replyCountLabel;
    UILabel *_endLabel;
    UILabel *_addressLabel;
    UIImageView *_rightArrowImageView;
}

@property(retain, nonatomic) UIImageView *rightArrowImageView; // @synthesize rightArrowImageView=_rightArrowImageView;
@property(retain, nonatomic) UILabel *addressLabel; // @synthesize addressLabel=_addressLabel;
@property(retain, nonatomic) UILabel *endLabel; // @synthesize endLabel=_endLabel;
@property(retain, nonatomic) UILabel *replyCountLabel; // @synthesize replyCountLabel=_replyCountLabel;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *relationEngNameLabel; // @synthesize relationEngNameLabel=_relationEngNameLabel;
@property(retain, nonatomic) UILabel *relationNameLabel; // @synthesize relationNameLabel=_relationNameLabel;
@property(retain, nonatomic) GWImagePolicyView *postImageView; // @synthesize postImageView=_postImageView;
@property(nonatomic) _Bool hideMark; // @synthesize hideMark=_hideMark;
@property(nonatomic) __weak id <GWAppTypeDelegate> releatedInfo; // @synthesize releatedInfo=_releatedInfo;
- (void).cxx_destruct;
- (void)hideRightArrow:(_Bool)arg1;
- (void)refreshFrame;
- (id)activityLeaveDays;
- (id)activityReplyCount;
- (void)updateDramaForWP;
- (_Bool)isDramaReleated;
- (_Bool)isActivityReleated;
- (_Bool)isCinemaReleated;
- (_Bool)isStarReleated;
- (_Bool)isMovieReleated;
- (id)initWithFrame:(struct CGRect)arg1;

@end

