//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWObject.h"

@class NSString;

@interface GWSeatErrorModel : GWObject
{
    NSString *_errorcode;
    NSString *_errormsg;
    NSString *_errorimg;
}

@property(retain, nonatomic) NSString *errorimg; // @synthesize errorimg=_errorimg;
@property(retain, nonatomic) NSString *errormsg; // @synthesize errormsg=_errormsg;
@property(retain, nonatomic) NSString *errorcode; // @synthesize errorcode=_errorcode;
- (void).cxx_destruct;

@end

