//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "STHeaderView.h"

@class NSMutableArray;

@interface GWSwipeTableHeaderView : STHeaderView
{
    _Bool _beManualTouch;
    NSMutableArray *_responseArray;
}

@property(retain, nonatomic) NSMutableArray *responseArray; // @synthesize responseArray=_responseArray;
@property(nonatomic) _Bool beManualTouch; // @synthesize beManualTouch=_beManualTouch;
- (void).cxx_destruct;
- (id)responseView:(struct CGPoint)arg1;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

