//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class GWImageView, MarkLabel, StarCountView, UILabel;

@interface GWUCLoveMovieView : UIView
{
    GWImageView *_movieLogoImageView;
    UILabel *_movieNameLabel;
    StarCountView *_starCountView;
    MarkLabel *_marklabel;
}

@property(retain, nonatomic) MarkLabel *marklabel; // @synthesize marklabel=_marklabel;
@property(retain, nonatomic) StarCountView *starCountView; // @synthesize starCountView=_starCountView;
@property(retain, nonatomic) UILabel *movieNameLabel; // @synthesize movieNameLabel=_movieNameLabel;
@property(retain, nonatomic) GWImageView *movieLogoImageView; // @synthesize movieLogoImageView=_movieLogoImageView;
- (void).cxx_destruct;
- (void)layoutViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

