//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class GWImagePolicyView, GWMarkLabel, UILabel, UIView;

@interface GWUserCinemaColloctionTableViewCell : UITableViewCell
{
    UILabel *_titleLabel;
    UILabel *_cinemaAddressLabel;
    UILabel *_detailLabel;
    GWMarkLabel *_scoreView;
    UILabel *_distanceLabel;
    GWImagePolicyView *_postImageView;
    UIView *_backView;
}

@property(retain, nonatomic) UIView *backView; // @synthesize backView=_backView;
@property(retain, nonatomic) GWImagePolicyView *postImageView; // @synthesize postImageView=_postImageView;
@property(retain, nonatomic) UILabel *distanceLabel; // @synthesize distanceLabel=_distanceLabel;
@property(retain, nonatomic) GWMarkLabel *scoreView; // @synthesize scoreView=_scoreView;
@property(retain, nonatomic) UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(retain, nonatomic) UILabel *cinemaAddressLabel; // @synthesize cinemaAddressLabel=_cinemaAddressLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
- (void)showCinemaTagWithTagIconArray:(id)arg1;
- (void)layoutSubviews;
- (void)showCellWithCellObject:(id)arg1;

@end

