//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSString;

@interface GWWebShareItem : NSObject
{
    NSString *_title;
    NSString *_content;
    NSString *_urlLink;
    NSString *_logo;
    NSArray *_platFormArr;
}

@property(retain, nonatomic) NSArray *platFormArr; // @synthesize platFormArr=_platFormArr;
@property(copy, nonatomic) NSString *logo; // @synthesize logo=_logo;
@property(copy, nonatomic) NSString *urlLink; // @synthesize urlLink=_urlLink;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (_Bool)isReady;

@end

