//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSDate.h>

@interface NSDate (KalAdditions)
+ (id)dateEndOfWeek;
+ (id)dateStartOfWeek;
+ (id)dateStartOfDay:(id)arg1;
+ (id)dateWithFromString:(id)arg1;
- (long long)numDaysInMonth;
- (id)offsetDay:(long long)arg1;
- (id)offsetHours:(long long)arg1;
- (id)offsetMonth:(long long)arg1;
- (long long)firstWeekDayInMonth;
- (long long)second;
- (long long)minute;
- (long long)hour;
- (long long)day;
- (long long)month;
- (long long)year;
- (unsigned long long)cc_numberOfDaysInMonth;
- (unsigned long long)cc_weekday;
- (id)cc_componentsForYearMonthDayHourMinuteAndSecond;
- (id)cc_componentsForMonthDayAndYear;
- (id)cc_dateByMovingToFirstDayOfTheFollowingMonth;
- (id)cc_dateByMovingToFirstDayOfThePreviousMonth;
- (id)cc_dateByMovingToFirstDayOfTheMonth;
- (id)cc_dateByMovingToEndOfDay;
- (id)cc_dateByMovingToBeginningOfDay;
@end

