//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (ScaleSize)
- (id)changeImageTintColor:(id)arg1;
- (id)roundedCornerImageWithCornerRadius:(double)arg1;
- (id)scaleImageWithSize:(struct CGSize)arg1;
@end

