//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIImage.h>

@interface UIImage (WPQRcode)
+ (id)qrCodeLogoImageWithQRImage:(id)arg1 logo:(id)arg2;
+ (id)qrCodeColorImageWithQRImage:(id)arg1 color:(id)arg2;
+ (id)wp_generateQRcodeImageWithContentStr:(id)arg1 withSize:(double)arg2 logo:(id)arg3 color:(id)arg4 inputCorrectionLevelType:(unsigned long long)arg5;
+ (id)createNonInterpolatedUIImageFormCIImage:(id)arg1 withSize:(double)arg2;
+ (id)wp_generateQRcodeImageWithContentStr:(id)arg1 withSize:(double)arg2 inputCorrectionLevelType:(unsigned long long)arg3;
+ (id)wp_generateQRcodeImageWithContentStr:(id)arg1 withSize:(double)arg2;
@end

