//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UILabel.h>

@interface UILabel (SFAddition)
- (void)setLineSpacing:(double)arg1 withText:(id)arg2;
- (double)fitHeightByTextUsingCurrentFontWithMaxHeight:(double)arg1;
- (double)fitHeightByTextUsingCurrentFontWithMaxNumOfLines:(long long)arg1;
@end

