//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWObject.h"

@class NSArray, NSString;

@interface WPDeliveryInfoModel : GWObject
{
    NSString *_delivCompany;
    NSString *_delivNO;
    NSString *_page;
    NSString *_perpage;
    NSString *_searchTime;
    NSString *_total;
    NSArray *_setupInfoArray;
}

+ (id)mj_objectClassInArray;
+ (id)mj_replacedKeyFromPropertyName;
@property(retain, nonatomic) NSArray *setupInfoArray; // @synthesize setupInfoArray=_setupInfoArray;
@property(copy, nonatomic) NSString *total; // @synthesize total=_total;
@property(copy, nonatomic) NSString *searchTime; // @synthesize searchTime=_searchTime;
@property(copy, nonatomic) NSString *perpage; // @synthesize perpage=_perpage;
@property(copy, nonatomic) NSString *page; // @synthesize page=_page;
@property(copy, nonatomic) NSString *delivNO; // @synthesize delivNO=_delivNO;
@property(copy, nonatomic) NSString *delivCompany; // @synthesize delivCompany=_delivCompany;
- (void).cxx_destruct;

@end

