//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSDictionary, UILabel;

@interface WPHelpTipStringCell : UITableViewCell
{
    long long _helpTipStyleType;
    NSDictionary *_dicDate;
    UILabel *_subTitleLabel;
    UILabel *_subContentLabel;
}

+ (id)getAttributeTextForHelpTip:(id)arg1;
@property(retain, nonatomic) UILabel *subContentLabel; // @synthesize subContentLabel=_subContentLabel;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
@property(retain, nonatomic) NSDictionary *dicDate; // @synthesize dicDate=_dicDate;
@property(nonatomic) long long helpTipStyleType; // @synthesize helpTipStyleType=_helpTipStyleType;
- (void).cxx_destruct;
- (void)setDateForCell:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

