//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseViewController.h"

#import "WPOrderRightsListCellDelegate-Protocol.h"

@class NSArray, NSDictionary, NSString, UITableView, UIView, WPRightsModel;

@interface WPMovieRightsListViewController : GWBaseViewController <WPOrderRightsListCellDelegate>
{
    UIView *_mainView;
    UITableView *_tableView;
    id _delegate;
    NSArray *_rightsArray;
    WPRightsModel *_selectedRightsModel;
    UIView *_blackView;
    NSDictionary *_rightsCacheDict;
}

@property(retain, nonatomic) NSDictionary *rightsCacheDict; // @synthesize rightsCacheDict=_rightsCacheDict;
@property(nonatomic) __weak UIView *blackView; // @synthesize blackView=_blackView;
@property(retain, nonatomic) WPRightsModel *selectedRightsModel; // @synthesize selectedRightsModel=_selectedRightsModel;
@property(retain, nonatomic) NSArray *rightsArray; // @synthesize rightsArray=_rightsArray;
@property(nonatomic) __weak id delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak UIView *mainView; // @synthesize mainView=_mainView;
- (void).cxx_destruct;
- (void)makesureSnackDidClick:(id)arg1;
- (void)cancel;
- (void)orderRightsListCell:(id)arg1 didClickRights:(id)arg2 rightsGoods:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setupTableView;
- (void)startAnimation;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)arg1 rightsArray:(id)arg2 selectedRightModel:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

