//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MarqueeLabel, NSString;

@interface WPNoticeView : UIView
{
    MarqueeLabel *_label;
    NSString *_noticeText;
    UIView *_contentView;
}

@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) NSString *noticeText; // @synthesize noticeText=_noticeText;
@property(retain, nonatomic) MarqueeLabel *label; // @synthesize label=_label;
- (void).cxx_destruct;
- (void)initial;
- (id)init;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

