//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class GWNumberSelectControl, UILabel, WPShowPriceBlockView, WPShowTimesModel, WPShowsPriceModel;
@protocol WPShowPriceListCellDelegate;

@interface WPShowPriceListCell : UITableViewCell
{
    _Bool _isPriceViewHide;
    id <WPShowPriceListCellDelegate> _delegate;
    WPShowPriceBlockView *_priceBlockView;
    GWNumberSelectControl *_numberSelectControl;
    WPShowsPriceModel *_cellModel;
    WPShowTimesModel *_currentTimesModel;
    UILabel *_tipsLabel;
}

@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) WPShowTimesModel *currentTimesModel; // @synthesize currentTimesModel=_currentTimesModel;
@property(retain, nonatomic) WPShowsPriceModel *cellModel; // @synthesize cellModel=_cellModel;
@property(retain, nonatomic) GWNumberSelectControl *numberSelectControl; // @synthesize numberSelectControl=_numberSelectControl;
@property(retain, nonatomic) WPShowPriceBlockView *priceBlockView; // @synthesize priceBlockView=_priceBlockView;
@property(nonatomic) _Bool isPriceViewHide; // @synthesize isPriceViewHide=_isPriceViewHide;
@property(nonatomic) __weak id <WPShowPriceListCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (double)allDiscountPriceWithDiscountProgram:(id)arg1;
- (id)tipsWithDiscountProgram:(id)arg1;
- (id)discountProgramWithPackageTicketByBasicPriceModel:(id)arg1;
- (void)updateTipsTitleWithPriceModel:(id)arg1;
- (unsigned long long)calculateMaxBuyNumber;
- (void)configShowPriceListCellWithModel:(id)arg1 timesModel:(id)arg2;
- (void)prepareSetCallBack;
- (void)setViews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

