//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class NSArray, NSMutableArray, UIImageView, UILabel, UIView, WPShowTimesModel;
@protocol WPShowNoSeatTimesCellDelegate;

@interface WPShowNoSeatTimesCell : UITableViewCell
{
    _Bool _isMultiPriceSale;
    _Bool _isDiscount;
    id <WPShowNoSeatTimesCellDelegate> _delegate;
    WPShowTimesModel *_viewModel;
    CDUnknownBlockType _priceBlockViewClick;
    UIView *_titleBackgroundView;
    UILabel *_titleLabel;
    UIImageView *_arrowIconView;
    UILabel *_statusLabel;
    UIView *_contentBackgroundView;
    UIView *_buttonBackgroundView;
    UILabel *_detailLabel;
    UIImageView *_discountImageView;
    NSArray *_priceArray;
    NSMutableArray *_priceViewArray;
}

@property(nonatomic) _Bool isDiscount; // @synthesize isDiscount=_isDiscount;
@property(nonatomic) _Bool isMultiPriceSale; // @synthesize isMultiPriceSale=_isMultiPriceSale;
@property(retain, nonatomic) NSMutableArray *priceViewArray; // @synthesize priceViewArray=_priceViewArray;
@property(retain, nonatomic) NSArray *priceArray; // @synthesize priceArray=_priceArray;
@property(nonatomic) __weak UIImageView *discountImageView; // @synthesize discountImageView=_discountImageView;
@property(nonatomic) __weak UILabel *detailLabel; // @synthesize detailLabel=_detailLabel;
@property(nonatomic) __weak UIView *buttonBackgroundView; // @synthesize buttonBackgroundView=_buttonBackgroundView;
@property(nonatomic) __weak UIView *contentBackgroundView; // @synthesize contentBackgroundView=_contentBackgroundView;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
@property(retain, nonatomic) UIImageView *arrowIconView; // @synthesize arrowIconView=_arrowIconView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *titleBackgroundView; // @synthesize titleBackgroundView=_titleBackgroundView;
@property(copy, nonatomic) CDUnknownBlockType priceBlockViewClick; // @synthesize priceBlockViewClick=_priceBlockViewClick;
@property(retain, nonatomic) WPShowTimesModel *viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <WPShowNoSeatTimesCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)clickCellByPriceBlockView:(id)arg1;
- (void)priceBlockViewClick:(id)arg1;
- (void)generatePriceView:(id)arg1;
- (void)configPriceArray:(id)arg1 timesDescription:(id)arg2;
- (void)refreshDiscountStatus:(id)arg1;
- (void)refreshArrowStatus:(id)arg1;
- (void)timesClick;
- (void)configShowNoSeatTimesCellWithModel:(id)arg1 withPriceButtonAction:(CDUnknownBlockType)arg2;
- (void)awakeFromNib;

@end

