//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 20:42:30).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseTableViewController.h"

@class UIView, WPDeliveryInfoModel;

@interface WPShowOrderExpressViewController : GWBaseTableViewController
{
    UIView *_topInfoView;
    WPDeliveryInfoModel *_deliveryInfoModel;
}

@property(retain, nonatomic) WPDeliveryInfoModel *deliveryInfoModel; // @synthesize deliveryInfoModel=_deliveryInfoModel;
@property(retain, nonatomic) UIView *topInfoView; // @synthesize topInfoView=_topInfoView;
- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)setUpViews;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithShowOrderModel:(id)arg1;

@end

