//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CSFriendCenterFriendsToolbox-Protocol.h"

@class CSGraphQLConnectionSearchCollectionComponentToolbox, FBFriendingToolbox;

@interface CSFriendCenterFriendsToolbox : NSObject <CSFriendCenterFriendsToolbox>
{
    FBFriendingToolbox *_friendingToolbox;
    CSGraphQLConnectionSearchCollectionComponentToolbox *_searchCollectionToolbox;
    struct FBProfileFriendListSectionCellComponentActions _actions;
}

@property(readonly, nonatomic) struct FBProfileFriendListSectionCellComponentActions actions; // @synthesize actions=_actions;
@property(readonly, nonatomic) CSGraphQLConnectionSearchCollectionComponentToolbox *searchCollectionToolbox; // @synthesize searchCollectionToolbox=_searchCollectionToolbox;
@property(readonly, nonatomic) FBFriendingToolbox *friendingToolbox; // @synthesize friendingToolbox=_friendingToolbox;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithFriendingToolbox:(id)arg1 analyticsModule:(id)arg2 actions:(struct FBProfileFriendListSectionCellComponentActions)arg3;

@end

