//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@interface CSProfileFriendListComponent : CKCompositeComponent
{
}

+ (id)newWithPersonGraphQLID:(id)arg1 profileImageSize:(id)arg2 collectionToolbox:(id)arg3 graphQLToolbox:(id)arg4 isSelfProfile:(_Bool)arg5 executionContext:(const struct CSExecutionContext *)arg6;

@end

