//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FBAccountAccessKeyboardAwareView.h"

#import "UITextFieldDelegate-Protocol.h"

@class FBAccountAccessUISpinnerButton, FBButton, NSString, UILabel, UITapGestureRecognizer, UITextField, UIView;
@protocol FBAccountAccessTextEntryViewDelegate;

@interface FBAccountAccessTextEntryView : FBAccountAccessKeyboardAwareView <UITextFieldDelegate>
{
    unsigned long long _minTextLength;
    UITextField *_textField;
    FBAccountAccessUISpinnerButton *_continueButton;
    UITapGestureRecognizer *_recognizer;
    UILabel *_instructionsLabel;
    UILabel *_secondaryLabel;
    FBButton *_secondaryButton;
    UIView *_divider;
    id <FBAccountAccessTextEntryViewDelegate> _delegate;
}

@property(nonatomic) __weak id <FBAccountAccessTextEntryViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)_textDidChange:(id)arg1;
- (_Bool)_canContinue;
- (void)_didTapSecondaryButton;
- (void)_didTapContinue;
- (void)_didTapView;
- (void)setKeyboardType:(long long)arg1;
- (void)setViewState:(unsigned long long)arg1;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithPlaceholder:(id)arg1 keyboardType:(long long)arg2 minTextLength:(unsigned long long)arg3 secure:(_Bool)arg4 instructionsString:(id)arg5 secondaryString:(id)arg6 secondaryButtonTitle:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

