//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBButton, FBContactPoint, FBRichTextView, NSAttributedString;

@interface FBAccountConfirmationAdditionalPendingContactPointItemView : UIView
{
    FBRichTextView *_contactPointLabel;
    NSAttributedString *_attributedString;
    FBContactPoint *_contactPoint;
    FBButton *_deleteButton;
    CDUnknownBlockType _deleteContactPointBlock;
}

@property(copy, nonatomic) CDUnknownBlockType deleteContactPointBlock; // @synthesize deleteContactPointBlock=_deleteContactPointBlock;
@property(readonly, nonatomic) FBButton *deleteButton; // @synthesize deleteButton=_deleteButton;
@property(readonly, nonatomic) FBContactPoint *contactPoint; // @synthesize contactPoint=_contactPoint;
@property(readonly, copy, nonatomic) NSAttributedString *attributedString; // @synthesize attributedString=_attributedString;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_didTapDeleteButton;
- (id)_contactPointAttributedString;
- (id)initWithContactPoint:(id)arg1 actionHandler:(CDUnknownBlockType)arg2;

@end

