//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary, NSString;

@protocol FBAppReferralDataModel
- (NSString *)promotionText;
- (NSString *)promotionSource;
- (NSString *)promotionCode;
- (NSString *)previewImageURLString;
- (NSString *)destination;
- (NSString *)applinkURLString;
- (NSString *)applicationName;
- (NSString *)applicationID;
- (NSString *)applicationIconURLString;
- (NSDictionary *)toDictionary;
- (NSDictionary *)sponsoredContext;
@end

