//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class FBAppReferralPickerViewController, FBAppReferralPresenter, FBPlatformShareView, FBTextView;

@interface FBAppReferralViewController : UIViewController
{
    FBAppReferralPresenter *_presenter;
    FBPlatformShareView *_previewView;
    FBAppReferralPickerViewController *_pickerViewController;
    FBTextView *_messageView;
}

- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)setPickerViewController:(id)arg1;
- (id)pickerViewController;
- (void)setPreviewView:(id)arg1;
- (void)setMessageView:(id)arg1;
- (id)messageViewText;
- (void)viewDidLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithPresenter:(id)arg1;

@end

