//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBAudienceComposerView, NSString;

@protocol FBAudienceComposerViewDelegate <NSObject>
- (void)composerView:(FBAudienceComposerView *)arg1 didFinishWithText:(NSString *)arg2;
- (void)composerView:(FBAudienceComposerView *)arg1 didChangeToHeight:(double)arg2;
- (void)composerViewDidEndEditing:(FBAudienceComposerView *)arg1;
- (void)composerViewWillEndEditing:(FBAudienceComposerView *)arg1;
- (void)composerViewDidBeginEditing:(FBAudienceComposerView *)arg1;
- (void)composerViewWillBeginEditing:(FBAudienceComposerView *)arg1;
- (void)composerViewDidTapReact:(FBAudienceComposerView *)arg1;
- (void)composerViewDidTapRemixReply:(FBAudienceComposerView *)arg1;
- (void)composerViewDidTapCamera:(FBAudienceComposerView *)arg1;
- (void)composerViewDidTapComposer:(FBAudienceComposerView *)arg1;
@end

