//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBAudienceSeenStateListenerAnnouncer, FBTimeThrottler, FBUserSession, NSMutableDictionary;

@interface FBAudienceSeenStateHandler : NSObject
{
    FBUserSession *_session;
    FBAudienceSeenStateListenerAnnouncer *_announcer;
    NSMutableDictionary *_threadSeenStates;
    FBTimeThrottler *_throttler;
    _Bool _hasFetchedCache;
}

@property(readonly, nonatomic) _Bool hasFetchedCache; // @synthesize hasFetchedCache=_hasFetchedCache;
- (void).cxx_destruct;
- (id)_snacksThreadByApplyingOptimisticLastViewReceiptSeenTime:(id)arg1;
- (id)_directInboxThreadByApplyingOptimisticSeenState:(id)arg1;
- (void)_persistSeenStateToDisk;
- (void)_markCacheFetchCompleted;
- (void)_retrieveSeenStateFromDisk;
- (void)invalidateSeenStateExceptForThreadIDs:(id)arg1;
- (void)markViewReceiptsAsSeenForThread:(id)arg1 inBucket:(id)arg2;
- (void)markThreadAsSeen:(id)arg1 inBucket:(id)arg2;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)lastSeenTimeForThreadGraphQLID:(id)arg1;
- (id)initWithSession:(id)arg1;

@end

