//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBCompositeSectionComponent.h>

@interface FBBookmarksSegmentRowSectionComponent : FBCompositeSectionComponent
{
}

+ (id)newWithBookmark:(id)arg1 bookmarkIndex:(long long)arg2 section:(id)arg3 sectionIndex:(long long)arg4 isEditingSection:(_Bool)arg5 sectionTapHandler:(id)arg6 toolbox:(id)arg7;

@end

