//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBCompositeSectionComponent.h>

@class FBSectionComponentToolbox, NSString;

@interface FBCommunityRelatedGroupsSectionComponent : FBCompositeSectionComponent
{
    NSString *_groupID;
    FBSectionComponentToolbox *_toolbox;
}

+ (id)newWithGroupID:(id)arg1 toolbox:(id)arg2;
@property(readonly, nonatomic) FBSectionComponentToolbox *toolbox; // @synthesize toolbox=_toolbox;
@property(readonly, copy, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
- (void).cxx_destruct;

@end

