//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FBContactImporterAddressBookAccessRequester;

@protocol FBContactImporterAddressBookAccessRequesterDelegate
- (void)addressBookAccessRequesterDidAcceptSystemAlert:(FBContactImporterAddressBookAccessRequester *)arg1;
- (void)addressBookAccessRequesterDidRejectSystemAlert:(FBContactImporterAddressBookAccessRequester *)arg1;
- (void)addressBookAccessRequesterDidAcceptPreAlert:(FBContactImporterAddressBookAccessRequester *)arg1;
- (void)addressBookAccessRequesterDidRejectPreAlert:(FBContactImporterAddressBookAccessRequester *)arg1;
@end

