//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class FBDBLStoredUserManager, FBImageDownloader, NSArray, NSDictionary;
@protocol FBDBLSettingsCallbackProtocol;

@interface FBDBLUserListTableViewController : UITableViewController
{
    struct FBDBLUserListMetrics _metrics;
    NSArray *_userList;
    NSDictionary *_pendingUsers;
    FBImageDownloader *_imageDownloader;
    FBDBLStoredUserManager *_userManager;
    id <FBDBLSettingsCallbackProtocol> _settingsCallback;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)_makeCellConfigBuilder;
- (_Bool)_viewIsVisible;
- (void)_updateUsersWithAnimation:(id)arg1;
- (void)_updateUserList:(id)arg1;
- (void)_reloadUserAccounts;
- (struct UIEdgeInsets)_contentInsets;
- (unsigned long long)_imageSize;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)_configureCell:(id)arg1 indexPath:(id)arg2 userAccount:(id)arg3;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithImageDownloader:(id)arg1 settingsCallback:(id)arg2;

@end

