//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBNetworkerRequest.h>

@class NSString;

@interface FBDBLCheckPasswordRequest : FBNetworkerRequest
{
    NSString *_accountID;
    NSString *_password;
}

+ (double)networkTimeoutInSec;
- (void).cxx_destruct;
- (_Bool)allowRetry;
- (id)networkRequest;
- (id)initWithAccountID:(id)arg1 password:(id)arg2 callbackPerformer:(id)arg3;

@end

