//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBDirectInboxDataControllerListener-Protocol.h"
#import "FBJewelNetworkDataSource-Protocol.h"

@class FBUserSession, NSString;
@protocol FBDirectEntrypointDataProvider;

@interface FBDirectInboxJewelNetworkDataSource : NSObject <FBDirectInboxDataControllerListener, FBJewelNetworkDataSource>
{
    FBUserSession *_session;
    id <FBDirectEntrypointDataProvider> _dataProvider;
    _Bool _needsReload;
    unsigned long long _badgeCount;
}

@property(nonatomic) _Bool needsReload; // @synthesize needsReload=_needsReload;
- (void).cxx_destruct;
- (void)inboxDataControllerDidFinishLoading:(id)arg1;
- (void)inboxDataController:(id)arg1 didUpdateToBadgeCount:(unsigned long long)arg2 unseenReplyCount:(unsigned long long)arg3 unseenPhotoCount:(unsigned long long)arg4 unseenVideoCount:(unsigned long long)arg5;
- (void)inboxDataController:(id)arg1 didUpdateDirectInboxBuckets:(id)arg2;
- (void)setBadgeCount:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long badgeCount; // @synthesize badgeCount=_badgeCount;
- (void)cancelAllRequests;
- (void)reloadDataWithReason:(long long)arg1;
- (void)dealloc;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

