//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@class CKComponent;

@interface FBDirectInboxRowContentComponent : CKCompositeComponent
{
    CKComponent *_subtitleComponent;
    CKComponent *_promptComponent;
}

+ (id)newWithAvatarGraphQLID:(id)arg1 otherParticipant:(id)arg2 state:(long long)arg3 unseenCount:(long long)arg4 displayedDate:(id)arg5 previewItem:(id)arg6 lastActivityMessage:(id)arg7 isReplyToStory:(_Bool)arg8 shouldShowReplyOverlay:(_Bool)arg9 shouldShowReplayAction:(_Bool)arg10 shouldShowUnselectablePrompt:(_Bool)arg11 shouldRenderFullSeparator:(_Bool)arg12 toolbox:(id)arg13;
- (void).cxx_destruct;
- (vector_035bbd4a)animationsFromPreviousComponent:(id)arg1;

@end

