//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@class FBLivestreamVideoPlayerComponent;

@interface FBElectionHubLiveVideoComponent : CKCompositeComponent
{
    _Bool _logVideoOpened;
    _Bool _alwaysPollViewerCount;
    FBLivestreamVideoPlayerComponent *_livestreamVideoPlayerComponent;
}

+ (id)newWithVideo:(id)arg1 size:(const struct CKComponentSize *)arg2 alwaysPollViewerCount:(_Bool)arg3 logVideoOpened:(_Bool)arg4 toolbox:(id)arg5;
+ (id)newWithVideo:(id)arg1 size:(const struct CKComponentSize *)arg2 toolbox:(id)arg3;
@property(readonly, nonatomic) _Bool alwaysPollViewerCount; // @synthesize alwaysPollViewerCount=_alwaysPollViewerCount;
@property(readonly, nonatomic) FBLivestreamVideoPlayerComponent *livestreamVideoPlayerComponent; // @synthesize livestreamVideoPlayerComponent=_livestreamVideoPlayerComponent;
- (void).cxx_destruct;
- (void)_didTapPlayAction:(id)arg1;

@end

