//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "FBExperimentListSearchResponderProtocol-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"
#import "UISearchDisplayDelegate-Protocol.h"

@class FBExperimentListSearchResultController, FBExperimentListViewControllerDataSource, FBPreferenceChangeConfirmer, FBUserSession, NSArray, NSString, UISearchDisplayController, UISwitch;
@protocol FBAlertViewCreating;

@interface FBExperimentListViewController : UITableViewController <UISearchDisplayDelegate, UIAlertViewDelegate, FBExperimentListSearchResponderProtocol>
{
    FBUserSession *_session;
    UISwitch *_overridesDisabledSwitch;
    FBPreferenceChangeConfirmer *_preferenceConfirmer;
    FBPreferenceChangeConfirmer *_experimentConfirmer;
    id <FBAlertViewCreating> _alertViewCreator;
    FBExperimentListViewControllerDataSource *_dataSource;
    FBExperimentListSearchResultController *_searchResultController;
    _Bool _fetchingConfigFromTask;
    _Bool _fetchedSuccessfullyFromTask;
    UISearchDisplayController *searchDisplayController;
    NSArray *_experimentNames;
    CDUnknownBlockType _confirmationBlock;
}

@property(copy, nonatomic) CDUnknownBlockType confirmationBlock; // @synthesize confirmationBlock=_confirmationBlock;
@property(copy, nonatomic) NSArray *experimentNames; // @synthesize experimentNames=_experimentNames;
@property(retain, nonatomic) UISearchDisplayController *searchDisplayController; // @synthesize searchDisplayController;
- (void).cxx_destruct;
- (void)_showInvalidTaskNumberAlert;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldAutorotate;
- (void)performWithSearchResultItem:(id)arg1;
- (_Bool)searchDisplayController:(id)arg1 shouldReloadTableForSearchString:(id)arg2;
- (id)analyticsModule;
- (_Bool)fb_showAuxiliaryViewController;
- (_Bool)fb_showNavBarSearchField;
- (id)_getTitleForExperiment:(id)arg1 experiment:(id)arg2;
- (void)_importConfigFromTaskNumber:(id)arg1;
- (void)_importConfigFromTask;
- (void)_showConfigImportErrorAlertWithServerMessage:(id)arg1;
- (void)_handleConfigImportResponse:(id)arg1 error:(id)arg2;
- (_Bool)_importOverridesFromServerResponse:(id)arg1 error:(id)arg2 errorMessage:(id *)arg3;
- (void)_removeAllOverrides;
- (void)_tryToRegisterOverridesWithExperimentNames:(id)arg1 registrationBlock:(CDUnknownBlockType)arg2;
- (void)_refreshExperiments;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 sectionForSectionIndexTitle:(id)arg2 atIndex:(long long)arg3;
- (id)sectionIndexTitlesForTableView:(id)arg1;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_enableSwitchDidChange:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)selectExperimentAtIndexPath:(id)arg1;
- (id)initWithDataSource:(id)arg1 preferenceChangeConfirmer:(id)arg2 experimentChangeConfirmer:(id)arg3 alertViewCreator:(id)arg4 session:(id)arg5;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

