//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBExperimentListViewController, FBExperimentManager, NSArray, NSDictionary;

@interface FBExperimentListViewControllerDataSource : NSObject
{
    FBExperimentManager *_manager;
    FBExperimentListViewController *_controller;
    NSArray *_allSectionKeys;
    NSArray *_existingSectionKeys;
    NSDictionary *_sortedExperimentsByKey;
    NSArray *_sortedExperimentName;
    NSArray *_allExperimentNamesAndIndices;
}

@property(copy, nonatomic) NSArray *allExperimentNamesAndIndices; // @synthesize allExperimentNamesAndIndices=_allExperimentNamesAndIndices;
@property(copy, nonatomic) NSArray *sortedExperimentName; // @synthesize sortedExperimentName=_sortedExperimentName;
@property(copy, nonatomic) NSDictionary *sortedExperimentsByKey; // @synthesize sortedExperimentsByKey=_sortedExperimentsByKey;
@property(copy, nonatomic) NSArray *existingSectionKeys; // @synthesize existingSectionKeys=_existingSectionKeys;
@property(copy, nonatomic) NSArray *allSectionKeys; // @synthesize allSectionKeys=_allSectionKeys;
@property(nonatomic) __weak FBExperimentListViewController *controller; // @synthesize controller=_controller;
@property(readonly, nonatomic) FBExperimentManager *manager; // @synthesize manager=_manager;
- (void).cxx_destruct;
- (void)refresh;
- (id)experimentAtIndexPath:(id)arg1;
- (id)experimentWitExperimentName:(id)arg1;
- (unsigned long long)numberOfRowsInSection:(long long)arg1;
@property(readonly, nonatomic) unsigned long long numberOfSections;
- (id)_sectionKeyForExperimentName:(id)arg1;
- (id)initWithManager:(id)arg1;

@end

