//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIResponder.h>

#import "FBComponentTableViewDataSourceEventListener-Protocol.h"
#import "FBFriendingPossibilitiesEdgesListener-Protocol.h"
#import "FBIntermixedTabComponentDataSourceAdapterProtocol-Protocol.h"
#import "FBIntermixedTabFriendRequestEmptyStateCellManagerDelegate-Protocol.h"
#import "FBIntermixedTabRespondingAdapterProtocol-Protocol.h"
#import "FBIntermixedTabRowCountAnnouncingAdapterProtocol-Protocol.h"
#import "FBIntermixedTabSectionHeaderProviderDelegate-Protocol.h"

@class FBFriendingPossibilitiesDataCoordinator, FBFriendingPossibilitiesDataSource, FBFriendingSingleSectionStatefulWriteInterface, FBIntermixedTabComponentDataSourceAdapterAppearanceListenerAnnouncer, FBIntermixedTabComponentDataSourceAdapterReloadListenerAnnouncer, FBIntermixedTabComponentDataSourceAdapterRowCountListenerAnnouncer, FBIntermixedTabFriendRequestEmptyStateCellManager, FBIntermixedTabFriendRequestSectionHeaderManager, FBNotificationsComponentDataSourceWrapper, FBNotificationsFriendingIntermixedComponentContext, FBUserSession, FBViewControllerAppearanceLifecycleListenerAnnouncer, NSString;

@interface FBFriendRequestComponentDataSourceAdapter : UIResponder <FBFriendingPossibilitiesEdgesListener, FBComponentTableViewDataSourceEventListener, FBIntermixedTabFriendRequestEmptyStateCellManagerDelegate, FBIntermixedTabSectionHeaderProviderDelegate, FBIntermixedTabComponentDataSourceAdapterProtocol, FBIntermixedTabRespondingAdapterProtocol, FBIntermixedTabRowCountAnnouncingAdapterProtocol>
{
    FBUserSession *_session;
    FBNotificationsComponentDataSourceWrapper *_dataSource;
    FBViewControllerAppearanceLifecycleListenerAnnouncer *_lifecycleAnnouncer;
    unsigned long long _section;
    FBNotificationsFriendingIntermixedComponentContext *_context;
    FBFriendingSingleSectionStatefulWriteInterface *_statefulWriteInterface;
    FBFriendingPossibilitiesDataCoordinator *_friendingDataCoordinator;
    FBFriendingPossibilitiesDataSource *_friendingDataSource;
    FBIntermixedTabFriendRequestEmptyStateCellManager *_emptyStateManager;
    FBIntermixedTabFriendRequestSectionHeaderManager *_sectionHeaderManager;
    FBIntermixedTabComponentDataSourceAdapterAppearanceListenerAnnouncer *_appearanceAnnouncer;
    FBIntermixedTabComponentDataSourceAdapterReloadListenerAnnouncer *_reloadAnnouncer;
    FBIntermixedTabComponentDataSourceAdapterRowCountListenerAnnouncer *_rowCountAnnouncer;
    _Bool _componentsInitiallyAppeared;
    _Bool _isInView;
    _Bool _hasRenderedFriendRequestSection;
    _Bool _sectionHeaderNeedsUpdate;
    _Bool _hasRenderedFriendRequests;
    _Bool _needScrollToMiddle;
    unsigned long long _currentDisplayingEmptyCellType;
    _Bool _isReloading;
    CDUnknownBlockType _nextResponderProvider;
}

@property(copy, nonatomic) CDUnknownBlockType nextResponderProvider; // @synthesize nextResponderProvider=_nextResponderProvider;
@property(readonly, nonatomic) _Bool isReloading; // @synthesize isReloading=_isReloading;
- (void).cxx_destruct;
- (id)statefulWriteInterface;
- (double)dataSource:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)dataSource:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)dataSource:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (CKTypedComponentAction_4b39899e)_actionForEmptyStateCellType:(unsigned long long)arg1;
- (void)_openContactImporterFromEmptySection;
- (void)_openFriendCenterSearchPageFromEmptySection;
- (void)_openFriendCenterSuggestionsPageFromEmptySection;
- (void)_openFriendCenterRequestsPageFromSeeAll;
- (void)_openProfileForPerson:(id)arg1;
- (_Bool)_presentEntityCardsForFriendRequestsAtSelectedIndex:(unsigned long long)arg1;
- (void)_scheduleMarkAllSeenAsRead;
- (void)_sendOutJewelClearRequest;
- (void)_markAllUnseenAsUnreadAndSeen;
- (void)_showLoadingStateIfSyncError;
- (void)_refreshFriendRequestListWithSyncError:(id)arg1;
- (_Bool)_hasVisibleSeenButUnreadFriendRequests;
- (_Bool)_hasSeenButUnreadFriendRequests;
- (_Bool)_hasUnseenFriendRequests;
- (void)friendingPossibilitiesDataSource:(id)arg1 didUpdateEdges:(id)arg2 isReloading:(_Bool)arg3;
- (void)friendingPossibilitiesDataSource:(id)arg1 didRemoveEdges:(id)arg2 isReloading:(_Bool)arg3;
- (void)friendingPossibilitiesDataSource:(id)arg1 didInsertEdges:(id)arg2 forLoadType:(long long)arg3 withError:(id)arg4;
- (void)componentDidDisappearFromViewWithFrame:(struct CGRect)arg1 withModel:(id)arg2 atIndexPath:(id)arg3;
- (void)componentWillAppearInViewWithFrame:(struct CGRect)arg1 withModel:(id)arg2 atIndexPath:(id)arg3;
- (void)dataSourceDidEndUpdates:(id)arg1 changeset:(struct Changeset)arg2;
- (void)_updateSectionHeader;
- (void)sectionHeaderNeedsUpdate;
- (void)updateEmptyStateIfNecessary:(unsigned long long)arg1;
- (unsigned long long)rowCount;
- (void)_announceInitialAppearanceForEmptySectionIfNecessary;
- (void)_announceInitialAppearance;
- (void)intermixedTabComponentDataSourceAdapterComponentsWillInitiallyAppear:(id)arg1;
- (void)_doScrollToMiddle;
- (void)_scrollToMiddle;
- (void)viewControllerViewDidDisappear:(_Bool)arg1;
- (void)viewControllerViewWillAppear:(_Bool)arg1;
- (void)refreshFriendRequestSection;
- (_Bool)canPerformAction:(SEL)arg1 withSender:(id)arg2;
- (id)nextResponder;
- (void)reloadForPTR;
- (void)removeRowCountListener:(id)arg1;
- (void)addRowCountListener:(id)arg1;
- (void)removeReloadListener:(id)arg1;
- (void)addReloadListener:(id)arg1;
- (void)removeComponentsAppearanceListener:(id)arg1;
- (void)addComponentsAppearanceListener:(id)arg1;
- (void)setUpWithPYMKAdapter:(id)arg1;
- (void)setUpWithFriendingDataCoordinator:(id)arg1;
- (void)_setupInitialSection;
- (void)dealloc;
- (id)initWithSession:(id)arg1 componentDataSource:(id)arg2 controllerLifecycleAnnouncer:(id)arg3 section:(unsigned long long)arg4 context:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

