//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBFriendingPossibilitiesDataSource, NSArray, NSError;

@protocol FBFriendingPossibilitiesEdgesListener <NSObject>
- (void)friendingPossibilitiesDataSource:(FBFriendingPossibilitiesDataSource *)arg1 didUpdateEdges:(NSArray *)arg2 isReloading:(_Bool)arg3;
- (void)friendingPossibilitiesDataSource:(FBFriendingPossibilitiesDataSource *)arg1 didRemoveEdges:(NSArray *)arg2 isReloading:(_Bool)arg3;
- (void)friendingPossibilitiesDataSource:(FBFriendingPossibilitiesDataSource *)arg1 didInsertEdges:(NSArray *)arg2 forLoadType:(long long)arg3 withError:(NSError *)arg4;
@end

