//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBGraphQLQueryBuilder.h>

@interface FBFriendsNearbyContactsSectionsQueryBuilder : FBGraphQLQueryBuilder
{
}

+ (const struct FBGraphQLQueryCodegenInitInfo *)initInfoPtr;
+ (id)builderWithAccuracy:(id)arg1 contactId:(id)arg2 highlightIds:(id)arg3 itemCount:(id)arg4 itemCursor:(id)arg5 latitude:(id)arg6 longitude:(id)arg7 sectionCount:(id)arg8 sectionCursor:(id)arg9 staleTimeSeconds:(id)arg10;

@end

