//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FBGCKCastChannel, NSString;

@protocol FBGCKCastChannelDelegate
- (void)castChannelDidDisconnect:(FBGCKCastChannel *)arg1;
- (void)castChannelDidConnect:(FBGCKCastChannel *)arg1;
- (void)castChannel:(FBGCKCastChannel *)arg1 didReceiveTextMessage:(NSString *)arg2;
@end

