//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@class FBSectionComponentToolbox, NSString;

@interface FBGroupInsightsSectionBodyComponent : CKCompositeComponent
{
    FBSectionComponentToolbox *_toolbox;
    unsigned long long _type;
    NSString *_groupID;
}

+ (id)newWithGroupInsights:(const struct FBGroupInsightsGenericSectionComponentGraphQL *)arg1 groupID:(id)arg2 type:(unsigned long long)arg3 toolbox:(id)arg4;
@property(readonly, nonatomic) NSString *groupID; // @synthesize groupID=_groupID;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, nonatomic) FBSectionComponentToolbox *toolbox; // @synthesize toolbox=_toolbox;
- (void).cxx_destruct;
- (void)didTap;

@end

