//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

#import "FBHScrollImpressionLogging-Protocol.h"

@class FBFeedToolbox, FBMemFeedStory, FBMemGroup;

@interface FBGroupLocalNewsStoryComponent : CKCompositeComponent <FBHScrollImpressionLogging>
{
    FBMemFeedStory *_story;
    FBMemGroup *_parentGroup;
    FBFeedToolbox *_toolbox;
}

+ (id)newWithStory:(id)arg1 parentGroup:(id)arg2 scrollToNextStoryAction:(CKTypedComponentAction_4b39899e)arg3 toolbox:(id)arg4;
- (void).cxx_destruct;
- (void)becameFullyVisible;
- (void)_didTap;

@end

