//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBImageFilter-Protocol.h"

@class NSString, UIColor;

@interface FBGroupCasualGroupsFacepileHairlineFilter : NSObject <FBImageFilter>
{
    double _radius;
    UIColor *_lineColor;
    double _lineWidth;
}

- (void).cxx_destruct;
@property(readonly, copy, nonatomic) NSString *filterID;
- (id)filterImage:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithRadius:(double)arg1 lineColor:(id)arg2 lineWidth:(double)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

