//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "UITableViewDataSource-Protocol.h"

@class FBUserSession, NSMutableArray, NSString;

@interface FBGroupsLandingEditDataSource : NSObject <UITableViewDataSource>
{
    FBUserSession *_session;
    NSMutableArray *_favoriteGroups;
    NSMutableArray *_normalGroups;
    _Bool _showFavoriteSectionFooter;
    _Bool _showNormalSectionFooter;
}

- (void).cxx_destruct;
- (void)_tableView:(id)arg1 reloadSection:(unsigned long long)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 moveRowAtIndexPath:(id)arg2 toIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canMoveRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_syncFavorites;
- (_Bool)shouldShowFooterForSection:(long long)arg1;
- (_Bool)shouldShowHeaderForSection:(long long)arg1;
- (unsigned long long)countOfGroupsInSection:(unsigned long long)arg1;
- (id)_groupAtIndexPath:(id)arg1;
- (void)setGroups:(id)arg1;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

