//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSIndexPath;

@protocol FBGraphSearchMediaResultsDataBridgeDelegate <NSObject>
- (struct CGSize)itemSizeForItemAtIndexPath:(NSIndexPath *)arg1;
- (void)twiddleResultsInSection:(unsigned long long)arg1 resultEdges:(NSArray *)arg2 hasMore:(_Bool)arg3;
- (void)hideLoadingFooter;
- (void)showLoadingFooter;
- (void)createComponentDataSourceIfNeeded;
- (unsigned long long)enqueueChangeset:(const struct Changeset *)arg1 userInfo:(NSDictionary *)arg2;
- (void)didReceiveInitalContentWithAppliedFilters:(NSDictionary *)arg1 isOfflineContent:(_Bool)arg2;
- (void)updateViewState:(unsigned long long)arg1;
@end

