//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

#import "FIGCardContentHScrollChildCompliant-Protocol.h"

@class FBFeedToolbox, FBMemGroup, NSString;

@interface FBGroupWeeklyHighlightsNewMembersComponent : CKCompositeComponent <FIGCardContentHScrollChildCompliant>
{
    FBFeedToolbox *_toolbox;
    FBMemGroup *_group;
}

+ (id)newWithGroup:(id)arg1 toolbox:(id)arg2;
- (void).cxx_destruct;
- (void)_didTapSeeAll;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

