//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class CLLocation, FBUserSession;

@interface FBGroupLocalNewsViewController : UIViewController
{
    CLLocation *_location;
    FBUserSession *_session;
    UIViewController *_newsViewController;
}

- (void).cxx_destruct;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (_Bool)fb_showNavBarSearchField;
- (id)initWithSession:(id)arg1 location:(id)arg2;

@end

