//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class FBGroupDownloadRequestProvider, FBMemGroup, FBMemGroupPurpose, FBTransientViewStateManager, FBUserSession, NSString;
@protocol FBGroupsEditGroupPurposesViewControllerDelegate, FBGroupsInfoViewConfig, FBGroupsPresentationHandlerProtocol;

@interface FBGroupsEditGroupPurposesViewController : UITableViewController
{
    FBUserSession *_session;
    FBMemGroup *_group;
    FBGroupDownloadRequestProvider *_downloadProvider;
    FBTransientViewStateManager *_viewStateManager;
    FBMemGroupPurpose *_selectedGroupPurpose;
    NSString *_groupID;
    id <FBGroupsInfoViewConfig> _config;
    id <FBGroupsPresentationHandlerProtocol> _presentationHandler;
    id <FBGroupsEditGroupPurposesViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBGroupsEditGroupPurposesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_saveAndDismiss;
- (void)_didTapSave;
- (void)_didTapCancel;
- (void)_loadGroup;
- (id)_purposeForIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidLoad;
- (id)initWithGroupID:(id)arg1 session:(id)arg2 viewConfig:(id)arg3 presentationHandler:(id)arg4;

@end

