//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBGroupsLandingViewConfig-Protocol.h"

@class NSString, UIColor;

@interface FBGroupsLandingWildeViewConfig : NSObject <FBGroupsLandingViewConfig>
{
    _Bool _canShowCreatePog;
    _Bool _showAddToHomeScreenInMenu;
    _Bool _shouldAdjustContentInsets;
    _Bool _showCreateInFavorites;
    UIColor *_accentColor;
    UIColor *_pogTitleColor;
    UIColor *_sectionDividerColor;
    UIColor *_sectionHeaderTitleColor;
    UIColor *_backgroundColor;
    UIColor *_errorBackgroundColor;
}

+ (void)setShowCreateInFavorites:(_Bool)arg1;
+ (void)setErrorBackgroundColor:(id)arg1;
+ (void)setBackgroundColor:(id)arg1;
@property(nonatomic) _Bool showCreateInFavorites; // @synthesize showCreateInFavorites=_showCreateInFavorites;
@property(retain, nonatomic) UIColor *errorBackgroundColor; // @synthesize errorBackgroundColor=_errorBackgroundColor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) _Bool shouldAdjustContentInsets; // @synthesize shouldAdjustContentInsets=_shouldAdjustContentInsets;
@property(nonatomic) _Bool showAddToHomeScreenInMenu; // @synthesize showAddToHomeScreenInMenu=_showAddToHomeScreenInMenu;
@property(nonatomic) _Bool canShowCreatePog; // @synthesize canShowCreatePog=_canShowCreatePog;
@property(retain, nonatomic) UIColor *sectionHeaderTitleColor; // @synthesize sectionHeaderTitleColor=_sectionHeaderTitleColor;
@property(retain, nonatomic) UIColor *sectionDividerColor; // @synthesize sectionDividerColor=_sectionDividerColor;
@property(retain, nonatomic) UIColor *pogTitleColor; // @synthesize pogTitleColor=_pogTitleColor;
@property(retain, nonatomic) UIColor *accentColor; // @synthesize accentColor=_accentColor;
- (void).cxx_destruct;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

