//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FIGTabsComponentListener-Protocol.h"

@class FBMemAlbumsViewController, FBMemGroup, FBPhotosCollageInsetsTrackingViewController, FBUserSession, FIGTabsComponentHostingView, NSString, UIView;
@protocol FBGraphQLConnectionSyncStoreProtocol;

@interface FBGroupsPhotosListDetailViewController : UIViewController <FIGTabsComponentListener>
{
    FBUserSession *_session;
    FBMemGroup *_group;
    id <FBGraphQLConnectionSyncStoreProtocol> _mediaStore;
    FIGTabsComponentHostingView *_tabBarHostingView;
    UIView *_contentView;
    FBMemAlbumsViewController *_albumsViewController;
    FBPhotosCollageInsetsTrackingViewController *_groupPhotosViewController;
}

- (void).cxx_destruct;
- (id)_getTabsData;
- (void)_setupTabBar;
- (void)_initializeViewControllers;
- (void)_switchToIndex:(long long)arg1;
- (_Bool)fb_showNavBarSearchField;
- (void)didSelectTabWithIndex:(long long)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (id)initWithSession:(id)arg1 group:(id)arg2 mediaStore:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

