//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FIGCoverImageChanger-Protocol.h"
#import "NSCopying-Protocol.h"

@class FBUserSession, NSString;
@protocol FBGroupFeedCoverImageChangerDelegate;

@interface FBGroupFeedCoverImageChanger : NSObject <FIGCoverImageChanger, NSCopying>
{
    NSString *_groupGraphQLID;
    CDUnknownBlockType _didFailToChangeCoverImageBlock;
    CDUnknownBlockType _didChangeCoverImageBlock;
    id <FBGroupFeedCoverImageChangerDelegate> _delegate;
    FBUserSession *_session;
}

@property(retain, nonatomic) FBUserSession *session; // @synthesize session=_session;
@property(copy, nonatomic) NSString *groupGraphQLID; // @synthesize groupGraphQLID=_groupGraphQLID;
@property(nonatomic) __weak id <FBGroupFeedCoverImageChangerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_notifyDelegateDidFailToChangeCoverImageWithErrorType:(int)arg1;
- (void)_notifyDelegateDidChangeCoverImage;
- (void)_notifyDelegateWillChangeCoverImage;
- (void)_updateCoverImageWithGraphQLID:(id)arg1;
- (void)didSelectNewCoverImage:(id)arg1 didChangeCoverImageBlock:(CDUnknownBlockType)arg2 didFailToChangeCoverImageBlock:(CDUnknownBlockType)arg3;
- (void)didSelectNewCoverImageWithExistingPhoto:(id)arg1 didChangeCoverImageBlock:(CDUnknownBlockType)arg2 didFailToChangeCoverImageBlock:(CDUnknownBlockType)arg3;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

