//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FBEmbeddedTab-Protocol.h"

@class FBMemGroupConfigurationsConnection, FBUserSession, NSArray, NSString, UIScrollView, UIView;

@interface FBGroupPendingMemberListViewController : UIViewController <FBEmbeddedTab>
{
    NSString *_groupID;
    NSString *_pendingMemberType;
    NSString *_source;
    FBUserSession *_session;
    FBMemGroupConfigurationsConnection *_groupConfigs;
    NSArray *_possibleOrderings;
    UIViewController *_childViewController;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (void)refreshData;
- (_Bool)fb_showNavBarSearchField;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;
- (id)initWithGroupID:(id)arg1 pendingMemberType:(id)arg2 source:(id)arg3 session:(id)arg4 groupConfigs:(id)arg5 possibleOrderings:(id)arg6;

// Remaining properties
@property(retain, nonatomic) UIView *secondaryStickyHeaderView;

@end

