//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBImageDownloadLogger-Protocol.h"
#import "FBImageDownloaderRequestManagerDelegate-Protocol.h"
#import "FBImageStreamingService-Protocol.h"
#import "FBInvalidating-Protocol.h"
#import "FBStreamingImageResponseHandlerDelegate-Protocol.h"

@class FBImageDownloaderRequestManager, NSString;
@protocol FBImageDownloaderCache;

@interface FBImageStreamer : NSObject <FBInvalidating, FBImageDownloadLogger, FBStreamingImageResponseHandlerDelegate, FBImageDownloaderRequestManagerDelegate, FBImageStreamingService>
{
    id <FBImageDownloaderCache> _imageCache;
    FBImageDownloaderRequestManager *_requestManager;
    struct FBStreamingFlagsManager _desiredImageFlagsForUrls;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)allImageDownloadsRemovedForURL:(id)arg1;
- (void)imageDownloadAdded:(id)arg1;
- (void)reachedMaxDesiredFlagForURL:(id)arg1 result:(id)arg2 isLastFlag:(_Bool)arg3;
- (unsigned long long)maxDesiredFlagForURL:(id)arg1;
- (id)_responseHandlerForRequest:(id)arg1 response:(id)arg2 URL:(id)arg3 partialData:(id)arg4;
- (CDUnknownBlockType)_createResponseHandlerFactoryBlockForURL:(id)arg1 withPartialData:(id)arg2;
- (void)logFinishWithType:(unsigned long long)arg1;
- (void)invalidate;
@property(readonly, nonatomic, getter=isValid) _Bool valid;
- (void)clearAllImageCache:(CDUnknownBlockType)arg1;
- (void)cancelStreamingForToken:(id)arg1;
- (_Bool)_handleStreamingCachedImage:(id)arg1 withDownloadResult:(unsigned long long)arg2 forDownload:(id)arg3;
- (id)streamImageWithURL:(id)arg1 desiredImageFlag:(unsigned long long)arg2 imageFlagsToBeNotified:(unsigned long long)arg3 scenePath:(id)arg4 priority:(long long)arg5 analyticsTags:(id)arg6 options:(unsigned long long)arg7 queue:(id)arg8 streamingBlock:(CDUnknownBlockType)arg9;
- (id)initWithNetworker:(id)arg1 imageCache:(id)arg2 configuration:(id)arg3 scenePathAnnouncer:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

