//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSString, UIImage;

@protocol FBImageFilter <NSObject, NSCopying>
@property(readonly, copy, nonatomic) NSString *filterID;
- (id)copy;
- (UIImage *)filterImage:(UIImage *)arg1;
@end

