//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBImmersiveImageStitchStatus, FBImmersiveImageStitcher, FBTimer, NSMutableArray;
@protocol FBImmersiveImageStitchStatusUpdateDelegate, OS_dispatch_queue;

@interface FBImmersiveImageStitchManager : NSObject
{
    double _stitchImageMaxWidth;
    id <FBImmersiveImageStitchStatusUpdateDelegate> _statusUpdateDelegate;
    FBImmersiveImageStitcher *_stitcher;
    NSMutableArray *_capturedCenters;
    NSObject<OS_dispatch_queue> *_stitcherQueue;
    FBTimer *_stitchingStatusTimer;
    FBImmersiveImageStitchStatus *_storedStitchStatus;
}

@property(retain, nonatomic) FBImmersiveImageStitchStatus *storedStitchStatus; // @synthesize storedStitchStatus=_storedStitchStatus;
@property(retain, nonatomic) FBTimer *stitchingStatusTimer; // @synthesize stitchingStatusTimer=_stitchingStatusTimer;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *stitcherQueue; // @synthesize stitcherQueue=_stitcherQueue;
@property(retain, nonatomic) NSMutableArray *capturedCenters; // @synthesize capturedCenters=_capturedCenters;
@property(retain, nonatomic) FBImmersiveImageStitcher *stitcher; // @synthesize stitcher=_stitcher;
@property(nonatomic) __weak id <FBImmersiveImageStitchStatusUpdateDelegate> statusUpdateDelegate; // @synthesize statusUpdateDelegate=_statusUpdateDelegate;
@property(nonatomic) double stitchImageMaxWidth; // @synthesize stitchImageMaxWidth=_stitchImageMaxWidth;
- (void).cxx_destruct;
@property(readonly, nonatomic) FBImmersiveImageStitchStatus *currentStitchStatus;
- (void)reset;
- (void)startStitchingWithLoggingCallback:(CDUnknownBlockType)arg1 completionCallbackQueue:(id)arg2 horizontalCoverage:(float)arg3 verticalCoverage:(float)arg4 completion:(CDUnknownBlockType)arg5;
- (_Bool)processImageForStitchingIfNeeded:(id)arg1 relativeAttitude:(struct _GLKQuaternion)arg2 gravityAlignedAttitude:(struct _GLKQuaternion)arg3 innerFov:(double)arg4;
- (_Bool)_isGoodFrameForStitchingAtYaw:(double)arg1 Pitch:(double)arg2 Roll:(double)arg3 InnerFov:(double)arg4;
- (double)_centralAngle:(double)arg1 pitch1:(double)arg2 yaw2:(double)arg3 pitch2:(double)arg4;
- (void)dealloc;
- (id)init;

@end

