//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "FBInstantGamePermissionViewDelegate-Protocol.h"
#import "FBQuicksilverStartViewController-Protocol.h"

@class FBInstantGameContextTokenFetcher, FBInstantGameGamePlayViewerInfo, FBInstantGameLoadingCardView, FBInstantGameReferralInfo, FBInstantGameUIMetrics, FBMemInstantGamePrivacyNotice, FBQuicksilverGameInfo, FBUserSession, NSString;
@protocol FBQuicksilverStartViewControllerDelegate;

@interface FBInstantGamePermissionViewController : UIViewController <FBInstantGamePermissionViewDelegate, FBQuicksilverStartViewController>
{
    FBQuicksilverGameInfo *_gameInfo;
    FBMemInstantGamePrivacyNotice *_privacyNotice;
    FBInstantGameGamePlayViewerInfo *_viewerInfo;
    FBUserSession *_session;
    FBInstantGameLoadingCardView *_cardView;
    FBInstantGameReferralInfo *_referralInfo;
    FBInstantGameContextTokenFetcher *_contextTokenFetcher;
    FBInstantGameUIMetrics *_metrics;
    NSString *_contextToken;
    _Bool _isContextTokenQueryFinished;
    _Bool _isPermissionGranted;
    _Bool _isLoadingFinished;
    _Bool _isGameStarted;
    id <FBQuicksilverStartViewControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBQuicksilverStartViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setPermissionGrantedAndTryStartGame;
- (void)_setLoadingFinishedAndTryStartGame;
- (void)_setContextTokenAndTryStartGame:(id)arg1;
- (void)_startGameIfReady;
- (void)_doStartGameIfReady;
- (_Bool)_isContextTokenValid;
- (void)_grantAllRequiredPermissions;
- (void)instantGamePermissionViewDidTapPlayButton:(id)arg1;
- (void)dismissStartViewWithCompletion:(CDUnknownBlockType)arg1;
- (void)didFinishGameLoading;
- (void)didProgressGameLoading:(double)arg1;
- (void)didStartGameLoading;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (id)initWithSession:(id)arg1 gameInfo:(id)arg2 privacyNotice:(id)arg3 viewerInfo:(id)arg4 referralInfo:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

