//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface FBIntermixedTabEntryPointCellModel : NSObject
{
    unsigned long long _type;
    unsigned long long _glyphName;
    NSString *_title;
    NSString *_subtitle;
    CKTypedComponentAction_4b39899e _action;
}

@property(readonly, nonatomic) CKTypedComponentAction_4b39899e action; // @synthesize action=_action;
@property(readonly, copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly, nonatomic) unsigned long long glyphName; // @synthesize glyphName=_glyphName;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithType:(unsigned long long)arg1 glyphName:(unsigned long long)arg2 title:(id)arg3 subtitle:(id)arg4 action:(CKTypedComponentAction_4b39899e)arg5;

@end

