//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBComponentCellAppearanceEventListener-Protocol.h"
#import "FBComponentTableViewDataSourceSelectionEventListener-Protocol.h"
#import "FBNotificationsPullToRefreshManagingListener-Protocol.h"
#import "FBViewControllerAppearanceLifecycleListener-Protocol.h"

@class FBNotificationsComponentDataSourceWrapper, FBNotificationsFriendingIntermixedPullToRefreshManager, FBViewControllerAppearanceLifecycleListenerAnnouncer, NSMutableSet, NSNotificationCenter, NSString;

@interface FBIntermixedTabFriendRequestLoggingHelper : NSObject <FBViewControllerAppearanceLifecycleListener, FBComponentCellAppearanceEventListener, FBComponentTableViewDataSourceSelectionEventListener, FBNotificationsPullToRefreshManagingListener>
{
    FBNotificationsComponentDataSourceWrapper *_componentDataSource;
    FBViewControllerAppearanceLifecycleListenerAnnouncer *_lifecycleAnnouncer;
    NSNotificationCenter *_notificationCenter;
    FBNotificationsFriendingIntermixedPullToRefreshManager *_pullToRefreshManager;
    _Bool _isInView;
    NSMutableSet *_seenFriendRequestIDs;
}

- (void).cxx_destruct;
- (void)_logFriendRequestImpression;
- (void)_saveVisibleFriendRequests;
- (void)dataSource:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)componentDidDisappearFromViewWithFrame:(struct CGRect)arg1 withModel:(id)arg2 atIndexPath:(id)arg3;
- (void)componentWillAppearInViewWithFrame:(struct CGRect)arg1 withModel:(id)arg2 atIndexPath:(id)arg3;
- (void)pullToRefreshManagerDidTriggerRefresh:(id)arg1;
- (void)viewControllerViewDidDisappear:(_Bool)arg1;
- (void)viewControllerViewWillAppear:(_Bool)arg1;
- (void)_didEnterBackground;
- (void)setUpWithPullToRefreshManager:(id)arg1;
- (void)dealloc;
- (id)initWithComponentDataSource:(id)arg1 controllerLifecycleAnnouncer:(id)arg2 notificationCenter:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

