//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSString, UIScrollView, UIVisualEffectView;
@protocol FBInstantGameEndContainerViewDelegate;

@interface FBInstantGameEndContainerView : UIView <UIScrollViewDelegate>
{
    UIScrollView *_horizontalScrollView;
    UIView *_gameInfoView;
    UIView *_endGameView;
    UIView *_scoreShareView;
    UIVisualEffectView *_blurredBackgroundView;
    UIVisualEffectView *_vibranceView;
    long long _currentScreen;
    id <FBInstantGameEndContainerViewDelegate> _delegate;
}

@property(nonatomic) __weak id <FBInstantGameEndContainerViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) long long currentScreen; // @synthesize currentScreen=_currentScreen;
- (void).cxx_destruct;
- (id)_blurEffectForScrollView:(id)arg1;
- (void)animateOutBlurEffectWithCompletion:(CDUnknownBlockType)arg1;
- (void)setContentOffsetToEndScreen:(long long)arg1 animated:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)setCurrentScreen:(long long)arg1;
- (void)layoutSubviews;
@property(readonly, nonatomic) UIScrollView *scrollView;
- (id)initWithGameInfoView:(id)arg1 endGameView:(id)arg2 scoreShareView:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

