//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class FBInstantGameUIMetrics, UIImageView;

@interface FBInstantGameRoundableCell : UITableViewCell
{
    UIImageView *_roundedImageView;
    FBInstantGameUIMetrics *_metrics;
}

- (void).cxx_destruct;
- (id)_roundedImageFromSpec:(long long)arg1 color:(id)arg2;
- (void)setRoundedCornerSpec:(long long)arg1 backgroundColor:(id)arg2;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

