//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBBackstagePublishingHandlerListener-Protocol.h"
#import "FBInlineSnacksPluginController-Protocol.h"
#import "FBSnacksDataControllerListener-Protocol.h"
#import "FBSnacksEventHandler-Protocol.h"

@class FBInlineSnacksModel, FBSnacksToolbox, FBUserSession, NSArray, NSString;
@protocol FBInlineSnacksControllerDelegate;

@interface FBInlineSnacksController : NSObject <FBSnacksDataControllerListener, FBBackstagePublishingHandlerListener, FBSnacksEventHandler, FBInlineSnacksPluginController>
{
    _Bool _loading;
    _Bool _isFeedVisible;
    _Bool _isCellShownInFeed;
    FBUserSession *_session;
    NSString *_trayLoadSource;
    NSArray *_nullStateBuckets;
    long long _numUploadAnimations;
    id <FBInlineSnacksControllerDelegate> _delegate;
    FBInlineSnacksModel *_model;
    FBSnacksToolbox *_toolbox;
}

@property(readonly, nonatomic) FBSnacksToolbox *toolbox; // @synthesize toolbox=_toolbox;
@property(retain, nonatomic) FBInlineSnacksModel *model; // @synthesize model=_model;
@property(nonatomic) __weak id <FBInlineSnacksControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)_shouldShowDataUploadingImprovement;
- (void)feedViewDidDisappear:(_Bool)arg1;
- (void)feedViewDidAppear:(_Bool)arg1 isFirstTime:(_Bool)arg2;
- (void)graphQLConnectionController:(id)arg1 didLoadEdgesFromNetworkLoad:(id)arg2;
- (void)graphQLConnectionController:(id)arg1 didReceiveEdgesFromNetworkLoad:(id)arg2;
- (void)graphQLConnectionController:(id)arg1 didCompleteLoad:(id)arg2;
- (void)graphQLConnectionController:(id)arg1 didBeginLoad:(id)arg2;
- (void)stream:(id)arg1 willStartLoading:(unsigned long long)arg2 refreshMode:(id)arg3 requestAnalyticsUUID:(id)arg4 userInfo:(id)arg5;
- (void)stream:(id)arg1 didFinishLoading:(unsigned long long)arg2 withResults:(id)arg3 requestAnalyticsUUID:(id)arg4 userInfo:(id)arg5;
- (void)_prefetchReactionsForFirstThreadWithModel:(id)arg1;
- (void)_prefetchSelfStackWithModel:(id)arg1;
- (void)_prefetchUnseenThreadsWithModel:(id)arg1;
- (void)_prefetchThreadsAndReactions;
- (id)_updateNullStateBucketsBasedOnFriendBuckets:(id)arg1 friendBuckets:(id)arg2;
- (void)_updateNullStateFriendBuckets:(id)arg1;
- (void)_setupNoCacheState;
- (_Bool)_isSnacksCellVisible;
- (void)_updateVisibilityForFeed:(_Bool)arg1 cellShown:(_Bool)arg2;
- (void)_logSnacksTrayImpression;
- (void)reloadModel;
- (void)publishingHandler:(id)arg1 didEnqueueTask:(id)arg2;
- (void)publishingHandler:(id)arg1 didFinishTask:(id)arg2 error:(id)arg3;
- (void)publishingHandlerDidFinishAllPublications:(id)arg1;
- (void)publishingHandler:(id)arg1 didTimeoutForTask:(id)arg2;
- (void)publishingHandler:(id)arg1 willPublishTask:(id)arg2;
- (void)publishingHandler:(id)arg1 didBeginProcessingVideosForTask:(id)arg2;
- (void)publishingHandler:(id)arg1 didUpdateProgress:(double)arg2 forTask:(id)arg3;
- (void)snacksDataController:(id)arg1 didUpdateBucket:(id)arg2;
- (void)snacksDataControllerDidFailToLoad:(id)arg1;
- (void)snacksDataController:(id)arg1 didUpdateStoryBucketData:(id)arg2 updateType:(unsigned long long)arg3;
- (void)updateVisibilityForCellShown:(_Bool)arg1;
- (void)reloadSnacksWithForceRefresh:(_Bool)arg1 delayCacheLoadDuringAppStart:(_Bool)arg2;
- (id)initWithToolbox:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

