//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBGenericFetcher, FBUserSession;

@interface FBInstantGameListFetcher : NSObject
{
    FBUserSession *_session;
    FBGenericFetcher *_genericFetcher;
    _Bool _shouldAllowQueryCaching;
    long long _cacheThresholdInSeconds;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool isFetching;
- (void)fetchFlatGameListWithExcludedGameID:(id)arg1 referralInfo:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
- (void)_logFetchFailure;
- (void)_logFetchSuccessFromCache:(_Bool)arg1;
- (void)_handleFailureWithFailureBlock:(CDUnknownBlockType)arg1 error:(id)arg2 querySurface:(id)arg3 referralInfo:(id)arg4;
- (void)_handleSuccessWithSuccessBlock:(CDUnknownBlockType)arg1 responseObject:(id)arg2;
- (id)fetchSectionGameListWithQuerySurface:(id)arg1 sectionType:(id)arg2 referralInfo:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
- (id)initWithSession:(id)arg1 shouldAllowQueryCaching:(_Bool)arg2;

@end

