//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBInstantGameGamePlayStrategy-Protocol.h"

@class FBUserSession, NSString;

@interface FBInstantGameFriendGamePlayStrategy : NSObject <FBInstantGameGamePlayStrategy>
{
    FBUserSession *_session;
}

- (void).cxx_destruct;
- (id)leaderboardDataFromViewerInfo:(id)arg1 nonFriendLeaderboardData:(id)arg2 friendLeaderboardData:(id)arg3;
- (id)scoreStringFromViewerInfo:(id)arg1;
- (id)scoreFromViewerInfo:(id)arg1;
- (void)tearDown;
- (void)updateGameScore:(id)arg1;
- (id)initWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

