//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBLocationAccessManagerDelegate-Protocol.h"

@class FBLocationAccessManager, NSString;

@interface FBLocationServicesRegistrar : NSObject <FBLocationAccessManagerDelegate>
{
    FBLocationAccessManager *_locationAccessManager;
}

- (void).cxx_destruct;
- (void)locationAccessManager:(id)arg1 accessDenied:(unsigned long long)arg2;
- (void)locationAccessManager:(id)arg1 accessGranted:(id)arg2;
- (void)requestLocationAccessWithSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

