//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBValueObject.h>

#import "NSCopying-Protocol.h"

@interface FBMAppProperties : FBValueObject <NSCopying>
{
    _Bool _supportZeroRating;
    _Bool _supportLocation;
    _Bool _shouldUpgradeCredentials;
    _Bool _supportAppStartDelaying;
    _Bool _supportGroupsTab;
    _Bool _supportEarlyStartForLongAsyncBackgroundJobs;
    _Bool _supportTypingNotifications;
    _Bool _supportMessageThreadDiskStorage;
    _Bool _shouldUseMessengerSharedDiskStore;
    _Bool _shouldDisplayiPadLoginScreenInsetInFrame;
    _Bool _shouldOwnSharedDiskStore;
    _Bool _supportPlatformComposer;
    _Bool _supportMessengerEmoji;
    _Bool _supportMessengerCode;
    unsigned long long _supportedInterfaceOrientations;
}

@property(readonly, nonatomic) _Bool supportMessengerCode; // @synthesize supportMessengerCode=_supportMessengerCode;
@property(readonly, nonatomic) unsigned long long supportedInterfaceOrientations; // @synthesize supportedInterfaceOrientations=_supportedInterfaceOrientations;
@property(readonly, nonatomic) _Bool supportMessengerEmoji; // @synthesize supportMessengerEmoji=_supportMessengerEmoji;
@property(readonly, nonatomic) _Bool supportPlatformComposer; // @synthesize supportPlatformComposer=_supportPlatformComposer;
@property(readonly, nonatomic) _Bool shouldOwnSharedDiskStore; // @synthesize shouldOwnSharedDiskStore=_shouldOwnSharedDiskStore;
@property(readonly, nonatomic) _Bool shouldDisplayiPadLoginScreenInsetInFrame; // @synthesize shouldDisplayiPadLoginScreenInsetInFrame=_shouldDisplayiPadLoginScreenInsetInFrame;
@property(readonly, nonatomic) _Bool shouldUseMessengerSharedDiskStore; // @synthesize shouldUseMessengerSharedDiskStore=_shouldUseMessengerSharedDiskStore;
@property(readonly, nonatomic) _Bool supportMessageThreadDiskStorage; // @synthesize supportMessageThreadDiskStorage=_supportMessageThreadDiskStorage;
@property(readonly, nonatomic) _Bool supportTypingNotifications; // @synthesize supportTypingNotifications=_supportTypingNotifications;
@property(readonly, nonatomic) _Bool supportEarlyStartForLongAsyncBackgroundJobs; // @synthesize supportEarlyStartForLongAsyncBackgroundJobs=_supportEarlyStartForLongAsyncBackgroundJobs;
@property(readonly, nonatomic) _Bool supportGroupsTab; // @synthesize supportGroupsTab=_supportGroupsTab;
@property(readonly, nonatomic) _Bool supportAppStartDelaying; // @synthesize supportAppStartDelaying=_supportAppStartDelaying;
@property(readonly, nonatomic) _Bool shouldUpgradeCredentials; // @synthesize shouldUpgradeCredentials=_shouldUpgradeCredentials;
@property(readonly, nonatomic) _Bool supportLocation; // @synthesize supportLocation=_supportLocation;
@property(readonly, nonatomic) _Bool supportZeroRating; // @synthesize supportZeroRating=_supportZeroRating;
- (id)initWithSupportZeroRating:(_Bool)arg1 supportLocation:(_Bool)arg2 shouldUpgradeCredentials:(_Bool)arg3 supportAppStartDelaying:(_Bool)arg4 supportGroupsTab:(_Bool)arg5 supportEarlyStartForLongAsyncBackgroundJobs:(_Bool)arg6 supportTypingNotifications:(_Bool)arg7 supportMessageThreadDiskStorage:(_Bool)arg8 shouldUseMessengerSharedDiskStore:(_Bool)arg9 shouldDisplayiPadLoginScreenInsetInFrame:(_Bool)arg10 shouldOwnSharedDiskStore:(_Bool)arg11 supportPlatformComposer:(_Bool)arg12 supportMessengerEmoji:(_Bool)arg13 supportedInterfaceOrientations:(unsigned long long)arg14 supportMessengerCode:(_Bool)arg15;

@end

