//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBMemSearchCombinedResultsEdge.h>

@class NSArray, NSDictionary, NSString;

@interface FBMemSearchCombinedResultsEdge (ClientModuleLogging)
@property(copy, nonatomic) NSArray *clientModuleLoggingOverrideResultEdges;
@property(copy, nonatomic) NSString *clientVPVLoggingIdentifier;
@property(copy, nonatomic) NSDictionary *clientModuleLoggingExtras;
@end

