//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FBMobileConfigQEUniverseViewControllerDelegate <NSObject>
- (basic_string_a490aa4c)getExperimentNameString:(const basic_string_a490aa4c *)arg1 universe:(struct FBMobileConfigQEUniverseInfo *)arg2;
- (struct FBMobileConfigQEParamInfo)getProbableParamFromExperiment:(const struct FBMobileConfigQEExperimentInfo *)arg1;
- (void)selectExperiment:(const struct FBMobileConfigQEExperimentInfo *)arg1 universe:(struct FBMobileConfigQEUniverseInfo *)arg2 config:(basic_string_a490aa4c)arg3 isSessionless:(_Bool)arg4;
@end

