//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBConsistentLookasideCacheObservationHandle, FBNativeTemplateContext, JSContext, NSString;
@protocol NTAction;

@interface FBNativeTemplateGraphQLConsistencyActionManager : NSObject
{
    FBConsistentLookasideCacheObservationHandle *_handle;
    FBNativeTemplateContext *_context;
    NSString *_jsString;
    JSContext *_jsContext;
    id <NTAction> _action;
}

- (void).cxx_destruct;
- (void)loadMemModelExporterIfNeeded;
- (void)objectUpdated:(id)arg1;
- (void)addSubscriptionForAction:(id)arg1;

@end

