//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

@class FBUserSession, NSArray;

@interface FBNativeTemplateCacheDebugViewController : UITableViewController
{
    FBUserSession *_session;
    NSArray *_cachedPaths;
}

- (void).cxx_destruct;
- (void)_configureEmptyPathsCell:(id)arg1;
- (void)_configurePathCell:(id)arg1 forRow:(unsigned long long)arg2;
- (void)_configureClearCacheCell:(id)arg1;
- (void)_configureNextUpdateCell:(id)arg1;
- (id)tableView:(id)arg1 titleForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (void)viewDidLoad;
- (id)initWithSession:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;

@end

