//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NTTemplate-Protocol.h"

@class NSString;

@interface FBNativeTemplateMapPinData : NSObject <NTTemplate>
{
    NSString *_pinID;
    NSString *_category;
    double _anchorX;
    double _anchorY;
    double _latitude;
    double _longitude;
}

+ (id)newWithModel:(id)arg1 context:(id)arg2;
@property(readonly, nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(readonly, nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(readonly, nonatomic) double anchorY; // @synthesize anchorY=_anchorY;
@property(readonly, nonatomic) double anchorX; // @synthesize anchorX=_anchorX;
@property(readonly, copy, nonatomic) NSString *category; // @synthesize category=_category;
@property(readonly, copy, nonatomic) NSString *pinID; // @synthesize pinID=_pinID;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

