//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBMemImage, FBMemNotifActionState, FBMemRichNotification, FBMemTextWithEntities, NSArray, NSDate, NSNumber, NSString;
@protocol FBNotificationDataModelBuilder, FBNotificationOptionSetsConnectionDataModel;

@protocol FBNotificationDataModel <NSObject>
+ (id <FBNotificationDataModelBuilder>)builder;
- (id <FBNotificationOptionSetsConnectionDataModel>)previousNotifOptionSets;
- (id <FBNotificationOptionSetsConnectionDataModel>)notifOptionSets;
- (NSString *)notificationTrackingData;
- (FBMemImage *)notificationProfilePicture74;
- (NSDate *)notificationSentTime;
- (NSString *)notificationSeenState;
- (FBMemTextWithEntities *)notificationTitle;
- (FBMemImage *)notificationAppIcon;
- (NSString *)notificationCacheID;
- (NSString *)notificationGraphQLID;
- (double)notifPrefetchPriorityValue;
- (NSNumber *)notifPrefetchPriority;
- (NSArray *)sortKeys;
- (NSArray *)eligibleBuckets;
- (FBMemRichNotification *)richNotification;
- (_Bool)showBeeperValue;
- (NSNumber *)showBeeper;
- (FBMemNotifActionState *)actionState;
- (NSString *)selectedNotifOptionRowHash;
- (NSString *)profileImageOverride;
- (NSArray *)previousNotifOptionRows;
- (_Bool)notifPendingRemovalValue;
- (NSNumber *)notifPendingRemoval;
- (NSArray *)notifOptionRows;
- (NSDate *)localFirstReadTime;
- (NSDate *)localFirstSeenTime;
- (NSDate *)localFirstMarkedAsSeenTime;
- (_Bool)localRichAttachmentExpandedValue;
- (NSNumber *)localRichAttachmentExpanded;
- (_Bool)badgeDisabledValue;
- (NSNumber *)badgeDisabled;
- (id <FBNotificationDataModelBuilder>)copyBuilder;
@end

