//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBObjectiveCGraphElement, NSHashTable;
@protocol FBObjectiveCGraphNodeDelegate;

@interface FBObjectiveCGraphNode : NSObject
{
    id <FBObjectiveCGraphNodeDelegate> _delegate;
    FBObjectiveCGraphElement *_graphElement;
    NSHashTable *_outgoingReferences;
    NSHashTable *_incomingReferences;
}

- (void).cxx_destruct;
- (id)allRetainedObjects;
- (id)graphElement;
- (id)incomingReferences;
- (id)outgoingReferences;
- (void)addIncomingReference:(id)arg1;
- (void)buildReferencesWithObjects:(id)arg1;
- (id)initWithGraphElement:(id)arg1 delegate:(id)arg2;

@end

