//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBOfflineSearchFeedEdgesGenerator, FBSearchResultsLogEventListenerAnnouncer, NSString;

@interface FBOfflineSearchResultGenerator : NSObject
{
    FBOfflineSearchFeedEdgesGenerator *_feedEdgesGenerator;
    NSString *_clientSessionID;
    FBSearchResultsLogEventListenerAnnouncer *_logAnnouncer;
    _Bool _matchActorsOnly;
}

- (void).cxx_destruct;
- (id)resultsForQuery:(id)arg1;
- (id)initWithFeedEdgesGenerator:(id)arg1 clientSessionID:(id)arg2 logAnnouncer:(id)arg3 matchActorsOnly:(_Bool)arg4;

@end

