//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "FBPersonTimelineConfigurableWithPerson-Protocol.h"

@class FBContextualTimelineHeaderConfiguration, FBTimelineActivityLogButton, FBTimelineFriendButton, FBTimelineManageButton, FBTimelineMoreButton, FBTimelineSubscribeButton, FBTimelineUpdateInfoButton, FBUserSession, NSArray, NSMutableArray, NSString, UIButton, UIImage, UIImageView;

@interface FBPersonTimelineActionsView : UIView <FBPersonTimelineConfigurableWithPerson>
{
    FBTimelineSubscribeButton *_subscribeButton;
    FBTimelineFriendButton *_friendButton;
    FBTimelineManageButton *_manageButton;
    FBTimelineActivityLogButton *_activityLogButton;
    FBTimelineUpdateInfoButton *_updateInfoButton;
    FBTimelineMoreButton *_secondaryActionsButton;
    FBUserSession *_session;
    FBContextualTimelineHeaderConfiguration *_configuration;
    unsigned long long _numberOfButtons;
    UIImageView *_card;
    UIImageView *_friendCard;
    struct UIEdgeInsets _cardInsets;
    UIImage *_separatorImage;
    NSMutableArray *_separators;
    double _actionButtonHeight;
    NSArray *_actions;
}

@property(copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
- (void).cxx_destruct;
- (id)_newSeparatorView;
- (id)_actionButtonFromType:(int)arg1 person:(id)arg2;
- (void)_addSeparatorImagesFromCount:(long long)arg1;
- (void)_resetTimelineButtons;
- (void)_updateActionsWithPerson:(id)arg1;
- (double)widthOfLowerButtons:(struct CGSize)arg1;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (double)desiredHeight;
- (void)configureWithPerson:(id)arg1;
@property(readonly, nonatomic) UIButton *manageActionButton;
- (id)initWithSession:(id)arg1 configuration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

