//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBPlatformAction, NSDictionary;
@protocol FBPlatformBridgeAPIDelegate;

@interface FBPlatformBridgeAPI : NSObject
{
    FBPlatformAction *_action;
    id <FBPlatformBridgeAPIDelegate> _delegate;
    NSDictionary *_parameters;
}

+ (id)javaScriptImplementation;
+ (id)javaScriptFunctionName;
@property(readonly, copy, nonatomic) NSDictionary *parameters; // @synthesize parameters=_parameters;
@property(nonatomic) __weak id <FBPlatformBridgeAPIDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, nonatomic) FBPlatformAction *action; // @synthesize action=_action;
- (void).cxx_destruct;
- (void)invokeFromViewController:(id)arg1;
- (id)initWithAction:(id)arg1 parameters:(id)arg2;
- (_Bool)requireParameterWithName:(id)arg1 value:(id *)arg2;
- (_Bool)getURLParameter:(id)arg1 required:(_Bool)arg2 value:(id *)arg3;
- (_Bool)getStringParameter:(id)arg1 required:(_Bool)arg2 value:(id *)arg3;
- (_Bool)getDictionaryParameter:(id)arg1 required:(_Bool)arg2 value:(id *)arg3;
- (_Bool)getArrayParameter:(id)arg1 required:(_Bool)arg2 value:(id *)arg3;
- (void)failWithErrorMessage:(id)arg1;
- (void)completeWithData:(id)arg1;

@end

