//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBProfileCurationTagsActionBar, FBProfileCurationTagsActionBarListenerAnnouncer, FBProfileCurationTagsEditTracker, FBProfileCurationTagsTapListenerAnnouncer, FBProfileCurationTagsUpdateListenerAnnouncer, FBUserSession;

@interface FBProfileCurationTagsToolbox : NSObject
{
    FBUserSession *_session;
    FBProfileCurationTagsUpdateListenerAnnouncer *_curationTagsStatusListenerAnnouncer;
    FBProfileCurationTagsEditTracker *_tagsEditTracker;
    FBProfileCurationTagsActionBarListenerAnnouncer *_curationTagsActionBarListenerAnnouncer;
    FBProfileCurationTagsActionBar *_curationTagsActioBar;
    FBProfileCurationTagsTapListenerAnnouncer *_tapListenerAnnouncer;
}

@property(readonly, nonatomic) FBProfileCurationTagsTapListenerAnnouncer *tapListenerAnnouncer; // @synthesize tapListenerAnnouncer=_tapListenerAnnouncer;
@property(readonly, nonatomic) __weak FBProfileCurationTagsActionBar *curationTagsActioBar; // @synthesize curationTagsActioBar=_curationTagsActioBar;
@property(readonly, nonatomic) FBProfileCurationTagsActionBarListenerAnnouncer *curationTagsActionBarListenerAnnouncer; // @synthesize curationTagsActionBarListenerAnnouncer=_curationTagsActionBarListenerAnnouncer;
@property(readonly, nonatomic) FBProfileCurationTagsEditTracker *tagsEditTracker; // @synthesize tagsEditTracker=_tagsEditTracker;
@property(readonly, nonatomic) FBProfileCurationTagsUpdateListenerAnnouncer *curationTagsStatusListenerAnnouncer; // @synthesize curationTagsStatusListenerAnnouncer=_curationTagsStatusListenerAnnouncer;
@property(readonly, nonatomic) FBUserSession *session; // @synthesize session=_session;
- (void).cxx_destruct;
- (id)initWithSession:(id)arg1 curationTagsStatusListenerAnnouncer:(id)arg2 tagsEditTracker:(id)arg3 curationTagsActionBarListenerAnnouncer:(id)arg4 curationTagsActioBar:(id)arg5 tapListenerAnnouncer:(id)arg6;

@end

