//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface FBProfileWizardStatusUpdateContentView : UIView
{
    UIView *_composerView;
    UIView *_topInsetView;
    UIView *_bottomInsetView;
    UIView *_leftInsetView;
    UIView *_rightInsetView;
    UIView *_composerTopLineView;
    UIView *_composerBottomLineView;
}

- (void).cxx_destruct;
- (id)_createLineView;
- (void)_addLineViews;
- (id)_createInsetView;
- (void)_addInsetViews;
- (void)layoutSubviews;
- (id)initWithComposerView:(id)arg1;

@end

