//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@interface FBProfileIntroCardOtherAccountsContentComponent : CKCompositeComponent
{
}

+ (id)newWithLinks:(FragmentVector_6c04686d)arg1 insets:(struct UIEdgeInsets)arg2 shouldShowEditButton:(_Bool)arg3 editButtonAction:(CKTypedComponentAction_4b39899e)arg4 toolbox:(id)arg5;

@end

