//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBAnnouncerBase.h>

#import "FBProfileSetsNuxEventListener-Protocol.h"

@class NSString;

@interface FBProfileSetsNuxEventListenerAnnouncer : FBAnnouncerBase <FBProfileSetsNuxEventListener>
{
}

- (void)nuxDidExitViewportWithDuration:(double)arg1;
- (void)didDownloadSets:(id)arg1;
- (void)didTapCreateSetButton;
- (void)didDismissSetsNux:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

