//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/FBCompositeSectionComponent.h>

@class FBMemProfileDiscoverySection, FBProfileDiscoveryListToolbox;

@interface FBProfileDiscoverySegmentSectionComponent : FBCompositeSectionComponent
{
    FBMemProfileDiscoverySection *_section;
    FBProfileDiscoveryListToolbox *_toolbox;
}

+ (id)newWithSection:(id)arg1 viewerProfilePictureURL:(id)arg2 sectionIndex:(unsigned long long)arg3 isPivotCard:(_Bool)arg4 toolbox:(id)arg5;
- (void).cxx_destruct;

@end

