//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@protocol FBProfileActionBarSecondaryItemTapActions <NSObject>
- (void)didTapSendMoneyButton:(id)arg1;
- (void)didTapViewInsightsButton:(id)arg1;
- (void)didTapAddToGroupsButton:(id)arg1;
- (void)didTapSeeFriendshipButton:(id)arg1;
- (void)didTapTextButton:(id)arg1;
- (void)didTapPokeButton:(id)arg1;
- (void)didTapReportButton:(id)arg1;
- (void)didTapViewPrivacyShortcutsButton:(id)arg1;
- (void)didTapChangeCoverPhotoButton:(id)arg1;
- (void)didTapChangeProfilePictureButton:(id)arg1;
- (void)didTapViewMTouchProfileButton:(id)arg1;
- (void)didTapBlockButton:(id)arg1;
- (void)didTapWritePostButton:(id)arg1;
@end

