//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBPushHandler-Protocol.h"

@class FBCoveringSplitViewController, FBCustomNavigationController, FBUserSession, NSString;
@protocol FBIntentHandler, FBNavigationController_DEPRECATED;

@interface FBPushHandler : NSObject <FBPushHandler>
{
    FBUserSession *_session;
    FBCustomNavigationController<FBNavigationController_DEPRECATED> *_navigationController;
    FBCoveringSplitViewController *_coveringSplitViewController;
    id <FBIntentHandler> _intentHandler;
}

- (void).cxx_destruct;
- (void)_handleAPNSPayLoad:(id)arg1 withPushActionHandlerURL:(id)arg2 objectType:(unsigned short)arg3;
- (id)_getPushActionHandlerURLFromAPNSPayload:(id)arg1 pushType:(unsigned long long)arg2 objectType:(unsigned short)arg3;
- (void)_openFullscreenLiveVideoStoryGraphQLID:(id)arg1 analytics:(id)arg2 dismissalMenuItemIdentifier:(id)arg3;
- (_Bool)_isLiveVideoOrScheduledLiveVideoNotification:(unsigned short)arg1;
- (void)_openFriendCenterForRequest;
- (void)_switchToFriendTab;
- (void)_switchToMessenger:(id)arg1 launchedByUser:(_Bool)arg2;
- (void)handleAPNSWithPayLoad:(id)arg1 launchedByUser:(_Bool)arg2 actionIdentifier:(id)arg3;
- (void)handleAPNSWithPayLoad:(id)arg1 launchedByUser:(_Bool)arg2;
- (void)handleLocalNotificationWithPayload:(id)arg1 launchedByUser:(_Bool)arg2;
- (void)_openBookmark:(id)arg1;
- (id)initWithNavigationController:(id)arg1 coveringSplitViewController:(id)arg2 intentHandler:(id)arg3 session:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

