//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FBMemModelObject, FBReactionContext, NSIndexPath, NSString;
@protocol FBQueriedReactionUnitComponentFieldsProtocol, FBQueriedReactionUnitFieldsProtocol;

@protocol FBReactionBrickComponent
+ (id)newWithReactionContext:(FBReactionContext *)arg1 resultStyle:(NSString *)arg2 reactionUnit:(FBMemModelObject<FBQueriedReactionUnitFieldsProtocol> *)arg3 reactionUnitComponent:(FBMemModelObject<FBQueriedReactionUnitComponentFieldsProtocol> *)arg4 position:(unsigned long long)arg5 indexPath:(NSIndexPath *)arg6;
+ (id)new;
- (id)init;
@end

