//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol FBReactionRequestSupportedStylesProtocol <NSObject>
@property(readonly, copy, nonatomic) NSString *persistIDForUnitStyles;
@property(readonly, copy, nonatomic) NSString *persistIDForHeaderStyles;
@property(readonly, copy, nonatomic) NSString *persistIDForUnitComponentStyles;
@property(readonly, copy, nonatomic) NSString *persistIDForAttachmentStyles;
@property(readonly, copy, nonatomic) NSString *persistIDForActionStyles;
@property(readonly, copy, nonatomic) NSArray *supportedUnitStyles;
@property(readonly, copy, nonatomic) NSArray *supportedHeaderStyles;
@property(readonly, copy, nonatomic) NSArray *supportedUnitComponentStyles;
@property(readonly, copy, nonatomic) NSArray *supportedAttachmentsStyles;
@property(readonly, copy, nonatomic) NSArray *supportedActionStyles;
- (id)copy;
@end

