//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBSearchGeneralDataProviderDelegate-Protocol.h"

@class FBSearchGeneralDataProvider, FBSearchResultsAnnouncers, FBSerpConfig, FBUserSession, NSArray, NSMutableDictionary, NSString;
@protocol FBSearchPhotoStreamResultsDataBridgeDelegate;

@interface FBSearchPhotoStreamResultsDataBridge : NSObject <FBSearchGeneralDataProviderDelegate>
{
    FBUserSession *_session;
    FBSerpConfig *_serpConfig;
    FBSearchResultsAnnouncers *_announcers;
    NSObject *_scenePath;
    unsigned long long _numberOfItemsReceived;
    FBSearchGeneralDataProvider *_dataProvider;
    NSMutableDictionary *_modelsCache;
    NSArray *_incompleteModelsCacheKeys;
    _Bool _initialLoadStarted;
    id <FBSearchPhotoStreamResultsDataBridgeDelegate> _delegate;
}

@property(nonatomic) __weak id <FBSearchPhotoStreamResultsDataBridgeDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)hasAppliedFilters;
- (void)didReceiveInitalContentWithAppliedFilters:(id)arg1 isOfflineContent:(_Bool)arg2;
- (unsigned long long)enqueueChangeset:(const struct Changeset *)arg1 userInfo:(id)arg2;
- (void)_releaseIncompleteModels;
- (void)didUpdateFromState:(long long)arg1 toState:(long long)arg2 error:(id)arg3;
- (void)dealloc;
- (id)edgesToLog;
- (id)postSearchIntentLog;
- (id)resultsSessionLoggingUnitId;
- (id)verticalToLog;
- (void)releaseCachedResults;
- (void)loadTail;
- (void)loadHeadIfEmpty;
- (_Bool)hasMoreData;
- (_Bool)searchResultsIsEmpty;
- (id)initWithSession:(id)arg1 serpConfig:(id)arg2 announcers:(id)arg3 scenePath:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

