//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKComponentController.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class FBSearchBreakingNewsArticlesPagerComponent, FBSearchBreakingNewsArticlesPagerView, FBSearchBreakingNewsArticlesPagerViewLayout, NSString, UICollectionView;
@protocol FBSearchBreakingNewsArticlesPagerComponentControllerDelegate;

@interface FBSearchBreakingNewsArticlesPagerComponentController : CKComponentController <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    FBSearchBreakingNewsArticlesPagerViewLayout *_layout;
    shared_ptr_6a94d7a4 _mountedChildren;
    _Bool _isMounted;
    _Bool _isScrolling;
    struct unordered_map<FBSearchBreakingNewsArticlesPagerViewCell *, FBSearchBreakingNewsArticlesPagerComponentMountInfo, FB::HashFunctor<NSObject *>, std::__1::equal_to<FBSearchBreakingNewsArticlesPagerViewCell *>, std::__1::allocator<std::__1::pair<FBSearchBreakingNewsArticlesPagerViewCell *const, FBSearchBreakingNewsArticlesPagerComponentMountInfo>>> _cellToMountInfo;
    struct unordered_map<id, FBSearchBreakingNewsArticlesPagerViewCell *, FB::HashFunctor<NSObject *>, std::__1::equal_to<id>, std::__1::allocator<std::__1::pair<const id, FBSearchBreakingNewsArticlesPagerViewCell *>>> _scopeFrameTokenToCell;
    struct FBSearchBreakingNewsArticlesPagerComponentOffsetState _offsetState;
    id <FBSearchBreakingNewsArticlesPagerComponentControllerDelegate> _delegate;
}

@property(nonatomic) __weak id <FBSearchBreakingNewsArticlesPagerComponentControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)scopeFrameTokenOfLeftmostVisibleComponent;
- (void)restoreOffset;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (void)saveOffset;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)setTransformForCell:(id)arg1 collectionView:(id)arg2;
- (void)mountLayoutAtIndex:(unsigned long long)arg1 onCell:(id)arg2;
- (void)updateChildMountState;
- (void)componentWillRelinquishView;
- (void)didUpdateComponent;
- (void)willUpdateComponent;
- (void)willRemount;
- (void)didRemount;
- (void)willUnmount;
- (void)didMount;
- (void)componentDidAcquireView;
@property(readonly, nonatomic) FBSearchBreakingNewsArticlesPagerView *pagerView;
@property(readonly, nonatomic) UICollectionView *collectionView;
@property(readonly, nonatomic) FBSearchBreakingNewsArticlesPagerComponent *pagerComponent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

