//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@class NSArray;

@interface FBSearchAnimatingExpandingSectionComponent : CKCompositeComponent
{
    NSArray *_children;
    NSArray *_models;
}

+ (id)newWithChildren:(vector_85e08721)arg1;
@property(readonly, copy, nonatomic) NSArray *models; // @synthesize models=_models;
@property(readonly, copy, nonatomic) NSArray *children; // @synthesize children=_children;
- (void).cxx_destruct;
- (vector_035bbd4a)animationsFromPreviousComponent:(id)arg1;

@end

