//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSearchResultsContext, NSDictionary, NSString;
@protocol NSObject;

@protocol FBSearchVPVLoggingParserProtocol <NSObject>
+ (id)new;
+ (CDUnknownFunctionPointerType)identifierFactory;
+ (NSString *)nodeIdentifierToLogForModel:(id <NSObject>)arg1;
- (NSDictionary *)extrasToLogForModel:(id <NSObject>)arg1 index:(long long)arg2 context:(FBSearchResultsContext *)arg3;
@end

