//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class FBQuickButton;
@protocol FBSearchResultsModalNavigationBarDelegate;

@interface FBSearchResultsModalNavigationBar : UIControl
{
    FBQuickButton *_backButton;
    id <FBSearchResultsModalNavigationBarDelegate> _delegate;
}

@property(nonatomic) __weak id <FBSearchResultsModalNavigationBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_handleTapOnBackButton:(id)arg1;
- (void)_createBackButtonWithGlyph:(unsigned long long)arg1;
- (void)_createGradientBackground;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 backButtonGlyph:(unsigned long long)arg2;

@end

