//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class FBSettingsSchemaItemMultiValue, NSString;
@protocol FBSettingsViewControllerDelegate;

@interface FBSettingsMultiValueTableViewController : UITableViewController <UITableViewDataSource, UITableViewDelegate>
{
    id <FBSettingsViewControllerDelegate> _delegate;
    FBSettingsSchemaItemMultiValue *_schemaItem;
}

@property(retain, nonatomic) FBSettingsSchemaItemMultiValue *schemaItem; // @synthesize schemaItem=_schemaItem;
@property(nonatomic) id <FBSettingsViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)preferredInterfaceOrientationForPresentation;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)fb_showAuxiliaryViewController;
- (id)initWithTitle:(id)arg1 data:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

