//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@class FBSearchResultsContext;

@interface FBSearchResultsDebateSentimentReactionModuleComponent : CKCompositeComponent
{
    CKTypedComponentAction_4b39899e _voteAction;
    FBSearchResultsContext *_context;
}

+ (id)newWithContext:(id)arg1 reaction:(id)arg2 action:(CKTypedComponentAction_4b39899e)arg3 maxVotes:(id)arg4 highlighted:(_Bool)arg5;
@property(retain, nonatomic) FBSearchResultsContext *context; // @synthesize context=_context;
- (id).cxx_construct;
- (void).cxx_destruct;

@end

