//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBStorylineVideoDataBundle, UIView;
@protocol FBStorylinePlayerControllerManagerDelegate;

@protocol FBStorylinePlayerControllerManager <NSObject>
@property(nonatomic) __weak id <FBStorylinePlayerControllerManagerDelegate> delegate;
- (_Bool)isExporting;
- (void)pauseForEntrypoint:(unsigned long long)arg1;
- (void)pauseAnimationForEntrypoint:(unsigned long long)arg1;
- (UIView *)viewForEntrypoint:(unsigned long long)arg1;
- (void)cancelExportingForEntryPoint:(unsigned long long)arg1;
- (void)startExportingForEntryPoint:(unsigned long long)arg1;
- (void)playWithVideoBundle:(FBStorylineVideoDataBundle *)arg1 forEntryPoint:(unsigned long long)arg2;
- (void)startWithVideoBundle:(FBStorylineVideoDataBundle *)arg1 forEntryPoint:(unsigned long long)arg2;
- (_Bool)hasPlayerControllerForEntryPoint:(unsigned long long)arg1;
- (void)tearDownPlayerControllerForEntryPoint:(unsigned long long)arg1;
- (void)createNewPlayerControllerWithEntryPoint:(unsigned long long)arg1;
@end

