//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol FBGraphQLService, FBServiceTransactionMutating;

@interface FBStoryGallerySurveyStoriesFetcher : NSObject
{
    id <FBGraphQLService> _graphQLService;
    id <FBServiceTransactionMutating> _requestToken;
}

- (void).cxx_destruct;
- (void)_configureGraphQLServiceConfig:(id)arg1;
- (void)fetchStoryGallerySurveyStories:(CDUnknownBlockType)arg1 failureBlock:(CDUnknownBlockType)arg2;
- (id)initWithGraphQLService:(id)arg1;

@end

