//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBStarRatingsTriggering-Protocol.h"

@class FBStarRatingsUserData, NSString, NSTimer;
@protocol FBStarRatingsQuiesenceTriggerDelegateProtocol;

@interface FBStarRatingsDelayedTrigger : NSObject <FBStarRatingsTriggering>
{
    FBStarRatingsUserData *_userData;
    double _delay;
    NSTimer *_timer;
    id <FBStarRatingsQuiesenceTriggerDelegateProtocol> _delegate;
}

+ (id)triggerWithDelay:(double)arg1 userData:(id)arg2;
@property(nonatomic) __weak id <FBStarRatingsQuiesenceTriggerDelegateProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_timerDidFire:(id)arg1;
- (void)stopTrigger;
- (void)startTrigger;
- (id)initWithDelay:(double)arg1 userData:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

