//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBStarRatingsTriggering-Protocol.h"

@class FBStarRatingsUserData, NSArray, NSString;
@protocol FBStarRatingsQuiesenceTriggerDelegateProtocol;

@interface FBStarRatingsSmartTrigger : NSObject <FBStarRatingsTriggering>
{
    FBStarRatingsUserData *_userData;
    double _secondsUntilPrompt;
    unsigned long long _usesUntilPrompt;
    unsigned long long _significantEventsUntilPrompt;
    NSArray *_significantEventNotifications;
    id <FBStarRatingsQuiesenceTriggerDelegateProtocol> _delegate;
}

+ (void)incrementUsesWithUserData:(id)arg1;
+ (id)triggerWithUserData:(id)arg1 daysUntilPrompt:(unsigned long long)arg2 usesUntilPrompt:(unsigned long long)arg3 significantEventsUntilPrompt:(unsigned long long)arg4 significantEventNotifications:(id)arg5;
@property(nonatomic) __weak id <FBStarRatingsQuiesenceTriggerDelegateProtocol> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)navigationModeEventDidOccur;
- (void)_significantEventDidFire:(id)arg1;
- (void)_checkConditions;
- (void)stopTrigger;
- (void)startTrigger;
- (void)dealloc;
- (id)initWithUserData:(id)arg1 daysUntilPrompt:(unsigned long long)arg2 usesUntilPrompt:(unsigned long long)arg3 significantEventsUntilPrompt:(unsigned long long)arg4 significantEventNotifications:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

