//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDate, NSString, NSURL;

@interface FBUpdate : NSObject
{
    NSString *_name;
    NSString *_buildNumber;
    NSString *_bundleIdentifier;
    NSString *_releaseNotes;
    NSString *_version;
    NSURL *_itmsURL;
    NSURL *_downloadURL;
    NSString *_releaseTag;
    NSString *_releaseChannel;
    NSDate *_publicationDate;
    unsigned long long _archiveSize;
    unsigned long long _uncompressedArchiveSize;
    unsigned long long _type;
    unsigned long long _networkRequirements;
    unsigned long long _retryInterval;
}

+ (id)updateFromFQLQueryResult:(id)arg1;
+ (id)updateFromGraphQueryResult:(id)arg1;
+ (id)_updateFromQueryResult:(id)arg1 valuesToMap:(id)arg2 downloadUrlKey:(id)arg3;
+ (id)updateFromEndpointResponse:(id)arg1;
@property(nonatomic) unsigned long long retryInterval; // @synthesize retryInterval=_retryInterval;
@property(nonatomic) unsigned long long networkRequirements; // @synthesize networkRequirements=_networkRequirements;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(nonatomic) unsigned long long uncompressedArchiveSize; // @synthesize uncompressedArchiveSize=_uncompressedArchiveSize;
@property(nonatomic) unsigned long long archiveSize; // @synthesize archiveSize=_archiveSize;
@property(copy, nonatomic) NSDate *publicationDate; // @synthesize publicationDate=_publicationDate;
@property(copy, nonatomic) NSString *releaseChannel; // @synthesize releaseChannel=_releaseChannel;
@property(copy, nonatomic) NSString *releaseTag; // @synthesize releaseTag=_releaseTag;
@property(retain, nonatomic) NSURL *downloadURL; // @synthesize downloadURL=_downloadURL;
@property(retain, nonatomic) NSURL *itmsURL; // @synthesize itmsURL=_itmsURL;
@property(copy, nonatomic) NSString *version; // @synthesize version=_version;
@property(copy, nonatomic) NSString *releaseNotes; // @synthesize releaseNotes=_releaseNotes;
@property(copy, nonatomic) NSString *bundleIdentifier; // @synthesize bundleIdentifier=_bundleIdentifier;
@property(copy, nonatomic) NSString *buildNumber; // @synthesize buildNumber=_buildNumber;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;
- (_Bool)isSameBundleAsCurrentApp;
- (_Bool)isMoreRecentThanCurrentApp;
- (_Bool)isMoreRecentThan:(id)arg1;
- (_Bool)isMoreRecentThanBundle:(id)arg1;
- (_Bool)isSameBundleAs:(id)arg1;
- (_Bool)canDownloadOnNetwork:(unsigned long long)arg1;
- (unsigned long long)uniqueIdentifier;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDictionary:(id)arg1;
- (_Bool)isShellUpdate;
- (_Bool)_isVersionKind;
- (_Bool)_isAutoUpdaterKind;
- (_Bool)_isShellKind;
- (_Bool)_isCurrentAppUpdateKind;
- (unsigned long long)kind;

@end

