//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <FBSharedFramework/CKCompositeComponent.h>

@interface FBVideoHomeSecondaryActionComponent : CKCompositeComponent
{
}

+ (id)newWithFeedUnit:(id)arg1 insets:(struct UIEdgeInsets)arg2 color:(id)arg3 isNotification:(_Bool)arg4 feedToolbox:(id)arg5;

@end

