//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class FBUserSession, FBVideoHomeGuideBadgeUpdateListenerAnnouncer;
@protocol FBGraphQLSubscriptionHandle;

@interface FBVideoHomeGuideBadgeUpdateSubscriptionHandler : NSObject
{
    FBUserSession *_session;
    id <FBGraphQLSubscriptionHandle> _subscriptionHandle;
    FBVideoHomeGuideBadgeUpdateListenerAnnouncer *_announcer;
}

@property(readonly, nonatomic) FBVideoHomeGuideBadgeUpdateListenerAnnouncer *announcer; // @synthesize announcer=_announcer;
- (void).cxx_destruct;
- (void)_didReceiveUpdate:(id)arg1;
- (id)buildDebugInfo;
- (void)unsubscribe;
- (void)subscribe;
- (void)dealloc;
- (id)initWithSession:(id)arg1;

@end

