//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CKComponentHostingView, FBVideoHomeComposerHeaderComponentContext, FBVideoHomeComposerHeaderComponentModel;
@protocol FBVideoHomeComposerHeaderViewDelegate;

@interface FBVideoHomeComposerHeaderView : UIView
{
    CKComponentHostingView *_hostingView;
    FBVideoHomeComposerHeaderComponentModel *_model;
    FBVideoHomeComposerHeaderComponentContext *_context;
    id <FBVideoHomeComposerHeaderViewDelegate> _delegate;
}

@property(nonatomic) __weak id <FBVideoHomeComposerHeaderViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_goLiveTapped;
- (void)layoutSubviews;
- (void)setFriendsOnlineCount:(unsigned long long)arg1;
- (void)setUserName:(id)arg1;
- (id)initWithSession:(id)arg1;
- (id)init;

@end

