//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class FBWhistleExecutor, NSObject;
@protocol OS_dispatch_queue;

@protocol FBWhistleDispatcher
- (FBWhistleExecutor *)whistleExecutor;
- (NSObject<OS_dispatch_queue> *)queue;
- (void)dispatchFromWorkerToMainQueue:(void (^)(void))arg1;
- (void)dispatchFromEvbToWorkerQueue:(void (^)(void))arg1;
- (void)dispatchFromMainToWorkerQueue:(void (^)(void))arg1;
@end

