//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSData, NSError, NSNumber, NSString;

@protocol FBWhistleDelegate <NSObject>
- (void)onPingResponse;
- (void)onPingRequestSent;
- (void)onSubAckWithMessageId:(NSNumber *)arg1;
- (void)onPubAckWithMessageId:(NSNumber *)arg1;
- (void)onPublishFailedWithContext:(NSNumber *)arg1 error:(NSError *)arg2;
- (void)onPublishSentWithMessageId:(NSNumber *)arg1 context:(NSNumber *)arg2;
- (void)onPublishWithTopic:(NSString *)arg1 messageId:(NSNumber *)arg2 qos:(int)arg3 payload:(NSData *)arg4 receiveTime:(double)arg5;
- (void)onPingResponseTimeout;
- (void)onError:(NSError *)arg1;
- (void)onConnFailure:(NSNumber *)arg1;
- (void)onConnSuccess:(NSData *)arg1;
- (void)onConnectSent;
@end

