//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "FBClassProvidable-Protocol.h"

@class NSString;
@protocol FBClock;

@interface LastActiveManager : NSObject <FBClassProvidable>
{
    id <FBClock> _clock;
}

@property(retain, nonatomic) id <FBClock> clock; // @synthesize clock=_clock;
- (void).cxx_destruct;
- (double)secondsAgo:(long long)arg1;
- (id)initWithProviderMapData:(id)arg1;
- (double)timeIntervalSinceLastActive:(long long)arg1;
- (long long)DEPRECATED_combinedLastActiveTimeFromUserLastActiveTime:(long long)arg1 userId:(id)arg2 isOnline:(_Bool)arg3;
- (long long)DEPRECATED_lastActiveTimeForSyncPerson:(id)arg1;
- (id)initWithClock:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

