//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "RCTFBSessionModule-Protocol.h"

@class FBUserSession, NSMutableDictionary, NSString, RCTBridge;
@protocol OS_dispatch_queue;

@interface MQTTModule : NSObject <RCTFBSessionModule>
{
    NSMutableDictionary *_listenerForPattern;
    RCTBridge *_bridge;
    FBUserSession *_session;
}

+ (id)__rct_export__531;
+ (id)__rct_export__280;
+ (void)load;
+ (id)moduleName;
@property(nonatomic) __weak FBUserSession *session; // @synthesize session=_session;
@property(readonly, nonatomic) __weak RCTBridge *bridge; // @synthesize bridge=_bridge;
- (void).cxx_destruct;
- (void)unsubscribe:(id)arg1;
- (void)subscribe:(id)arg1 withEventName:(id)arg2;
@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *methodQueue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

