//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCTSGGroup.h"

@interface RCTSGCamera : RCTSGGroup
{
    _Bool _clearDepth;
    _Bool _clearColor;
    int _order;
    int _renderTarget;
    double _depthValue;
    struct RCTSGRect _viewPort;
    struct RCTSGRect _clipRect;
    struct RCTSGVec4 _colorValue;
    struct RCTSGMatrix _projectionMatrix;
}

@property(nonatomic) int renderTarget; // @synthesize renderTarget=_renderTarget;
@property(nonatomic) _Bool clearColor; // @synthesize clearColor=_clearColor;
@property(nonatomic) _Bool clearDepth; // @synthesize clearDepth=_clearDepth;
@property(nonatomic) int order; // @synthesize order=_order;
@property(nonatomic) double depthValue; // @synthesize depthValue=_depthValue;
@property(nonatomic) struct RCTSGVec4 colorValue; // @synthesize colorValue=_colorValue;
@property(nonatomic) struct RCTSGRect clipRect; // @synthesize clipRect=_clipRect;
@property(nonatomic) struct RCTSGRect viewPort; // @synthesize viewPort=_viewPort;
@property(nonatomic) struct RCTSGMatrix projectionMatrix; // @synthesize projectionMatrix=_projectionMatrix;
- (void)renderGather:(struct RCTSGRenderContext *)arg1 sgview:(id)arg2 matrixStack:(struct RCTSGMatrix *)arg3;
- (id)init;
- (void)updateProps:(id)arg1;

@end

