//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class DetailTableViewController, NSArray, UIBarButtonItem;

@protocol DetailTableViewControllerDelegate <NSObject>
- (void)showMailView:(DetailTableViewController *)arg1;
- (void)purgeMemoryViewController:(DetailTableViewController *)arg1;
- (void)showActivityMenuDetailTable:(DetailTableViewController *)arg1 shareItems:(NSArray *)arg2 sender:(UIBarButtonItem *)arg3;
- (void)TouchDetailDoneDetailTableView:(DetailTableViewController *)arg1 nowTableView:(int)arg2;
@end

