//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "UIScrollViewDelegate-Protocol.h"

@class XScrollView;

@protocol XScrollViewDelegate <UIScrollViewDelegate>
- (void)scrollViewDidEndDraggingAndEndDecelerating:(XScrollView *)arg1;
- (void)scrollViewWillBeginDecelerating:(XScrollView *)arg1;
- (void)scrollViewDidScroll:(XScrollView *)arg1;
- (void)xScrollViewDoubleTapped:(XScrollView *)arg1 tapPoint:(struct CGPoint)arg2;
@end

