//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NRMATimedTraceSegment.h"

@class NSArray, NSMutableArray;

@interface NRMAHarvestableActivity : NRMATimedTraceSegment
{
    NSMutableArray *_childSegments;
    unsigned long long _sendAttempts;
    NSArray *_lastActivityStamp;
}

@property(retain, nonatomic) NSArray *lastActivityStamp; // @synthesize lastActivityStamp=_lastActivityStamp;
@property(nonatomic) unsigned long long sendAttempts; // @synthesize sendAttempts=_sendAttempts;
@property(retain, nonatomic) NSMutableArray *childSegments; // @synthesize childSegments=_childSegments;
- (void).cxx_destruct;
- (id)JSONObject;
- (id)init;

@end

