//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UILabel, UIView;

@interface OptimizationButton : UIButton
{
    UILabel *_statusLabel;
    UILabel *_resultLabel;
    UIView *_labelContainerView;
}

+ (id)buttonWithType:(long long)arg1;
@property(retain, nonatomic) UIView *labelContainerView; // @synthesize labelContainerView=_labelContainerView;
@property(retain, nonatomic) UILabel *resultLabel; // @synthesize resultLabel=_resultLabel;
@property(retain, nonatomic) UILabel *statusLabel; // @synthesize statusLabel=_statusLabel;
- (void).cxx_destruct;
- (void)scaleToDefault;
- (void)scaleAnimation;
- (void)scaleToSmall;
- (id)resultLabelAnimationTo:(double)arg1;
- (id)scalAniamtion:(double)arg1;
- (id)optimizationResultStringWithString:(id)arg1;
- (id)checkResultString;
- (void)showCheckResultUI;
- (void)showCheckingUI;
- (void)optimizationComplete:(id)arg1;
- (void)startOptimization;
- (void)setupView;

@end

