//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AppLaunchView;

@interface SplashAdManager : NSObject
{
    _Bool _isDidFinishLaunching;
    _Bool _isLoadingConfig;
    _Bool _isAdViewShowing;
    _Bool _isApplicationOpenURL;
    _Bool _isShowing;
    _Bool _isActiveFromNotification;
    _Bool _isPlacehoderViewShowing;
    double _fetchConfigStartTime;
    double _fetchConfigEndTime;
    AppLaunchView *_adPlacehoderView;
    long long _applicationState;
}

+ (void)pushWebViewControllerWithUrl:(id)arg1 currentModel:(long long)arg2;
+ (void)sendHideNotification;
+ (void)start;
+ (id)shareInstance;
@property(nonatomic) _Bool isPlacehoderViewShowing; // @synthesize isPlacehoderViewShowing=_isPlacehoderViewShowing;
@property(nonatomic) _Bool isActiveFromNotification; // @synthesize isActiveFromNotification=_isActiveFromNotification;
@property(nonatomic) long long applicationState; // @synthesize applicationState=_applicationState;
@property(retain, nonatomic) AppLaunchView *adPlacehoderView; // @synthesize adPlacehoderView=_adPlacehoderView;
@property(nonatomic) double fetchConfigEndTime; // @synthesize fetchConfigEndTime=_fetchConfigEndTime;
@property(nonatomic) double fetchConfigStartTime; // @synthesize fetchConfigStartTime=_fetchConfigStartTime;
@property(nonatomic) _Bool isShowing; // @synthesize isShowing=_isShowing;
@property(nonatomic) _Bool isApplicationOpenURL; // @synthesize isApplicationOpenURL=_isApplicationOpenURL;
@property(nonatomic) _Bool isAdViewShowing; // @synthesize isAdViewShowing=_isAdViewShowing;
- (void).cxx_destruct;
- (void)removeSplashAdCache;
- (id)splashAdViewConfigFromCache;
- (void)cacheSplashAdViewConfig:(id)arg1 trackImageDownload:(_Bool)arg2;
- (void)removePlacehoderView;
- (void)adCallBackWithURLWithURLS:(id)arg1;
- (void)showSplashAdViewWithSplashAd:(id)arg1 currentModel:(long long)arg2;
- (void)requestAdWithModel:(long long)arg1;
- (void)showSplashViewWithModel:(long long)arg1;
- (void)checkSplashadWithModel:(long long)arg1;
- (void)appBecomeActive;
- (void)appFinishLaunching:(id)arg1;
- (void)enableActiveFromNotification;
- (void)didReceiveLocalNotification;
- (void)didReceiveRemoteNotification;
- (id)init;

@end

