//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WKAppConfigBase.h"

@class NSDictionary;

@interface WKAppConfigSniffer : WKAppConfigBase
{
    NSDictionary *_list;
}

@property(retain, nonatomic) NSDictionary *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (void)configData:(id)arg1;
- (id)feature;

@end

