//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSString;

@interface WKFeedBadgeButton : UIButton
{
    unsigned long long _badgeCount;
    NSString *_badgeValue;
}

+ (id)buttonWithBadgeValue:(unsigned long long)arg1;
@property(retain, nonatomic) NSString *badgeValue; // @synthesize badgeValue=_badgeValue;
@property(nonatomic) unsigned long long badgeCount; // @synthesize badgeCount=_badgeCount;
- (void).cxx_destruct;
- (void)badgeCountChangeWithValueCount:(unsigned long long)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

