//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface WKHomeListSortManager : NSObject
{
}

+ (id)sortWiFiListByDistance:(id)arg1;
+ (id)sortWiFiListByStrength:(id)arg1;
+ (id)convertDictionaryArrayToWiFiObjectArray:(id)arg1;
+ (id)sortCachedSystemWiFiList:(id)arg1;
+ (id)sortHomeListWithCachedLatestList:(id)arg1 cacheListNeedConvertToObject:(_Bool)arg2 nearbyWiFiList:(id)arg3;
+ (id)sortHomeListWithCachedLatestList:(id)arg1 nearbyWiFiList:(id)arg2;
+ (id)sortHomeListWithOCRList:(id)arg1 nearbyWiFiList:(id)arg2;

@end

