//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WKNotificationBase.h"

@interface WKLocalNotificationHelper : WKNotificationBase
{
}

+ (void)invokeLocalNofiticationWithTitle:(id)arg1 delay:(double)arg2 sound:(_Bool)arg3 userInfo:(id)arg4 requestIdentifier:(id)arg5 categoryIdentifier:(id)arg6;
+ (void)invokeLocalNofiticationWithTitle:(id)arg1 delay:(double)arg2 sound:(_Bool)arg3 userInfo:(id)arg4;
+ (void)invokeLocalNofitication:(id)arg1 delay:(double)arg2 sound:(_Bool)arg3 userInfo:(id)arg4 requestIdentifier:(id)arg5 categoryIdentifier:(id)arg6;
+ (void)invokeLocalNofitication:(id)arg1 delay:(double)arg2 sound:(_Bool)arg3 userInfo:(id)arg4 requestIdentifier:(id)arg5;
+ (void)invokeLocalNofitication:(id)arg1 delay:(double)arg2 sound:(_Bool)arg3 notificationType:(id)arg4;

@end

