//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel;

@interface WKSpeedResultRecommendCell : UITableViewCell
{
    UILabel *_chatLabel;
    UILabel *_onlineLabel;
    UILabel *_gameLabel;
    UILabel *_videoLabel;
    UILabel *_noteLabel;
    UIImageView *_speedIndicator;
}

@property(retain, nonatomic) UIImageView *speedIndicator; // @synthesize speedIndicator=_speedIndicator;
@property(retain, nonatomic) UILabel *noteLabel; // @synthesize noteLabel=_noteLabel;
@property(retain, nonatomic) UILabel *videoLabel; // @synthesize videoLabel=_videoLabel;
@property(retain, nonatomic) UILabel *gameLabel; // @synthesize gameLabel=_gameLabel;
@property(retain, nonatomic) UILabel *onlineLabel; // @synthesize onlineLabel=_onlineLabel;
@property(retain, nonatomic) UILabel *chatLabel; // @synthesize chatLabel=_chatLabel;
- (void).cxx_destruct;
- (void)updateSpeedResult:(id)arg1;
- (id)getIndicatorImageNameWithSpeed:(double)arg1;
- (id)updateSpeedLabelWithSpeed:(double)arg1;
- (void)layoutAllSubviews;
- (void)setupSubViews;
- (id)getNormalLabelWithTitle:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

