//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel, _TtC7Lingome18HeadphoneTipButton;

@interface _TtC7Lingome16HeadphoneTipView : UIView
{
    // Error parsing type: , name: tipLabel
    // Error parsing type: , name: continueButton
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) __weak _TtC7Lingome18HeadphoneTipButton *continueButton; // @synthesize continueButton;
@property(nonatomic) __weak UILabel *tipLabel; // @synthesize tipLabel;

@end

