//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSDate, NSLayoutConstraint, UICollectionView, UIView, _TtC7Lingome32CheckInAchievementViewController;

@interface _TtC7Lingome29CheckInCalendarViewController : UIViewController
{
    // Error parsing type: , name: velocity
    // Error parsing type: , name: scrollDirection
    // Error parsing type: , name: lastContentOffset
    // Error parsing type: , name: summary
    // Error parsing type: , name: badges
    // Error parsing type: , name: event
    // Error parsing type: , name: page
    // Error parsing type: , name: records
    // Error parsing type: , name: preferredWidth
    // Error parsing type: , name: beginningOfMonth
    // Error parsing type: , name: beginningOfNextMonth
    // Error parsing type: , name: today
    // Error parsing type: , name: currentTipView
    // Error parsing type: , name: shareImage
    // Error parsing type: , name: normalContainer
    // Error parsing type: , name: withoutNetworkContainer
    // Error parsing type: , name: collectionView
    // Error parsing type: , name: topContainerView
    // Error parsing type: , name: topContainerHeightConstraint
    // Error parsing type: , name: achievementViewController
}

- (CDUnknownBlockType).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)showTopView;
- (void)setupCollectionview;
- (void)setupMonthData;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;
@property(nonatomic, retain) _TtC7Lingome32CheckInAchievementViewController *achievementViewController; // @synthesize achievementViewController;
@property(nonatomic) __weak NSLayoutConstraint *topContainerHeightConstraint; // @synthesize topContainerHeightConstraint;
@property(nonatomic) __weak UIView *topContainerView; // @synthesize topContainerView;
@property(nonatomic) __weak UICollectionView *collectionView; // @synthesize collectionView;
@property(nonatomic) __weak UIView *withoutNetworkContainer; // @synthesize withoutNetworkContainer;
@property(nonatomic) __weak UIView *normalContainer; // @synthesize normalContainer;
@property(nonatomic, readonly) NSDate *today; // @synthesize today;
@property(nonatomic) double preferredWidth; // @synthesize preferredWidth;
@property(nonatomic, readonly) double maxTopContainerHeight;
@property(nonatomic, readonly) double minTopContainerHeight;
@property(nonatomic) long long page; // @synthesize page;
@property(nonatomic) struct CGPoint lastContentOffset; // @synthesize lastContentOffset;
@property(nonatomic) double scrollDirection; // @synthesize scrollDirection;
@property(nonatomic) double velocity; // @synthesize velocity;

@end

