//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSBundle, NSDictionary;

@interface EMPromptManager : NSObject
{
    NSBundle *_sdkBundle;
    NSDictionary *_promptDic;
}

+ (id)shareManager;
+ (id)promptOfKey:(id)arg1;
- (void).cxx_destruct;
- (id)_promptOfKey:(id)arg1;
- (id)init;

@end

