//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class GSBroadcastManager, GSChatMessage, GSUserInfo;

@protocol GSBroadcastChatDelegate <NSObject>
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceiveChatModuleInitResult:(_Bool)arg2;

@optional
- (void)broadcastManager:(GSBroadcastManager *)arg1 didSetChattingEnabled:(_Bool)arg2;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceivePanelistMessage:(GSChatMessage *)arg2 fromUser:(GSUserInfo *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceivePublicMessage:(GSChatMessage *)arg2 fromUser:(GSUserInfo *)arg3;
- (void)broadcastManager:(GSBroadcastManager *)arg1 didReceivePrivateMessage:(GSChatMessage *)arg2 fromUser:(GSUserInfo *)arg3;
@end

