//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Aug  6 2017 21:40:27).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSUserDefaults.h>

@interface NSUserDefaults (UserConf)
- (void)removeConfWithLiulishuoID:(id)arg1;
- (void)removeCurrentUserConf;
- (void)setUserConfObject:(id)arg1 forKey:(id)arg2 withLiulishuoID:(id)arg3;
- (id)userConfForKey:(id)arg1 withLiulishuoID:(id)arg2;
- (void)removeUserConfObjectForKey:(id)arg1 withLiulishuoID:(id)arg2;
- (void)removeCurrentUserConfObjectForKey:(id)arg1;
- (void)setCurrentUserConfObject:(id)arg1 forKey:(id)arg2;
- (id)currentUserConfForKey:(id)arg1;
@end

