//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface GADAdType : NSObject
{
    BOOL _isRewardBasedVideoAd;
    BOOL _isInterstitial;
    struct GADAdSize _adSize;
}

+ (id)interstitialAdType;
+ (id)bannerAdTypeForSize:(struct GADAdSize)arg1;
@property(nonatomic) struct GADAdSize adSize; // @synthesize adSize=_adSize;
@property(readonly, nonatomic) BOOL isInterstitial; // @synthesize isInterstitial=_isInterstitial;
- (id)description;
- (BOOL)isValid;
- (BOOL)isRewardBasedVideoAd;
- (unsigned int)hash;
- (BOOL)isEqual:(id)arg1;
- (id)initForRewardBasedVideoAd;
- (id)initForInterstitial;
- (id)initWithAdSize:(struct GADAdSize)arg1;
- (id)init;

@end

