//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GADTransparentOverlayPresenter.h"

@class GADMRAIDResizeProperties, UIView;
@protocol GADMRAIDEventHandling;

@interface GADMRAIDResizeOverlayPresenter : GADTransparentOverlayPresenter
{
    BOOL _dismissToDefaultState;
    GADMRAIDResizeProperties *_resizeProperties;
    id <GADMRAIDEventHandling> _MRAIDEventHandler;
    UIView *_referenceView;
}

+ (struct CGRect)adjustedContentFrame:(struct CGRect)arg1 inBounds:(struct CGRect)arg2;
@property(retain, nonatomic) UIView *referenceView; // @synthesize referenceView=_referenceView;
@property(nonatomic) __weak id <GADMRAIDEventHandling> MRAIDEventHandler; // @synthesize MRAIDEventHandler=_MRAIDEventHandler;
@property(nonatomic) BOOL dismissToDefaultState; // @synthesize dismissToDefaultState=_dismissToDefaultState;
@property(retain, nonatomic) GADMRAIDResizeProperties *resizeProperties; // @synthesize resizeProperties=_resizeProperties;
- (void).cxx_destruct;
- (void)updateTransparentInterstitialOrientation;
- (void)composeTransparentInterstitialViewsForPresentation;
- (BOOL)isReadyToPresent;
- (void)repositionContentIfNeeded;
- (struct CGRect)contentFrame;
- (BOOL)resizePropertiesAreValid:(id)arg1 relativeToView:(id)arg2;
- (id)initWithReferenceView:(id)arg1;
- (id)init;

@end

