//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "GADActiveViewMonitorDelegate-Protocol.h"
#import "GADAdFetcherDelegate-Protocol.h"
#import "GADAdViewActiveViewMonitoring-Protocol.h"
#import "GADMRAIDEventHandling-Protocol.h"
#import "GADPercentDrivenUserInteractionAnimationControllerDelegate-Protocol.h"
#import "GADSDKCoreControllerDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class GADActiveViewMonitor, GADAd, GADAdFetcher, GADAdType, GADAdView, GADBannerAdViewDelegate, GADCorrelator, GADIntermission, GADInterstitial, GADMAdManager, GADMConfig, GADPercentDrivenUserInteractionAnimationController, GADRequest, GADSDKCoreWebView, GADScheduler, GADSlotStatistics, GADViewControllerFullScreenSwipeAnimation, NSDictionary, NSNumber, NSSet, NSString, NSTimer, SKStoreProductViewController, UIPanGestureRecognizer, UIView;
@protocol GADSlotAdEventDelegate, GADSlotAdKeyDelegate, GADSlotAdLoadDelegate, GADSlotAdResponseDelegate, GADSlotDelegate;

@interface GADSlot : NSObject <GADActiveViewMonitorDelegate, GADAdViewActiveViewMonitoring, GADPercentDrivenUserInteractionAnimationControllerDelegate, GADSDKCoreControllerDelegate, SKStoreProductViewControllerDelegate, GADMRAIDEventHandling, GADAdFetcherDelegate>
{
    int _state;
    unsigned int _activeViewID;
    int _swipeToViewControllerCheckerTaskID;
    GADMAdManager *_mediationManager;
    GADMConfig *_mediationConfiguration;
    BOOL _slotHasAttemptedAnAdRequestAtLeastOnce;
    BOOL _isListeningToDeviceOrientationChangeEvent;
    struct CGRect _usableInterfaceFrame;
    struct CGRect _creativeWebViewFrame;
    struct CGRect _creativeAdFrame;
    BOOL _viewHasMadeImpression;
    int _CSIIdentifier;
    NSString *_adResponseKey;
    NSString *_netWorkLatencyKey;
    NSString *_adRenderingKey;
    NSString *_totalTimeKey;
    BOOL _hasAutoRefreshed;
    BOOL _reloadable;
    BOOL _manualImpressionsEnabled;
    BOOL _calledLoadAndDisplayRequest;
    BOOL _swipeToViewControllerEnabled;
    BOOL _swipeToViewControllerAnimationControllerInitialized;
    BOOL _adCustomRendered;
    id <GADSlotDelegate> _slotDelegate;
    id <GADSlotAdLoadDelegate> _adLoadDelegate;
    id <GADSlotAdEventDelegate> _adEventDelegate;
    id <GADSlotAdResponseDelegate> _adResponseDelegate;
    id <GADSlotAdKeyDelegate> _adKeyDelegate;
    NSString *_adUnitID;
    GADAd *_ad;
    GADAdType *_adType;
    GADRequest *_request;
    GADCorrelator *_correlator;
    NSNumber *_timeLastLoaded;
    GADAdView *_adView;
    GADSlotStatistics *_slotStats;
    GADIntermission *_intermission;
    GADInterstitial *_interstitial;
    GADBannerAdViewDelegate *_adViewDelegate;
    GADAd *_loadingAd;
    GADAdFetcher *_adFetcher;
    NSDictionary *_applicationStatistics;
    NSSet *_pendingAdStatistics;
    NSTimer *_reloadTimer;
    NSString *_requestID;
    GADRequest *_nextRequest;
    GADActiveViewMonitor *_activeViewMonitor;
    GADSDKCoreWebView *_SDKCoreWebView;
    UIView *_activeViewMonitoredView;
    NSDictionary *_savedParamsForCheckingSwipeToViewController;
    GADPercentDrivenUserInteractionAnimationController *_animationController;
    GADViewControllerFullScreenSwipeAnimation *_animation;
    SKStoreProductViewController *_swipeableStoreProductViewController;
    UIPanGestureRecognizer *_swipeGestureRecognizer;
    GADSlot *_strongSlotForSwipeToViewController;
    GADScheduler *_swipeToViewControllerChecker;
    double _reloadInterval;
    struct CGSize _newAdSize;
}

+ (void)initialize;
@property(retain, nonatomic) GADScheduler *swipeToViewControllerChecker; // @synthesize swipeToViewControllerChecker=_swipeToViewControllerChecker;
@property(nonatomic, getter=isAdCustomRendered) BOOL adCustomRendered; // @synthesize adCustomRendered=_adCustomRendered;
@property(retain, nonatomic) GADSlot *strongSlotForSwipeToViewController; // @synthesize strongSlotForSwipeToViewController=_strongSlotForSwipeToViewController;
@property(retain, nonatomic) UIPanGestureRecognizer *swipeGestureRecognizer; // @synthesize swipeGestureRecognizer=_swipeGestureRecognizer;
@property(retain, nonatomic) SKStoreProductViewController *swipeableStoreProductViewController; // @synthesize swipeableStoreProductViewController=_swipeableStoreProductViewController;
@property(retain, nonatomic) GADViewControllerFullScreenSwipeAnimation *animation; // @synthesize animation=_animation;
@property(retain, nonatomic) GADPercentDrivenUserInteractionAnimationController *animationController; // @synthesize animationController=_animationController;
@property(nonatomic) BOOL swipeToViewControllerAnimationControllerInitialized; // @synthesize swipeToViewControllerAnimationControllerInitialized=_swipeToViewControllerAnimationControllerInitialized;
@property(nonatomic) BOOL swipeToViewControllerEnabled; // @synthesize swipeToViewControllerEnabled=_swipeToViewControllerEnabled;
@property(copy, nonatomic) NSDictionary *savedParamsForCheckingSwipeToViewController; // @synthesize savedParamsForCheckingSwipeToViewController=_savedParamsForCheckingSwipeToViewController;
@property(retain, nonatomic) UIView *activeViewMonitoredView; // @synthesize activeViewMonitoredView=_activeViewMonitoredView;
@property(retain, nonatomic) GADSDKCoreWebView *SDKCoreWebView; // @synthesize SDKCoreWebView=_SDKCoreWebView;
@property(retain, nonatomic) GADActiveViewMonitor *activeViewMonitor; // @synthesize activeViewMonitor=_activeViewMonitor;
@property(nonatomic) struct CGSize newAdSize; // @synthesize newAdSize=_newAdSize;
@property(copy, nonatomic) GADRequest *nextRequest; // @synthesize nextRequest=_nextRequest;
@property(copy, nonatomic) NSString *requestID; // @synthesize requestID=_requestID;
@property(nonatomic) double reloadInterval; // @synthesize reloadInterval=_reloadInterval;
@property(retain, nonatomic) NSTimer *reloadTimer; // @synthesize reloadTimer=_reloadTimer;
@property(copy, nonatomic) NSSet *pendingAdStatistics; // @synthesize pendingAdStatistics=_pendingAdStatistics;
@property(copy, nonatomic) NSDictionary *applicationStatistics; // @synthesize applicationStatistics=_applicationStatistics;
@property(retain, nonatomic) GADAdFetcher *adFetcher; // @synthesize adFetcher=_adFetcher;
@property(retain, nonatomic) GADAd *loadingAd; // @synthesize loadingAd=_loadingAd;
@property(retain, nonatomic) GADBannerAdViewDelegate *adViewDelegate; // @synthesize adViewDelegate=_adViewDelegate;
@property(nonatomic) __weak GADInterstitial *interstitial; // @synthesize interstitial=_interstitial;
@property(nonatomic) __weak GADIntermission *intermission; // @synthesize intermission=_intermission;
@property(nonatomic) BOOL calledLoadAndDisplayRequest; // @synthesize calledLoadAndDisplayRequest=_calledLoadAndDisplayRequest;
@property(retain, nonatomic) GADSlotStatistics *slotStats; // @synthesize slotStats=_slotStats;
@property(readonly, nonatomic) GADAdView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) NSNumber *timeLastLoaded; // @synthesize timeLastLoaded=_timeLastLoaded;
@property(retain, nonatomic) GADCorrelator *correlator; // @synthesize correlator=_correlator;
@property(copy, nonatomic) GADRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) GADAdType *adType; // @synthesize adType=_adType;
@property(retain, nonatomic) GADAd *ad; // @synthesize ad=_ad;
@property(nonatomic) BOOL manualImpressionsEnabled; // @synthesize manualImpressionsEnabled=_manualImpressionsEnabled;
@property(nonatomic) BOOL reloadable; // @synthesize reloadable=_reloadable;
@property(nonatomic) BOOL hasAutoRefreshed; // @synthesize hasAutoRefreshed=_hasAutoRefreshed;
@property(copy, nonatomic) NSString *adUnitID; // @synthesize adUnitID=_adUnitID;
@property(nonatomic) __weak id <GADSlotAdKeyDelegate> adKeyDelegate; // @synthesize adKeyDelegate=_adKeyDelegate;
@property(nonatomic) __weak id <GADSlotAdResponseDelegate> adResponseDelegate; // @synthesize adResponseDelegate=_adResponseDelegate;
@property(nonatomic) __weak id <GADSlotAdEventDelegate> adEventDelegate; // @synthesize adEventDelegate=_adEventDelegate;
@property(nonatomic) __weak id <GADSlotAdLoadDelegate> adLoadDelegate; // @synthesize adLoadDelegate=_adLoadDelegate;
@property(nonatomic) __weak id <GADSlotDelegate> slotDelegate; // @synthesize slotDelegate=_slotDelegate;
- (void).cxx_destruct;
- (void)adFetcher:(id)arg1 didFailToFetchAd:(id)arg2 withError:(id)arg3 responseCode:(unsigned int)arg4;
- (void)adFetcher:(id)arg1 didFetchAd:(id)arg2;
- (void)setViewForAdUsingView:(id)arg1;
- (BOOL)validateAdResponseWithAdSize:(struct GADAdSize)arg1 andValidAdSizes:(id)arg2;
- (void)processCustomRenderingAdResponse:(id)arg1;
- (BOOL)isMRAIDEnabled;
- (void)pingManualTrackingURLs;
- (void)pingImpressionURLs;
- (void)pingClickURLs;
- (void)processStandardAdResponse:(id)arg1;
- (void)finishedLoadingAdResponse:(id)arg1;
- (id)gestureClickURLWithURL:(id)arg1;
- (BOOL)isGoogleAdURL:(id)arg1;
- (void)cancelPendingAndFutureActions;
- (void)cancelPendingActions;
- (void)cancelLoad;
- (void)invalidate;
@property(readonly, copy) NSString *description;
- (void)dealloc;
- (id)init;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)loadAd:(id)arg1 headers:(id)arg2;
- (void)resetRequestState;
- (void)interstitialViewWillDisappear;
- (void)interstitialViewWillAppear;
- (void)bannerDidMoveToWindow:(id)arg1;
- (void)mediatedAdNetworkAutoRefreshed;
- (void)logRequestTestAdInstructions;
- (void)loadNextRequestWithAutoRefresh:(BOOL)arg1;
- (void)loadRequest:(id)arg1;
- (BOOL)shouldMakeRequest:(id)arg1;
- (BOOL)isMakingRequest;
- (void)adDidRelinquishFullScreen:(id)arg1;
- (void)adWillPresentFullScreen:(id)arg1;
- (void)appDidBecomeActive:(id)arg1;
- (void)appWillBecomeInactive:(id)arg1;
- (void)scheduleAdReloadTimer;
- (void)deactivateReloadTimer;
- (void)reloadCurrentRequest;
- (void)setAdType:(id)arg1 andReloadRequest:(BOOL)arg2;
- (BOOL)canEnableActiveViewMonitoring;
- (id)dictionaryForBounds:(struct CGRect)arg1;
- (id)adFormat;
- (id)activeViewParameters:(id)arg1 activeViewUnloaded:(BOOL)arg2;
- (id)activeViewJSCommandWithParams:(id)arg1;
- (void)activeViewMonitorDidRefresh:(id)arg1;
- (void)activeViewMonitorWillUnload;
- (void)finishActiveViewReporting;
- (void)startActiveViewReportingIfEnabled;
- (void)createActiveViewMonitor;
- (BOOL)monitoredViewIsSubviewOfDeviceScreen;
- (void)adViewDidStopActiveViewMonitoring;
- (void)adViewDidChangeActiveViewVisibility:(BOOL)arg1;
@property(nonatomic) BOOL viewHasMadeImpression;
- (void)didReceiveInAppPurchase:(id)arg1;
- (id)inAppPurchaseDelegate;
- (void)animationControllerDidCancelAnimationTransition:(id)arg1;
- (void)animationControllerDidFinishAnimationTransition:(id)arg1;
- (id)viewControllerForPresentingModalView;
- (BOOL)hasConsistentMediationConfigForAdType:(id)arg1;
- (void)requestAdWithType:(id)arg1 mediationConfig:(id)arg2;
- (void)processMediationAdResponse:(id)arg1;
- (void)presentMediatedInterstitialFromRootViewController:(id)arg1;
- (BOOL)isMediating;
- (BOOL)changeAdTypeTo:(id)arg1;
- (id)adNetworkClassName;
@property(readonly, nonatomic) int CSIIdentifier;
- (void)loadAdURLWithParameters:(id)arg1;
- (id)requestParameters;
- (void)invalidJavaScriptRequest;
- (void)failedJavaScriptFile;
- (int)requestedAdType;
- (id)multipleAdSizeParameterFromSizes:(id)arg1;
- (void)adWillLeaveApplication;
- (void)adDidDismissScreen;
- (void)adWillDismissScreen;
- (void)adWillPresentScreen;
- (void)adWasClicked;
- (void)adFinishedLoadingContent;
- (void)adFailedToReceiveContentWithError:(id)arg1;
- (void)willProcessAd;
- (void)processAdResponse:(id)arg1;
- (void)updateContentSize:(struct CGSize)arg1;
- (void)invalidateState;
- (void)resetState;
- (void)willLeaveAppDueToClick;
- (void)didMakeAdImpression;
- (void)didLoadAdHTMLInWebView;
- (void)willLoadAdHTMLInWebView;
- (void)willStartAdRendering;
- (void)didReceiveValidAd;
- (void)didReceiveInvalidAd;
- (void)didFailToReceiveAdWithError:(id)arg1 shouldCancelPendingActions:(BOOL)arg2;
- (void)willProcessMediationResponse;
- (void)didFetchAdContent;
- (void)willFetchAdContent;
- (void)didReceiveAdURL;
- (void)didFailToRetrieveSDKCoreWithError:(id)arg1;
- (void)willRequestAdURL;
- (void)setState:(int)arg1;
@property(readonly, nonatomic) int state;
- (void)loadAdNetworkJavaScriptRequest:(id)arg1;
- (void)productViewControllerDidFinish:(id)arg1;
- (BOOL)shouldProcessTouch:(struct CGPoint)arg1 inView:(id)arg2;
- (void)loadStoreProductViewController;
- (void)handlePanGesture:(id)arg1;
- (void)setUpAnimationController;
- (void)disableSwipeToViewController;
- (void)enableSwipeToViewController;
- (void)canEnableSwipeToViewController;
- (void)unscheduleSwipeToViewControllerChecker;
- (void)scheduleSwipeToViewControllerChecker;
- (void)didChangeDeviceOrientation;
- (void)addCreativeOrientationChangeObserver:(id)arg1 selector:(SEL)arg2;
- (void)endListeningToDeviceOrientationChangeEvent;
- (void)beginListeningToDeviceOrientationChangeEvent;
- (void)handleError:(id)arg1 action:(id)arg2;
- (void)updatePositionFromView:(id)arg1;
- (void)updateVisibility:(BOOL)arg1;
- (void)MRAIDAdDidUnload;
- (void)MRAIDAdDidLoad;
- (void)SDKDidBecomeReady;
- (void)notifyDeviceFeatures;
- (void)notifyOrientationToMRAIDCreative;
- (id)creativePositionDictionaryForActiveViewBounds:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned int hash;
@property(readonly) Class superclass;

@end

