//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSError.h>

@interface NSError (GADInternalErrorAdditions)
+ (id)gad_localizedDescriptionForErrorCode:(int)arg1;
+ (id)gad_errorWithCode:(int)arg1 description:(id)arg2;
+ (id)gad_errorWithDomain:(id)arg1 code:(int)arg2 description:(id)arg3;
@end

