//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface ALPPassDataModal : NSObject
{
    NSMutableArray *asyncCallers;
}

+ (id)sharedModal;
@property(retain, nonatomic) NSMutableArray *asyncCallers; // @synthesize asyncCallers;
- (void).cxx_destruct;
- (void)getPassdQRCode:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (_Bool)updateHandle:(id)arg1 goToMainList:(_Bool)arg2;
- (_Bool)updateHandle:(id)arg1;
- (void)exchange:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)deletePassListItem:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)deleteDiscountData:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)handleRPCFailure:(id)arg1 desc:(id)arg2 showToast:(_Bool)arg3 mainView:(id)arg4 duration:(double)arg5 completion:(CDUnknownBlockType)arg6;
- (void)handleRPCFailure:(id)arg1 desc:(id)arg2 showToast:(_Bool)arg3 mainView:(id)arg4 duration:(double)arg5;
- (void)queryPresentPassStatus:(id)arg1 completionBlock:(CDUnknownBlockType)arg2 showNetError:(_Bool)arg3;
- (void)applyPresentPass:(id)arg1 completionBlock:(CDUnknownBlockType)arg2 showNetError:(_Bool)arg3;
- (void)presentPassNew:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)presentPass:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)getPresentMsg:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)queryPassListByChannelId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)addPass:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)queryPassPreviewInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)getDynamicId:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)makeAsyncCallBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2 cancelable:(_Bool)arg3 showNetError:(_Bool)arg4;
- (void)makeCancelableAsyncCallBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2 showNetError:(_Bool)arg3;
- (void)makeNonCancelableAsyncCallBlock:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2 showNetError:(_Bool)arg3;
- (_Bool)getShareInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (_Bool)queryPagedPassList:(id)arg1 showNetError:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (_Bool)deleteUserPass:(id)arg1 completionBlock:(CDUnknownBlockType)arg2 showNetError:(_Bool)arg3;
- (void)queryMsgPassInfo:(id)arg1 completionBlock:(CDUnknownBlockType)arg2 showNetError:(_Bool)arg3;
- (_Bool)queryPassInfoById:(id)arg1 longitude:(id)arg2 latitude:(id)arg3 partnerId:(id)arg4 serialNumber:(id)arg5 completionBlock:(CDUnknownBlockType)arg6 showNetError:(_Bool)arg7;
- (void)clearAsyncCallers;
- (id)init;
- (id)currentUserId;

@end

