//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APExceptionView.h"

@interface ALPPassNetErrorView : APExceptionView
{
}

+ (id)showInViewController:(id)arg1 labelText:(id)arg2 action:(SEL)arg3 code:(long long)arg4;
+ (id)showInViewController:(id)arg1 labelText:(id)arg2 action:(SEL)arg3;

@end

