//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor;

@interface ALPVerLineView : UIView
{
    UIColor *_dottedLineColor;
}

@property(retain, nonatomic) UIColor *dottedLineColor; // @synthesize dottedLineColor=_dottedLineColor;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)arg1;

@end

