//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSString;

@interface AMapLocationUploadRequest : NSObject
{
    NSString *_fileName;
    NSData *_uploadInfoData;
}

@property(copy, nonatomic) NSData *uploadInfoData; // @synthesize uploadInfoData=_uploadInfoData;
@property(copy, nonatomic) NSString *fileName; // @synthesize fileName=_fileName;
- (void).cxx_destruct;

@end

