//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTService-Protocol.h"

@class H5PSDController, NAMApp, NSDictionary, NSString, UIViewController, UIWebView;
@protocol AMH5BusinessServiceDelegate;

@protocol AMH5BusinessService <DTService>
- (NSDictionary *)getApis:(NSString *)arg1;
- (void)unregisterApi:(NSString *)arg1;
- (void)unregisterApiName:(NSString *)arg1;
- (void)unregisterApi:(NSString *)arg1 Api:(NSString *)arg2;
- (void)registerApis:(NSDictionary *)arg1;
- (void)registerApi:(NSString *)arg1 Apis:(NSDictionary *)arg2;
- (UIWebView *)createWebViewWithVC:(UIViewController *)arg1 params:(NSDictionary *)arg2 JSApis:(NSDictionary *)arg3;
- (UIWebView *)createWebViewWithParams:(NSDictionary *)arg1 JSApis:(NSDictionary *)arg2;
- (H5PSDController *)createWebViewController:(NSDictionary *)arg1 JSApis:(NSDictionary *)arg2 withDelegate:(id <AMH5BusinessServiceDelegate>)arg3;
- (void)prepareApp:(NSString *)arg1 version:(NSString *)arg2 process:(void (^)(unsigned long long, id))arg3 finish:(void (^)(NAMApp *, NSError *))arg4;
- (void)requestApps:(NSDictionary *)arg1 finish:(void (^)(NSDictionary *, NSError *))arg2;
- (NAMApp *)findApp:(NSString *)arg1 version:(NSString *)arg2;
@end

