//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSMutableOrderedSet;

@interface AppMonitorMetricSet : NSObject
{
    NSMutableOrderedSet *_metrics;
    NSLock *_lock;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableOrderedSet *metrics; // @synthesize metrics=_metrics;
- (void).cxx_destruct;
- (id)metricForModule:(id)arg1 monitorPoint:(id)arg2;
- (void)addMetric:(id)arg1;
- (id)init;

@end

