//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VZViewController.h"

#import "AMapSearchDelegate-Protocol.h"
#import "CLLocationManagerDelegate-Protocol.h"
#import "KBCSchemeProtocol-Protocol.h"

@class AMapSearchAPI, ARGLViewManager, ARIndicatorManager, ARNaviManager, ARRadarManager, ARShopViewManager, CLLocationManager, CMMotionManager, NSArray, NSString, NSTimer, O2OARShopsModel, UIImageView, UITableView;

@interface ARShopStreetController : VZViewController <AMapSearchDelegate, CLLocationManagerDelegate, KBCSchemeProtocol>
{
    _Bool _naviMode;
    _Bool _coreMotionNeedCalibration;
    _Bool _waitCameraAuthStatus;
    CMMotionManager *_motionManager;
    CLLocationManager *_locationManager;
    ARGLViewManager *_glViewManager;
    ARShopViewManager *_shopViewManager;
    ARNaviManager *_naviManager;
    ARRadarManager *_radarManager;
    ARIndicatorManager *_indicatorManager;
    UIImageView *_backIcon;
    UIImageView *_refreshIcon;
    O2OARShopsModel *_arShopModel;
    AMapSearchAPI *_mapSearchAPI;
    NSTimer *_reloadTimer;
    NSArray *_managerQueue;
    UITableView *_tableView;
    struct CLLocationCoordinate2D _currentTruePos;
    struct CLLocationCoordinate2D _lastTruePos;
}

+ (unsigned long long)canInitWithScheme:(id)arg1;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool waitCameraAuthStatus; // @synthesize waitCameraAuthStatus=_waitCameraAuthStatus;
@property(retain, nonatomic) NSArray *managerQueue; // @synthesize managerQueue=_managerQueue;
@property(retain, nonatomic) NSTimer *reloadTimer; // @synthesize reloadTimer=_reloadTimer;
@property(nonatomic) struct CLLocationCoordinate2D lastTruePos; // @synthesize lastTruePos=_lastTruePos;
@property(retain, nonatomic) AMapSearchAPI *mapSearchAPI; // @synthesize mapSearchAPI=_mapSearchAPI;
@property(retain, nonatomic) O2OARShopsModel *arShopModel; // @synthesize arShopModel=_arShopModel;
@property(retain, nonatomic) UIImageView *refreshIcon; // @synthesize refreshIcon=_refreshIcon;
@property(retain, nonatomic) UIImageView *backIcon; // @synthesize backIcon=_backIcon;
@property(readonly, nonatomic) ARIndicatorManager *indicatorManager; // @synthesize indicatorManager=_indicatorManager;
@property(readonly, nonatomic) ARRadarManager *radarManager; // @synthesize radarManager=_radarManager;
@property(readonly, nonatomic) ARNaviManager *naviManager; // @synthesize naviManager=_naviManager;
@property(readonly, nonatomic) ARShopViewManager *shopViewManager; // @synthesize shopViewManager=_shopViewManager;
@property(readonly, nonatomic) ARGLViewManager *glViewManager; // @synthesize glViewManager=_glViewManager;
@property(nonatomic) struct CLLocationCoordinate2D currentTruePos; // @synthesize currentTruePos=_currentTruePos;
@property(readonly, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(readonly, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(nonatomic) _Bool coreMotionNeedCalibration; // @synthesize coreMotionNeedCalibration=_coreMotionNeedCalibration;
@property(nonatomic) _Bool naviMode; // @synthesize naviMode=_naviMode;
- (void).cxx_destruct;
- (void)goShopDetail:(id)arg1;
- (void)showShopTrace:(id)arg1;
- (void)hideProgressHUD;
- (void)queryTrace:(struct CLLocationCoordinate2D)arg1;
- (void)onRouteSearchDone:(id)arg1 response:(id)arg2;
- (void)AMapSearchRequest:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (struct CLLocationCoordinate2D)amapCoordFromLM;
- (id)amapLocFromLM;
- (float)computeCurrentLocRotate:(struct CLLocationCoordinate2D)arg1;
- (void)modelDidFail:(id)arg1 withError:(id)arg2;
- (void)modelDidFinish:(id)arg1;
- (void)loadShopList;
- (void)check2Reload;
- (void)force2Reload;
- (void)startReloadTimer;
- (float)computePHA;
- (void)stopMotion;
- (void)didUpdateMotion:(id)arg1 referenceFrame:(unsigned long long)arg2 error:(id)arg3;
- (void)beginMotionReference:(unsigned long long)arg1;
- (void)beginMotion;
- (void)vpChangLogic;
- (void)selectedShopObjChangLogic:(id)arg1;
- (void)managerQueueCallWithMethodName:(id)arg1 withParam:(id)arg2;
- (void)managerQueueCallWithMethodName:(id)arg1;
- (void)makeManagerQueue;
- (void)pageLeaveLogic;
- (void)beginLocationAndMotion;
- (void)beginLocation;
- (unsigned long long)getLocationState;
- (_Bool)checkLocationState;
- (void)makeLayout;
- (void)didBecomeActive;
- (void)willResignActive;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)authorizedviewDidAppearLogic;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillLayoutSubviews;
- (void)authorizedViewDidLoadLogic;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)dealloc;
- (void)didAccessForMediaLogic:(_Bool)arg1;
- (void)didAccessForMedia:(_Bool)arg1;
- (void)authorizedInitLogic;
- (id)initWithScheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

