//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface AUMethodSwizzling : NSObject
{
}

+ (void)swizzleMethod:(SEL)arg1 toMethod:(SEL)arg2 forClass:(Class)arg3;
+ (SEL)replaceSelector:(SEL)arg1 withSelector:(SEL)arg2 inClass:(Class)arg3;

@end

