//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <CoreLocation/CLLocation.h>

@class NSNumber, NSString;

@interface CLLocation (WIFIMacAddress)
@property(retain, nonatomic) NSString *lbs_optimized;
@property(retain, nonatomic) NSString *lbs_wifi_ssid;
@property(retain, nonatomic) NSString *lbs_wifi_mac;
@property(nonatomic) double lbs_unconverted_longitude;
@property(nonatomic) double lbs_unconverted_latitude;
@property(retain, nonatomic) NSNumber *lbs_from_wifi;
@property(retain, nonatomic) NSString *lbs_wifi_address;
@property(retain, nonatomic) NSNumber *location_from_alipay_client;
@end

