//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NBContentViewPageProfile.h"

@class H5PerformanceTiming, NSDate, NSString;

@interface H5PagePerformance : NBContentViewPageProfile
{
    _Bool _isReport;
    _Bool _isWK;
    _Bool _canReportProfile;
    _Bool _isWaitForStopLoading;
    _Bool _isWaitForStopLoadingWithLoc;
    int _instanceId;
    int _loadingReqs;
    int _loadingReqsWithLoc;
    NSString *_ipAddress;
    double _startTime;
    double _firstScreenTime;
    double _firstScreenTimeFromNative;
    double _stopLoadingTime;
    double _stopLoadingTimeWithLoc;
    H5PerformanceTiming *_performanceTiming;
    NSString *_generateFirst;
    NSDate *_firstAsyncStartDate;
    double _waitForStopTime;
    double _waitForStopTimeWithLoc;
    NSString *_errorType;
    NSString *_errorDomain;
    NSString *_errorCode;
    NSString *_errorExtra;
    NSString *_errorTrigger;
    NSString *_relatedImg;
}

+ (id)getMCC_MNC;
@property(copy, nonatomic) NSString *relatedImg; // @synthesize relatedImg=_relatedImg;
@property(copy, nonatomic) NSString *errorTrigger; // @synthesize errorTrigger=_errorTrigger;
@property(copy, nonatomic) NSString *errorExtra; // @synthesize errorExtra=_errorExtra;
@property(copy, nonatomic) NSString *errorCode; // @synthesize errorCode=_errorCode;
@property(copy, nonatomic) NSString *errorDomain; // @synthesize errorDomain=_errorDomain;
@property(copy, nonatomic) NSString *errorType; // @synthesize errorType=_errorType;
@property(nonatomic) double waitForStopTimeWithLoc; // @synthesize waitForStopTimeWithLoc=_waitForStopTimeWithLoc;
@property(nonatomic) double waitForStopTime; // @synthesize waitForStopTime=_waitForStopTime;
@property(nonatomic) _Bool isWaitForStopLoadingWithLoc; // @synthesize isWaitForStopLoadingWithLoc=_isWaitForStopLoadingWithLoc;
@property(nonatomic) _Bool isWaitForStopLoading; // @synthesize isWaitForStopLoading=_isWaitForStopLoading;
@property(retain, nonatomic) NSDate *firstAsyncStartDate; // @synthesize firstAsyncStartDate=_firstAsyncStartDate;
@property(nonatomic) _Bool canReportProfile; // @synthesize canReportProfile=_canReportProfile;
@property(copy, nonatomic) NSString *generateFirst; // @synthesize generateFirst=_generateFirst;
@property(nonatomic) int loadingReqsWithLoc; // @synthesize loadingReqsWithLoc=_loadingReqsWithLoc;
@property(nonatomic) int loadingReqs; // @synthesize loadingReqs=_loadingReqs;
@property(nonatomic) _Bool isWK; // @synthesize isWK=_isWK;
@property(nonatomic) _Bool isReport; // @synthesize isReport=_isReport;
@property(retain, nonatomic) H5PerformanceTiming *performanceTiming; // @synthesize performanceTiming=_performanceTiming;
@property(nonatomic) double stopLoadingTimeWithLoc; // @synthesize stopLoadingTimeWithLoc=_stopLoadingTimeWithLoc;
@property(nonatomic) double stopLoadingTime; // @synthesize stopLoadingTime=_stopLoadingTime;
@property(nonatomic) double firstScreenTimeFromNative; // @synthesize firstScreenTimeFromNative=_firstScreenTimeFromNative;
@property(nonatomic) double firstScreenTime; // @synthesize firstScreenTime=_firstScreenTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(copy, nonatomic) NSString *ipAddress; // @synthesize ipAddress=_ipAddress;
@property(nonatomic) int instanceId; // @synthesize instanceId=_instanceId;
- (void).cxx_destruct;
- (void)reportPageAbnormalWithPerformance:(id)arg1;
- (void)reportPageAbnormal;
- (void)reportPageAbnormalWithErrorType:(id)arg1 withError:(id)arg2;
- (void)reportPageAbnormalWithErrorType:(id)arg1 andErrorCode:(id)arg2;
- (void)reportSyncAjax;
- (void)reportPerformance;
- (void)printLog;
- (void)reportDidFinishedLoadDate:(id)arg1;
- (void)reportFirstScreenTime:(id)arg1;
- (void)reportRenderTime:(id)arg1;
- (void)reportReportWithReason:(id)arg1 notes:(id)arg2;
- (void)reportReport;
- (void)reportJSReport:(id)arg1;
- (void)reportJSMonitor:(id)arg1;
- (void)reportPSDType:(id)arg1;
- (void)reportCreateDate:(id)arg1;
- (void)stopLoadingWithLoc;
- (void)stopLoading;
- (void)stopWaitForStopLoading;
- (void)waitForStopLoading;
- (void)stopWaitForStopLoadingWithLoc;
- (void)waitForStopLoadingWithLoc;
- (void)reportLocEnd;
- (void)reportLocStart;
- (void)reportReqEnd;
- (void)reportReqStart;
- (void)mergeProfile:(id)arg1;
- (id)init;

// Remaining properties
@property(copy, nonatomic) NSString *url;

@end

