//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBCSAResponseData.h"

@class NSArray;

@interface KBCSAMyWaitCommentResponse : KBCSAResponseData
{
    _Bool _hasNextPage;
    NSArray *_myKoubeiOrderDetail;
    long long _totalSize;
}

+ (Class)myKoubeiOrderDetailElementClass;
@property(nonatomic) _Bool hasNextPage; // @synthesize hasNextPage=_hasNextPage;
@property(nonatomic) long long totalSize; // @synthesize totalSize=_totalSize;
@property(retain, nonatomic) NSArray *myKoubeiOrderDetail; // @synthesize myKoubeiOrderDetail=_myKoubeiOrderDetail;
- (void).cxx_destruct;

@end

