//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBCSAResponseData.h"

@class NSDictionary;

@interface KBCSADiscountCanUseResponse : KBCSAResponseData
{
    _Bool _canUse;
    NSDictionary *_data;
}

+ (Class)dataElementClass;
@property(retain, nonatomic) NSDictionary *data; // @synthesize data=_data;
@property(nonatomic) _Bool canUse; // @synthesize canUse=_canUse;
- (void).cxx_destruct;

@end

