//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "O2OHTTPListModel.h"

@class NSString;

@interface KBLiveCastCreateRoomModel : O2OHTTPListModel
{
    long long _validTime;
    NSString *_title;
    NSString *_imgLink;
    NSString *_startTimer;
    NSString *_liveid;
}

@property(readonly, nonatomic) NSString *liveid; // @synthesize liveid=_liveid;
@property(retain, nonatomic) NSString *startTimer; // @synthesize startTimer=_startTimer;
@property(retain, nonatomic) NSString *imgLink; // @synthesize imgLink=_imgLink;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long validTime; // @synthesize validTime=_validTime;
- (void).cxx_destruct;
- (_Bool)parseResponse:(id)arg1;
- (SEL)selectorNameForRPCService;
- (Class)RPCServiceClass;
- (Class)RPCResponseClass;
- (Class)RPCRequestClass;
- (id)rpcRequest;
- (id)key;
- (id)cacheKey;

@end

