//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface KBUpdateServiceImpl : NSObject
{
}

- (void)setLastAlertUpdateDate:(id)arg1 version:(id)arg2;
- (id)lastAlertUpdateDateWithVersion:(id)arg1;
- (void)alertUpdate:(id)arg1;
- (void)alertForceUpdate:(id)arg1;
- (void)alertUpdateIfNeed:(id)arg1;
- (void)checkUpdate:(CDUnknownBlockType)arg1;
- (void)checkUpdate;
- (void)start;

@end

