//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NAMDataStorageProtocol-Protocol.h"

@class NAMDataStorageAccessor, NSString;

@interface NAMDataStorageBiz : NSObject <NAMDataStorageProtocol>
{
    NAMDataStorageAccessor *_storageAccessor;
}

@property(retain, nonatomic) NAMDataStorageAccessor *storageAccessor; // @synthesize storageAccessor=_storageAccessor;
- (void).cxx_destruct;
- (id)storageInMode;
- (_Bool)saveData:(id)arg1 forKey:(id)arg2;
- (id)valueForKey:(id)arg1;
- (_Bool)saveClientConfigs:(id)arg1;
- (id)clientConfigs;
- (_Bool)saveInstalledApps:(id)arg1 scene:(unsigned long long)arg2;
- (id)installedApps:(unsigned long long)arg1;
- (_Bool)saveApps:(id)arg1 scene:(unsigned long long)arg2;
- (id)allApps:(unsigned long long)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

