//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NAMNetReachability;

@interface NAMReachability : NSObject
{
    int _networkStatus;
    NAMNetReachability *_internetReach;
}

+ (id)sharedNAMReachability;
@property(retain, nonatomic) NAMNetReachability *internetReach; // @synthesize internetReach=_internetReach;
@property(nonatomic) int networkStatus; // @synthesize networkStatus=_networkStatus;
- (void).cxx_destruct;
- (id)telephonyInfo;
- (_Bool)isReachableVia2G;
- (_Bool)isReachableVia3G;
- (void)refreshReachability;
- (void)updateWithReachability:(id)arg1;
- (void)reachabilityChanged:(id)arg1;

@end

