//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PSDEvent.h"

@class UIButton;

@interface NBNavigationItemEvent : PSDEvent
{
    UIButton *_customView;
}

+ (id)clickEvent:(id)arg1;
+ (id)createAfterEvent:(id)arg1;
+ (id)createBeforeEvent:(id)arg1;
+ (id)allEvent:(id)arg1;
@property(retain, nonatomic) UIButton *customView; // @synthesize customView=_customView;
- (void).cxx_destruct;

@end

