//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSFileManager.h>

@interface NSFileManager (O2OOverLap)
- (_Bool)moveItemAtPath:(id)arg1 toOverLapPath:(id)arg2 error:(id *)arg3;
- (_Bool)moveItemAtURL:(id)arg1 toOverLapURL:(id)arg2 error:(id *)arg3;
@end

