//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VZListViewDelegate.h"

@class NSDictionary;

@interface O2OCommentListDelegate : VZListViewDelegate
{
    NSDictionary *_expIds;
}

@property(retain, nonatomic) NSDictionary *expIds; // @synthesize expIds=_expIds;
- (void).cxx_destruct;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (id)init;

@end

