//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VZItem.h"

#import "NSCopying-Protocol.h"
#import "NSObject-Protocol.h"

@class NSString;

@interface O2OFeelingCardItem : VZItem <NSObject, NSCopying>
{
    unsigned long long _bgColorValue;
    NSString *_bgImageUrl;
    NSString *_headImageUrl;
    NSString *_content;
    NSString *_source;
    NSString *_bottomImageUrl;
    NSString *_num;
    long long _typeId;
    long long _sortNum;
    unsigned long long _objHash;
}

@property(nonatomic) unsigned long long objHash; // @synthesize objHash=_objHash;
@property(nonatomic) long long sortNum; // @synthesize sortNum=_sortNum;
@property(nonatomic) long long typeId; // @synthesize typeId=_typeId;
@property(copy, nonatomic) NSString *num; // @synthesize num=_num;
@property(copy, nonatomic) NSString *bottomImageUrl; // @synthesize bottomImageUrl=_bottomImageUrl;
@property(copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(copy, nonatomic) NSString *content; // @synthesize content=_content;
@property(copy, nonatomic) NSString *headImageUrl; // @synthesize headImageUrl=_headImageUrl;
@property(copy, nonatomic) NSString *bgImageUrl; // @synthesize bgImageUrl=_bgImageUrl;
@property(nonatomic) unsigned long long bgColorValue; // @synthesize bgColorValue=_bgColorValue;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) unsigned long long hash;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

