//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface O2OMerchantQRView : UIView
{
}

+ (id)drawQRCode:(id)arg1 size:(double)arg2 backgroundColor:(id)arg3;
+ (id)drawBarCode:(id)arg1 size:(struct CGSize)arg2 backgroundColor:(id)arg3;
+ (id)createQRView:(id)arg1 shopName:(id)arg2 logo:(id)arg3 frame:(struct CGRect)arg4;

@end

