//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSMutableDictionary;

@interface O2OShopFaceFeatureLoader : NSObject
{
    _Bool _cacheLoading;
    _Bool _featureListReady;
    CDUnknownBlockType _cacheLoadedBlock;
    NSMutableDictionary *_shop2FeatureDic;
    NSMutableArray *_queryQueue;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableArray *queryQueue; // @synthesize queryQueue=_queryQueue;
@property(retain, nonatomic) NSMutableDictionary *shop2FeatureDic; // @synthesize shop2FeatureDic=_shop2FeatureDic;
@property(nonatomic) _Bool featureListReady; // @synthesize featureListReady=_featureListReady;
@property(copy, nonatomic) CDUnknownBlockType cacheLoadedBlock; // @synthesize cacheLoadedBlock=_cacheLoadedBlock;
@property(readonly, nonatomic) _Bool cacheLoading; // @synthesize cacheLoading=_cacheLoading;
- (void).cxx_destruct;
- (_Bool)cleanCache;
- (_Bool)cleanCacheByLRU;
- (_Bool)cleanMem;
- (_Bool)check2cleanCacheByLRU:(float)arg1;
- (unsigned long long)cachedFeatureSize;
- (long long)folderSizeAtPath:(id)arg1;
- (long long)fileSizeAtPath:(id)arg1;
- (unsigned long long)cachedFeatureCount;
- (void)check2LoadShopFeatures:(id)arg1 WithCompleted:(CDUnknownBlockType)arg2;
- (_Bool)writeShopFeature:(id)arg1 localURL:(id)arg2;
- (_Bool)unzipFeatureFile:(id)arg1 toPath:(id)arg2;
- (_Bool)verifyFeatureFile:(id)arg1;
- (_Bool)replaceShopFeature:(id)arg1;
- (void)removeQuery:(id)arg1;
- (id)loadFeaturesByloc:(id)arg1;
- (id)loadFeaturesFromeCache:(id)arg1;
- (id)imageFeatureById:(id)arg1;
- (void)loadFeatureNamesFromCaches;
- (void)loadFeatureNamesWithCompleted:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)init;

@end

