//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CAShapeLayer, UILabel;

@interface O2OShopFaceProgressLoopView : UIView
{
    float _process;
    UILabel *_progressLabel;
    UIView *_loopView;
    CAShapeLayer *_processFanLayer;
}

@property(retain, nonatomic) CAShapeLayer *processFanLayer; // @synthesize processFanLayer=_processFanLayer;
@property(retain, nonatomic) UIView *loopView; // @synthesize loopView=_loopView;
@property(retain, nonatomic) UILabel *progressLabel; // @synthesize progressLabel=_progressLabel;
@property(nonatomic) float process; // @synthesize process=_process;
- (void).cxx_destruct;
- (void)showProcess;
- (void)makeLayout;
- (id)initWithFrame:(struct CGRect)arg1;

@end

