//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface O2OShopRecommend : APPBGeneratedMessage <GeneratedMessageProtocol>
{
    _Bool _hasTitle;
    _Bool _hasHasMore;
    _Bool _hasLabelId;
    _Bool _hasDtLogMonitor;
    _Bool _hasMore;
    NSString *_title;
    NSMutableArray *_shopDetails;
    NSString *_labelId;
    NSString *_dtLogMonitor;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *dtLogMonitor; // @synthesize dtLogMonitor=_dtLogMonitor;
@property(retain, nonatomic) NSString *labelId; // @synthesize labelId=_labelId;
@property(nonatomic) _Bool hasMore; // @synthesize hasMore=_hasMore;
@property(retain, nonatomic) NSMutableArray *shopDetails; // @synthesize shopDetails=_shopDetails;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(readonly) _Bool hasDtLogMonitor; // @synthesize hasDtLogMonitor=_hasDtLogMonitor;
@property(readonly) _Bool hasLabelId; // @synthesize hasLabelId=_hasLabelId;
@property(readonly) _Bool hasHasMore; // @synthesize hasHasMore=_hasHasMore;
@property(readonly) _Bool hasTitle; // @synthesize hasTitle=_hasTitle;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (void)addShopDetails:(id)arg1;
- (void)setShopDetailsArray:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

