//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class CADisplayLink, NSArray;

@interface O2OVolumeAnimationContainerView : UIView
{
    _Bool _handleVolumeChange;
    NSArray *_viewArray;
    NSArray *_spreadHeightArray;
    CADisplayLink *_displayLink;
    unsigned long long _startIndex;
}

@property(nonatomic) _Bool handleVolumeChange; // @synthesize handleVolumeChange=_handleVolumeChange;
@property(nonatomic) unsigned long long startIndex; // @synthesize startIndex=_startIndex;
@property(retain, nonatomic) CADisplayLink *displayLink; // @synthesize displayLink=_displayLink;
@property(retain, nonatomic) NSArray *spreadHeightArray; // @synthesize spreadHeightArray=_spreadHeightArray;
@property(retain, nonatomic) NSArray *viewArray; // @synthesize viewArray=_viewArray;
- (void).cxx_destruct;
- (void)reset;
- (void)showResume;
- (void)showWillCancle;
- (void)handleDisplayLink:(id)arg1;
- (void)stopSpreadAnimation;
- (void)startSpreadAnimation;
- (void)setVolumeHeight:(double)arg1;
- (void)setVolume:(unsigned long long)arg1;
- (void)setupView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

