//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray, NSString;

@interface UTMCStreamModel : NSObject
{
    NSMutableArray *_dataList;
    NSString *_key;
}

@property(retain, nonatomic) NSString *key; // @synthesize key=_key;
@property(retain, nonatomic) NSMutableArray *dataList; // @synthesize dataList=_dataList;
- (void).cxx_destruct;
- (_Bool)isSystemVersionMoreThanTen;
- (id)toStringOld;
- (id)toString;
- (void)appendStream:(id)arg1;
- (id)initWithKey:(id)arg1;

@end

