//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PTHLogger : NSObject
{
}

+ (void)logError:(id)arg1 descriptionFormat:(id)arg2;
+ (void)logException:(id)arg1 descriptionFormat:(id)arg2;
+ (void)logRequest:(id)arg1 responseValue:(id)arg2 error:(id)arg3;
+ (void)logFormat:(id)arg1;
+ (void)logString:(id)arg1;
+ (id)logStrings:(unsigned long long)arg1;
+ (id)logStrings;
+ (void)logUncaughtExceptions;

@end

