//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PTHTweetbotStatusCursor.h"

@interface PTHTweetbotStatusRepliesCursor : PTHTweetbotStatusCursor
{
}

+ (Class)itemClass;
- (id)newItemWithDictionary:(id)arg1;
- (id)queryDictionary;
- (id)itemsArrayFromResponse:(id)arg1;
- (id)requestURLString;
- (_Bool)hasReadStatus;

@end

