//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class PTHTweetbotAccount, PTHTweetbotAccountController, PTHTweetbotLaunchController, UIView, UIViewController;

@interface PTHTweetbotAppController : NSObject
{
    PTHTweetbotLaunchController *_launchController;
    PTHTweetbotAccountController *_selectedAccountController;
    UIView *_launchBackgroundView;
}

+ (id)selectedAccountController;
+ (id)appController;
+ (void)unmuteNewItemsSound;
+ (void)muteNewItemsSound;
+ (void)playNewItemsSound;
+ (void)initialize;
@property(readonly, nonatomic) PTHTweetbotAccountController *selectedAccountController; // @synthesize selectedAccountController=_selectedAccountController;
- (void).cxx_destruct;
- (void)setSelectedAccount:(id)arg1 selectedTab:(long long)arg2 animated:(_Bool)arg3 completion:(CDUnknownBlockType)arg4;
@property(readonly, nonatomic) __weak PTHTweetbotAccount *selectedAccount;
@property(nonatomic) __weak PTHTweetbotAccount *launchAccount;
@property(readonly, nonatomic) UIViewController *currentViewController;
- (id)createLaunchRootController;
- (void)runLaunchAnimation:(CDUnknownBlockType)arg1;
- (void)prepareLaunchAnimation;

@end

