//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PTHTweetbotCursor.h"

@class PTHTweetbotList;

@interface PTHTweetbotListCursor : PTHTweetbotCursor
{
    PTHTweetbotList *_list;
}

@property(readonly, nonatomic) __weak PTHTweetbotList *list; // @synthesize list=_list;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)queryDictionary;
- (void)setAccount:(id)arg1;
- (id)uniqueID;
- (id)initWithList:(id)arg1;

@end

