//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MQQWebViewController.h"

@interface MQQAssistWebViewController : MQQWebViewController
{
}

- (void)didCancelSharing;
- (void)willShareToDestination:(long long)arg1;
- (void)fetchURLStringForSharing:(CDUnknownBlockType)arg1;
- (_Bool)canShare;
- (void)willShare;
- (void)fetchWebContent:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (id)initWithURLString:(id)arg1 title:(id)arg2;

@end

