//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary;

@interface MQQConch : NSObject
{
    _Bool _mutilValueEnable;
    long long _conchID;
    long long _conchSeqNo;
    long long _time;
    unsigned long long _taskID;
    unsigned long long _taskSeqNo;
    NSDictionary *_params;
}

+ (int)convertConchIDToServerID:(long long)arg1;
+ (long long)convertServerIDToConchID:(int)arg1;
@property(nonatomic) _Bool mutilValueEnable; // @synthesize mutilValueEnable=_mutilValueEnable;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(nonatomic) unsigned long long taskSeqNo; // @synthesize taskSeqNo=_taskSeqNo;
@property(nonatomic) unsigned long long taskID; // @synthesize taskID=_taskID;
@property(nonatomic) long long time; // @synthesize time=_time;
@property(nonatomic) long long conchSeqNo; // @synthesize conchSeqNo=_conchSeqNo;
@property(nonatomic) long long conchID; // @synthesize conchID=_conchID;
- (void)dealloc;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

