//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MQQBaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class MQQDeviceInfoTopView, NSArray, NSString, UITableView, UIView;

@interface MQQDeviceInfoController : MQQBaseViewController <UITableViewDelegate, UITableViewDataSource>
{
    UIView *_headerView;
    MQQDeviceInfoTopView *_iphoneInfoView;
    UITableView *_tableView;
    NSArray *_sectionData;
}

@property(retain, nonatomic) NSArray *sectionData; // @synthesize sectionData=_sectionData;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) MQQDeviceInfoTopView *iphoneInfoView; // @synthesize iphoneInfoView=_iphoneInfoView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
- (id)_getHardwareInfos;
- (id)_getNetworkInfos;
- (id)_getBaseInfos;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateDeviceInfo:(id)arg1;
- (void)refreshTableView;
- (void)updateAllDeviceInfo;
- (void)registerNotifications;
- (void)dealloc;
- (void)doInitTableView;
- (void)doInitHeaderView;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

