//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "MQQECFilterProtocol-Protocol.h"
#import "MQQSharkRequestDelegate-Protocol.h"

@class MQQMCMessageCheckRequest, NSArray, NSString;

@interface MQQECServerFilter : NSObject <MQQSharkRequestDelegate, MQQECFilterProtocol>
{
    NSArray *_groups;
    MQQMCMessageCheckRequest *_checkRequest;
    CDUnknownBlockType _completionHandler;
}

@property(copy, nonatomic) CDUnknownBlockType completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain, nonatomic) MQQMCMessageCheckRequest *checkRequest; // @synthesize checkRequest=_checkRequest;
@property(copy, nonatomic) NSArray *groups; // @synthesize groups=_groups;
- (void)sharkRequestDidFail:(id)arg1;
- (void)sharkRequestDidFinish:(id)arg1 withInfo:(id)arg2;
- (void)cancel;
- (void)timeout;
- (void)filterGroups:(id)arg1 withCompletionHandler:(CDUnknownBlockType)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

