//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MQQInfomationRecordOp;

@interface MQQInfomationRecordManager : NSObject
{
    MQQInfomationRecordOp *_recordOp;
    long long _categoryID;
}

+ (id)sharedManagerWithCategoryID:(long long)arg1;
@property(nonatomic) long long categoryID; // @synthesize categoryID=_categoryID;
- (void)closeDatabase;
- (id)database;
- (id)infomationWithID:(long long)arg1;
- (void)fillInfomationLists:(id)arg1;
- (id)unfilledInfomationLists;
- (id)filledInfomationLists;
- (void)updateInfomationLists:(id)arg1;
- (id)infomationListWithID:(long long)arg1;
- (id)infomationLists;
- (id)initWithCategoryID:(long long)arg1;
- (void)dealloc;

@end

