//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MQQAsset.h"

@class CLLocation, NSDate;

@interface MQQMutableAsset : MQQAsset
{
    NSDate *__creationDate;
    CLLocation *__location;
}

+ (id)assetWithAsset:(id)arg1;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=__location;
@property(retain, nonatomic) NSDate *creationDate; // @synthesize creationDate=__creationDate;
@property(readonly, retain, nonatomic) CLLocation *_location;
@property(readonly, retain, nonatomic) NSDate *_creationDate;
- (void)dealloc;

@end

