//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MQQPFPhotoJourneyBaseView.h"

@class UIImageView;

@interface MQQPFPhotoJourneySpringTitleView : MQQPFPhotoJourneyBaseView
{
    UIImageView *_titleImageView;
}

@property(retain, nonatomic) UIImageView *titleImageView; // @synthesize titleImageView=_titleImageView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 isDefaultStyle:(_Bool)arg2;

@end

