//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UINavigationController.h>

@interface PtNavigationController : UINavigationController
{
    _Bool _bIsAutoRotate;
}

@property _Bool bIsAutoRotate; // @synthesize bIsAutoRotate=_bIsAutoRotate;
- (void)setAutoRotate:(_Bool)arg1;
- (id)init;
- (_Bool)shouldAutorotate;

@end

