//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class UIImage, UIImageView, UILabel;
@protocol TabBarDelegate;

@interface CustomTabBarView : UIButton
{
    UILabel *lblTabBar;
    UIImageView *tabBarImageView;
    UIImage *normalImg;
    UIImage *selectedImg;
    id <TabBarDelegate> delegate;
}

@property(nonatomic) id <TabBarDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) UIImage *selectedImg; // @synthesize selectedImg;
@property(retain, nonatomic) UIImage *normalImg; // @synthesize normalImg;
@property(retain, nonatomic) UIImageView *tabBarImageView; // @synthesize tabBarImageView;
@property(retain, nonatomic) UILabel *lblTabBar; // @synthesize lblTabBar;
- (void).cxx_destruct;
- (void)setTitleColor:(id)arg1 forState:(unsigned long long)arg2;
- (void)touched:(id)arg1;
- (void)setSelected:(_Bool)arg1;
- (void)setAlignEx:(unsigned long long)arg1;
- (void)setAlign:(unsigned long long)arg1;
- (id)initWithTextEx:(id)arg1 Image:(id)arg2 selectedImg:(id)arg3;
- (id)initWithText:(id)arg1 Image:(id)arg2 selectedImg:(id)arg3;

@end

