//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FBSDKWebDialogView, NSDictionary, NSError;

@protocol FBSDKWebDialogViewDelegate <NSObject>
- (void)webDialogViewDidFinishLoad:(FBSDKWebDialogView *)arg1;
- (void)webDialogViewDidCancel:(FBSDKWebDialogView *)arg1;
- (void)webDialogView:(FBSDKWebDialogView *)arg1 didFailWithError:(NSError *)arg2;
- (void)webDialogView:(FBSDKWebDialogView *)arg1 didCompleteWithResults:(NSDictionary *)arg2;
@end

