//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "IOMBaseViewController.h"

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSMutableArray, NSString, UILabel, UITableView, UIView;

@interface IOMCommentViewController : IOMBaseViewController <UITableViewDataSource, UITableViewDelegate>
{
    CDUnknownBlockType _webout;
    CDUnknownBlockType _childWebout;
    CDUnknownBlockType _reWebout;
    CDUnknownBlockType _loadClick;
    CDUnknownBlockType _remove;
    CDUnknownBlockType _setComment;
    CDUnknownBlockType _loginIn;
    CDUnknownBlockType _refreshTableViewHeight;
    NSMutableArray *_dataArray;
    UITableView *_commentTableView;
    UIView *_loadMoreView;
    UILabel *_messageLabel;
    UIView *_nomessageView;
    long long _height;
}

@property(nonatomic) long long height; // @synthesize height=_height;
@property(nonatomic) __weak UIView *nomessageView; // @synthesize nomessageView=_nomessageView;
@property(nonatomic) __weak UILabel *messageLabel; // @synthesize messageLabel=_messageLabel;
@property(retain, nonatomic) UIView *loadMoreView; // @synthesize loadMoreView=_loadMoreView;
@property(nonatomic) __weak UITableView *commentTableView; // @synthesize commentTableView=_commentTableView;
@property(retain, nonatomic) NSMutableArray *dataArray; // @synthesize dataArray=_dataArray;
@property(copy, nonatomic) CDUnknownBlockType refreshTableViewHeight; // @synthesize refreshTableViewHeight=_refreshTableViewHeight;
@property(copy, nonatomic) CDUnknownBlockType loginIn; // @synthesize loginIn=_loginIn;
@property(copy, nonatomic) CDUnknownBlockType setComment; // @synthesize setComment=_setComment;
@property(copy, nonatomic) CDUnknownBlockType remove; // @synthesize remove=_remove;
@property(copy, nonatomic) CDUnknownBlockType loadClick; // @synthesize loadClick=_loadClick;
@property(copy, nonatomic) CDUnknownBlockType reWebout; // @synthesize reWebout=_reWebout;
@property(copy, nonatomic) CDUnknownBlockType childWebout; // @synthesize childWebout=_childWebout;
@property(copy, nonatomic) CDUnknownBlockType webout; // @synthesize webout=_webout;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (void)creatTab:(id)arg1 action:(SEL)arg2;
- (void)addMoreOrlessMoreList:(id)arg1 andSection:(long long)arg2;
- (void)loadClicked;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)changeHeight:(long long)arg1;
- (void)creatNoMessageView;
- (void)creatUI;
- (void)viewDidLoad;
- (id)initWithHeight:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

