//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class IOMCommonActionTarget, UIImageView, UILabel;

@interface IOMFeedGoodItemView : UIView
{
    CDUnknownBlockType _handleClickedItemEvent;
    UIImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_priceLabel;
    UILabel *_originPriceLabel;
    UIView *_sepView;
    IOMCommonActionTarget *_target;
}

@property(retain, nonatomic) IOMCommonActionTarget *target; // @synthesize target=_target;
@property(retain, nonatomic) UIView *sepView; // @synthesize sepView=_sepView;
@property(retain, nonatomic) UILabel *originPriceLabel; // @synthesize originPriceLabel=_originPriceLabel;
@property(retain, nonatomic) UILabel *priceLabel; // @synthesize priceLabel=_priceLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView=_imageView;
@property(copy, nonatomic) CDUnknownBlockType handleClickedItemEvent; // @synthesize handleClickedItemEvent=_handleClickedItemEvent;
- (void).cxx_destruct;
- (void)showSepView:(_Bool)arg1;
- (void)bgBtnClicked;
- (void)refreshGoodsInfo:(id)arg1;
- (void)drawSelf;
- (id)init;

@end

