//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface iomVideoProductObject : NSObject
{
    NSString *_img;
    NSString *_title;
    NSString *_subtitle;
    NSString *_price;
    NSString *_originalPrice;
    NSString *_type;
    NSString *_url;
    NSString *_pageTypeId;
    NSString *_pageDataId;
}

@property(copy, nonatomic) NSString *pageDataId; // @synthesize pageDataId=_pageDataId;
@property(copy, nonatomic) NSString *pageTypeId; // @synthesize pageTypeId=_pageTypeId;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSString *type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *originalPrice; // @synthesize originalPrice=_originalPrice;
@property(copy, nonatomic) NSString *price; // @synthesize price=_price;
@property(copy, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *img; // @synthesize img=_img;
- (void).cxx_destruct;

@end

