//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DataLoadManager.h"

@class NSMutableString, NSString;

@interface IQYCMCCGetUseInfoManager : DataLoadManager
{
    NSMutableString *_url;
    NSString *_sign;
}

+ (id)sortParasByASCWithUrl:(id)arg1;
- (void).cxx_destruct;
- (_Bool)parse:(id)arg1;
- (void)prepareSign;
- (void)prepareUrl;
- (void)loadData;
- (id)urlStl;
- (id)init;

@end

