//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDictionary;

@interface ISLRCReadBaseObject : NSObject
{
    long long _readMsgType;
    NSDictionary *_jsonDic;
}

@property(retain, nonatomic) NSDictionary *jsonDic; // @synthesize jsonDic=_jsonDic;
@property(nonatomic) long long readMsgType; // @synthesize readMsgType=_readMsgType;
- (void).cxx_destruct;
- (id)initWithDic:(id)arg1;
- (id)init;

@end

