//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ISLRCReadBaseObject.h"

@interface ISLRCReadOnlineNumObject : ISLRCReadBaseObject
{
    long long _onlineNum;
    long long _onlineVIPNum;
    long long _totalNum;
    long long _visitorNum;
}

@property(nonatomic) long long visitorNum; // @synthesize visitorNum=_visitorNum;
@property(nonatomic) long long totalNum; // @synthesize totalNum=_totalNum;
@property(nonatomic) long long onlineVIPNum; // @synthesize onlineVIPNum=_onlineVIPNum;
@property(nonatomic) long long onlineNum; // @synthesize onlineNum=_onlineNum;
- (id)initWithDic:(id)arg1;

@end

