//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class PPao_CaptureVideoController;

@protocol PPao_CaptureVideoControllerDelegate <NSObject>

@optional
- (void)captureVideoChangeCameraPosition:(PPao_CaptureVideoController *)arg1;
- (void)captureVideoAuthorityFailure:(PPao_CaptureVideoController *)arg1;
- (void)captureVideoDidStopRecording:(PPao_CaptureVideoController *)arg1;
- (void)captureVideoWillStopRecording:(PPao_CaptureVideoController *)arg1;
- (void)captureVideoDidStartRecording:(PPao_CaptureVideoController *)arg1;
- (void)captureVideoWillStartRecording:(PPao_CaptureVideoController *)arg1;
@end

