//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QYPPFansLevelLabel, UIImageView, UILabel;

@interface PPao_SuspendTaskFansRankCell : UITableViewCell
{
    UIImageView *_avatarImg;
    UILabel *_nickName;
    UIImageView *_rankBackground;
    UILabel *_rankLabel;
    QYPPFansLevelLabel *_fansLevel;
    UILabel *_fansScore;
    CDUnknownBlockType _avatarBlock;
}

@property(copy, nonatomic) CDUnknownBlockType avatarBlock; // @synthesize avatarBlock=_avatarBlock;
@property(retain, nonatomic) UILabel *fansScore; // @synthesize fansScore=_fansScore;
@property(retain, nonatomic) QYPPFansLevelLabel *fansLevel; // @synthesize fansLevel=_fansLevel;
@property(retain, nonatomic) UILabel *rankLabel; // @synthesize rankLabel=_rankLabel;
@property(retain, nonatomic) UIImageView *rankBackground; // @synthesize rankBackground=_rankBackground;
@property(retain, nonatomic) UILabel *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) UIImageView *avatarImg; // @synthesize avatarImg=_avatarImg;
- (void).cxx_destruct;
- (void)avatarImgClicked:(id)arg1;
- (void)loadSuspendBestFansData:(id)arg1;
- (void)setup;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

