//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "PPao_IMRawDataModel-Protocol.h"

@class NSString;

@interface PPao_IMRawMessageDataModel : NSObject <PPao_IMRawDataModel>
{
}

+ (id)FMDBCreateTableSql;
+ (id)FMDBTableName;
+ (id)FMDBUniqueKeys;
+ (id)FMDBPrimaryKeys;
+ (id)FMDBAllColumnNames;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

