//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSNumber, NSString;

@interface PPCircleFeedGeniusModel : MTLModel <MTLJSONSerializing>
{
    NSNumber *_score;
    NSString *_url;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(copy, nonatomic) NSString *url; // @synthesize url=_url;
@property(copy, nonatomic) NSNumber *score; // @synthesize score=_score;
- (void).cxx_destruct;

@end

