//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

#import "RaceViewDelegate-Protocol.h"

@class NSString, OuterRace, RaceView, UIImageView, UIView;

@interface PPQ_ShootButton : UIControl <RaceViewDelegate>
{
    RaceView *_raceView;
    OuterRace *_outerRace;
    UIView *_innerRace;
    UIImageView *_pauseView;
    _Bool _willResignActive;
    _Bool _isAnimating;
    _Bool _isReset;
    _Bool _isLaterPause;
    _Bool _show3sAnimation;
    long long _shootState;
}

@property(nonatomic) _Bool show3sAnimation; // @synthesize show3sAnimation=_show3sAnimation;
@property(readonly, nonatomic) long long shootState; // @synthesize shootState=_shootState;
- (void).cxx_destruct;
- (void)appBecomeActive;
- (void)appWillResignActive;
- (void)raceViewCountdownAnimationStopped:(id)arg1;
- (void)stop;
- (void)pause;
- (void)start;
- (void)shootAction;
- (void)resetLaterPause;
- (void)laterPause:(double)arg1;
- (void)showCountdownAniamtion;
- (void)shootAction:(id)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (_Bool)isAnimating;
- (void)stopAnimation;
- (void)startAnimation;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

