//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class PPQ_FilterControlView;

@protocol PPQ_FilterControlViewDelegate <NSObject>

@optional
- (void)filterControlChangeCameraPosition:(PPQ_FilterControlView *)arg1;
- (void)filterControlChangeMode:(PPQ_FilterControlView *)arg1;
- (void)filterControlAuthorityFailure:(PPQ_FilterControlView *)arg1;
- (void)filterControl:(PPQ_FilterControlView *)arg1 writeProgress:(double)arg2;
- (void)filterControl:(PPQ_FilterControlView *)arg1 selectedAtIndex:(long long)arg2;
- (void)filterControlWillChangeFilter:(PPQ_FilterControlView *)arg1;
@end

