//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIButton, UIImage, UIImageView, UILabel;
@protocol PPQ_CameraNavBarDelegate;

@interface PPQ_CameraNavBar : UIView
{
    UIImageView *_effectView;
    UIView *_bgViewOnEffectView;
    UIButton *_leftButton;
    UILabel *_titleLabel;
    id <PPQ_CameraNavBarDelegate> _delegate;
    UIView *_contentView;
    UIImage *_effectImage;
    UIImage *_leftImage;
    NSString *_title;
}

@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) UIImage *leftImage; // @synthesize leftImage=_leftImage;
@property(retain, nonatomic) UIImage *effectImage; // @synthesize effectImage=_effectImage;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) id <PPQ_CameraNavBarDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)removeBackgroundView;
- (void)setBackgroundAlpha:(double)arg1;
- (void)backAction;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)dealloc;

@end

