//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QiXiuDataModelPlugin : NSObject
{
}

+ (void)accessServerError:(id)arg1:(id)arg2:(id)arg3:(id)arg4;
+ (void)postUrl:(id)arg1 params:(id)arg2 authorization:(id)arg3 allowFetchCache:(_Bool)arg4 blockWithSuccess:(CDUnknownBlockType)arg5 failure:(CDUnknownBlockType)arg6;
+ (void)postUrl:(id)arg1 params:(id)arg2 allowFetchCache:(_Bool)arg3 blockWithSuccess:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (void)postUrl:(id)arg1 authorization:(id)arg2 params:(id)arg3 allowFetchCache:(_Bool)arg4 blockWithSuccess:(CDUnknownBlockType)arg5;
+ (void)postUrl:(id)arg1 params:(id)arg2 allowFetchCache:(_Bool)arg3 blockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)fetchCardTask:(id)arg1 anchorId:(id)arg2 block:(CDUnknownBlockType)arg3;
+ (void)clockCardTask:(id)arg1 taskId:(id)arg2 roomId:(id)arg3 currentDay:(_Bool)arg4 block:(CDUnknownBlockType)arg5;
+ (void)fetchCardList:(id)arg1 block:(CDUnknownBlockType)arg2;
+ (void)switchLiveRoom:(_Bool)arg1 excluded_room_id:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)getEmotions:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)changeCarWithAuthcookie:(id)arg1 andProductId:(id)arg2 andStatus:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)getBuyCarListFromPage:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
+ (void)getNBCarWithRoomid:(id)arg1 page:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getTaskRewardWithTaskID:(id)arg1 andAuthCookie:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getAnimationListCompletionBlockWithSuccess:(CDUnknownBlockType)arg1;
+ (void)getChatLiveInfoWithRoomId:(id)arg1 anchorId:(id)arg2 authCookie:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4 failure:(CDUnknownBlockType)arg5;
+ (void)getLiveIpCompletionBlockWithSuccess:(CDUnknownBlockType)arg1;
+ (void)getLiveStreamUrlWithTypeId:(id)arg1 vid:(id)arg2 userId:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)submitFeedbackWithTicket:(id)arg1 andEntryClass:(id)arg2 andFeedbackClass:(id)arg3 andFeedbackContent:(id)arg4 andUserPhoneNumber:(id)arg5 andUserQQNumber:(id)arg6 andEmailAddress:(id)arg7 completionBlockWithSuccess:(CDUnknownBlockType)arg8;
+ (void)getFeedbackTicketWithCompletionBlockWithSuccess:(CDUnknownBlockType)arg1;
+ (void)deleteSystemMsgByAuthcookie:(id)arg1 uid:(id)arg2 msgids:(id)arg3 status:(id)arg4 agentType:(id)arg5 completionBlockWithSuccess:(CDUnknownBlockType)arg6;
+ (void)getSystemMsgByAgentType:(id)arg1 andUserID:(id)arg2 andAuthCookie:(id)arg3 andStatus:(id)arg4 andPage:(id)arg5 completionBlockWithSuccess:(CDUnknownBlockType)arg6;
+ (void)cardInTodayByAuthcookie:(id)arg1 taskID:(id)arg2 roomID:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)getPackageProductByProductID:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)deleteSearchWordsByAuthcookie:(id)arg1 andWords:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getSearchWordsByAuthcookie:(id)arg1 andNum:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getSearchResultWithWords:(id)arg1 authcookie:(id)arg2 page:(id)arg3 pageSize:(id)arg4 completionBlockWithSuccess:(CDUnknownBlockType)arg5;
+ (void)getUserPanelWithAuthcookie:(id)arg1 roomID:(id)arg2 toUserID:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)userRightsActionWithRoomID:(id)arg1 type:(id)arg2 toUserID:(id)arg3 authcookie:(id)arg4 opType:(id)arg5 completionBlockWithSuccess:(CDUnknownBlockType)arg6;
+ (void)deleteVisitRecordWithAuthcookie:(id)arg1 andRoomIDs:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getHistoryAddWithId:(id)arg1 rid:(id)arg2 aid:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)reportUploadScreenshotWithImage:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)getReportCreateWithId:(id)arg1 param:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getChatNearestHistoryWithId:(id)arg1 rid:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getAccountInfoWithCookie:(id)arg1 moneyTypes:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getDataForShopCenterWithCompletionBlockWithSuccess:(CDUnknownBlockType)arg1;
+ (void)sendStarWithAutocookie:(id)arg1 anchorID:(id)arg2 roomID:(id)arg3 num:(id)arg4 completionBlockWithSuccess:(CDUnknownBlockType)arg5;
+ (void)getGuardGoodListCompletionBlockWithSuccess:(CDUnknownBlockType)arg1;
+ (void)getNobleGoodListCompletionBlockWithSuccess:(CDUnknownBlockType)arg1;
+ (void)getRecommendOtherAnchorsWithNum:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)getRankZongyiListWithId:(id)arg1 num:(id)arg2 type:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)uploadFaceWithId:(id)arg1 image:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3 uploadProgressBlock:(CDUnknownBlockType)arg4;
+ (void)getMyGuardByPage:(id)arg1 pageSize:(id)arg2 userID:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)getFriendshipsMyGuardListWithId:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)getHomeFollowdsWithAuthcookie:(id)arg1 province:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getFriendshipsFollowersWithId:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)destroyFriendshipsWithId:(id)arg1 anchorid:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)createFriendshipsWithUserId:(id)arg1 anchorid:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3 failure:(CDUnknownBlockType)arg4;
+ (void)getFriendshipsIsFollowerWithId:(id)arg1 anchorid:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getAnchorStatWithId:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)getMultiAnchorInfoByUIDs:(id)arg1 andUType:(id)arg2 andFields:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)getUserCenterTotalDataByAuthcookie:(id)arg1 fields:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getUserRolesWithId:(id)arg1 room_id:(id)arg2 completionBlockWithSuccess:(CDUnknownBlockType)arg3;
+ (void)getUserStatWithId:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (void)getUserVisitHistoryWithId:(id)arg1 page:(id)arg2 pageSize:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)getUserInfoWithId:(id)arg1 utype:(id)arg2 fields:(id)arg3 completionBlockWithSuccess:(CDUnknownBlockType)arg4;
+ (void)getUserLoginWithCookie:(id)arg1 completionBlockWithSuccess:(CDUnknownBlockType)arg2;
+ (id)baseParamDictionary;

@end

