//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface QIYIPaopaoUserInfoMTLModel : MTLModel <MTLJSONSerializing>
{
    int _blockAll;
    int _gender;
    int _type;
    int _first_time;
    NSString *_uid;
    NSString *_nickname;
    NSString *_icon;
    double _shutupTime;
    double _shutupTime1;
    NSArray *_shutupWallTimeArray;
    NSNumber *_signRemind;
    long long _wallId;
    long long _identity;
}

+ (id)shutupWallTimeArrayJSONTransformer;
+ (id)JSONKeyPathsByPropertyKey;
@property(nonatomic) long long identity; // @synthesize identity=_identity;
@property(nonatomic) long long wallId; // @synthesize wallId=_wallId;
@property(retain, nonatomic) NSNumber *signRemind; // @synthesize signRemind=_signRemind;
@property(retain, nonatomic) NSArray *shutupWallTimeArray; // @synthesize shutupWallTimeArray=_shutupWallTimeArray;
@property(nonatomic) double shutupTime1; // @synthesize shutupTime1=_shutupTime1;
@property(nonatomic) double shutupTime; // @synthesize shutupTime=_shutupTime;
@property(nonatomic) int first_time; // @synthesize first_time=_first_time;
@property(nonatomic) int type; // @synthesize type=_type;
@property(nonatomic) int gender; // @synthesize gender=_gender;
@property(nonatomic) int blockAll; // @synthesize blockAll=_blockAll;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
@property(retain, nonatomic) NSString *uid; // @synthesize uid=_uid;
- (void).cxx_destruct;

@end

