//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MTLModel.h"

#import "MTLJSONSerializing-Protocol.h"

@class NSString;

@interface QPChatSightModel : MTLModel <MTLJSONSerializing>
{
    NSString *_pic;
    NSString *_fileid;
    NSString *_info;
}

+ (id)JSONKeyPathsByPropertyKey;
@property(copy, nonatomic) NSString *info; // @synthesize info=_info;
@property(copy, nonatomic) NSString *fileid; // @synthesize fileid=_fileid;
@property(copy, nonatomic) NSString *pic; // @synthesize pic=_pic;
- (void).cxx_destruct;

@end

