//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, QPUserModel;

@interface QPUserDataViewModel : NSObject
{
    QPUserModel *_userModel;
    CDUnknownBlockType _didUpdateBlk;
    NSString *_jidStr;
    NSString *_uid;
}

@property(copy, nonatomic) NSString *uid; // @synthesize uid=_uid;
@property(copy, nonatomic) NSString *jidStr; // @synthesize jidStr=_jidStr;
@property(copy, nonatomic) CDUnknownBlockType didUpdateBlk; // @synthesize didUpdateBlk=_didUpdateBlk;
@property(retain, nonatomic) QPUserModel *userModel; // @synthesize userModel=_userModel;
- (void).cxx_destruct;
- (void)didUpdate;
- (id)translateBirth:(id)arg1;
- (void)resetWithModel:(id)arg1;
- (void)updateModelWithCompletion:(CDUnknownBlockType)arg1;
- (id)dict2UserModel:(id)arg1;
- (void)saveUserInfoToLoacal;
- (void)setupModel;
- (id)stringToDate:(id)arg1;
- (id)initWithUid:(id)arg1;

@end

