//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "TabBarDelegate-Protocol.h"

@class CustomTabBarView, NSNumber, NSObject, NSString, QRBookViewerBrightView, QRBookViewerProgressView, QRBookViewerStyleSettingView, QRSlider, QRTouchButton, UIButton, UIImageView, UILabel;
@protocol OS_dispatch_source;

@interface QRBookViewerSettingView : UIView <TabBarDelegate>
{
    _Bool _disableFontSizeAndLineSpace;
    _Bool _bWatch;
    _Bool _bCanGotConsumeWelfare;
    CDUnknownBlockType _backHandler;
    CDUnknownBlockType _sliderHandler;
    CDUnknownBlockType _catalogHandler;
    CDUnknownBlockType _settingHandler;
    CDUnknownBlockType _brightHandler;
    CDUnknownBlockType _niteHandler;
    CDUnknownBlockType _fontChangedHandler;
    CDUnknownBlockType _flipStyleChangedHandler;
    CDUnknownBlockType _colorChangedHandler;
    CDUnknownBlockType _balanceHandler;
    CDUnknownBlockType _showPrevious;
    CDUnknownBlockType _showNext;
    CDUnknownBlockType _autoBytNextOn;
    CDUnknownBlockType _shareHandler;
    CDUnknownBlockType _downloadHandler;
    CDUnknownBlockType _commentHandeler;
    CDUnknownBlockType _giveGiftHandler;
    CDUnknownBlockType _brightChanged;
    CDUnknownBlockType _showFontChoosen;
    CDUnknownBlockType _userTaskHandle;
    CDUnknownBlockType _rewardHandle;
    double _progress;
    long long _pageNum;
    NSNumber *_totalFeeds;
    UIView *_firstLevelSettingViewView;
    UIView *_sepView;
    UIView *_sepViewEx;
    unsigned long long _balanceType;
    NSString *_chapterTitle;
    UIView *_headerView;
    UIView *_firstLevelView;
    UIView *_SlideView;
    QRSlider *_slider;
    QRTouchButton *_balanceBtn;
    QRBookViewerBrightView *_brightView;
    QRBookViewerStyleSettingView *_styleSettingView;
    QRBookViewerProgressView *_progressView;
    QRTouchButton *_shareBtn;
    QRTouchButton *_commentBtn;
    UILabel *_bannerLab;
    QRTouchButton *_downloadBtn;
    QRTouchButton *_moreBtn;
    QRTouchButton *_giveGiftBtn;
    NSObject<OS_dispatch_source> *_timer;
    CustomTabBarView *_mulu;
    CustomTabBarView *_shezhi;
    CustomTabBarView *_liangdu;
    CustomTabBarView *_yejian;
    QRTouchButton *_preBtn;
    QRTouchButton *_nextBtn;
    UIView *_headBottomLine;
    QRTouchButton *_backBtn;
    UIButton *_taskButton;
    UIButton *_RewardBtn;
    UIImageView *_RewardViewLeft;
    UIImageView *_RewardViewRight;
    UIImageView *_tipsView;
    UILabel *_tipsLabel;
}

@property(retain, nonatomic) UILabel *tipsLabel; // @synthesize tipsLabel=_tipsLabel;
@property(retain, nonatomic) UIImageView *tipsView; // @synthesize tipsView=_tipsView;
@property(nonatomic) _Bool bCanGotConsumeWelfare; // @synthesize bCanGotConsumeWelfare=_bCanGotConsumeWelfare;
@property(nonatomic) _Bool bWatch; // @synthesize bWatch=_bWatch;
@property(retain, nonatomic) UIImageView *RewardViewRight; // @synthesize RewardViewRight=_RewardViewRight;
@property(retain, nonatomic) UIImageView *RewardViewLeft; // @synthesize RewardViewLeft=_RewardViewLeft;
@property(retain, nonatomic) UIButton *RewardBtn; // @synthesize RewardBtn=_RewardBtn;
@property(retain, nonatomic) UIButton *taskButton; // @synthesize taskButton=_taskButton;
@property(retain, nonatomic) QRTouchButton *backBtn; // @synthesize backBtn=_backBtn;
@property(retain, nonatomic) UIView *headBottomLine; // @synthesize headBottomLine=_headBottomLine;
@property(retain, nonatomic) QRTouchButton *nextBtn; // @synthesize nextBtn=_nextBtn;
@property(retain, nonatomic) QRTouchButton *preBtn; // @synthesize preBtn=_preBtn;
@property(retain, nonatomic) CustomTabBarView *yejian; // @synthesize yejian=_yejian;
@property(retain, nonatomic) CustomTabBarView *liangdu; // @synthesize liangdu=_liangdu;
@property(retain, nonatomic) CustomTabBarView *shezhi; // @synthesize shezhi=_shezhi;
@property(retain, nonatomic) CustomTabBarView *mulu; // @synthesize mulu=_mulu;
@property(copy, nonatomic) NSObject<OS_dispatch_source> *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) QRTouchButton *giveGiftBtn; // @synthesize giveGiftBtn=_giveGiftBtn;
@property(retain, nonatomic) QRTouchButton *moreBtn; // @synthesize moreBtn=_moreBtn;
@property(retain, nonatomic) QRTouchButton *downloadBtn; // @synthesize downloadBtn=_downloadBtn;
@property(retain, nonatomic) UILabel *bannerLab; // @synthesize bannerLab=_bannerLab;
@property(retain, nonatomic) QRTouchButton *commentBtn; // @synthesize commentBtn=_commentBtn;
@property(retain, nonatomic) QRTouchButton *shareBtn; // @synthesize shareBtn=_shareBtn;
@property(retain, nonatomic) QRBookViewerProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) QRBookViewerStyleSettingView *styleSettingView; // @synthesize styleSettingView=_styleSettingView;
@property(retain, nonatomic) QRBookViewerBrightView *brightView; // @synthesize brightView=_brightView;
@property(retain, nonatomic) QRTouchButton *balanceBtn; // @synthesize balanceBtn=_balanceBtn;
@property(retain, nonatomic) QRSlider *slider; // @synthesize slider=_slider;
@property(retain, nonatomic) UIView *SlideView; // @synthesize SlideView=_SlideView;
@property(retain, nonatomic) UIView *firstLevelView; // @synthesize firstLevelView=_firstLevelView;
@property(retain, nonatomic) UIView *headerView; // @synthesize headerView=_headerView;
@property(copy, nonatomic) NSString *chapterTitle; // @synthesize chapterTitle=_chapterTitle;
@property(nonatomic) unsigned long long balanceType; // @synthesize balanceType=_balanceType;
@property(nonatomic) _Bool disableFontSizeAndLineSpace; // @synthesize disableFontSizeAndLineSpace=_disableFontSizeAndLineSpace;
@property(retain, nonatomic) UIView *sepViewEx; // @synthesize sepViewEx=_sepViewEx;
@property(retain, nonatomic) UIView *sepView; // @synthesize sepView=_sepView;
@property(retain, nonatomic) UIView *firstLevelSettingViewView; // @synthesize firstLevelSettingViewView=_firstLevelSettingViewView;
@property(retain, nonatomic) NSNumber *totalFeeds; // @synthesize totalFeeds=_totalFeeds;
@property(nonatomic) long long pageNum; // @synthesize pageNum=_pageNum;
@property(nonatomic) double progress; // @synthesize progress=_progress;
@property(copy, nonatomic) CDUnknownBlockType rewardHandle; // @synthesize rewardHandle=_rewardHandle;
@property(copy, nonatomic) CDUnknownBlockType userTaskHandle; // @synthesize userTaskHandle=_userTaskHandle;
@property(copy, nonatomic) CDUnknownBlockType showFontChoosen; // @synthesize showFontChoosen=_showFontChoosen;
@property(copy, nonatomic) CDUnknownBlockType brightChanged; // @synthesize brightChanged=_brightChanged;
@property(copy, nonatomic) CDUnknownBlockType giveGiftHandler; // @synthesize giveGiftHandler=_giveGiftHandler;
@property(copy, nonatomic) CDUnknownBlockType commentHandeler; // @synthesize commentHandeler=_commentHandeler;
@property(copy, nonatomic) CDUnknownBlockType downloadHandler; // @synthesize downloadHandler=_downloadHandler;
@property(copy, nonatomic) CDUnknownBlockType shareHandler; // @synthesize shareHandler=_shareHandler;
@property(copy, nonatomic) CDUnknownBlockType autoBytNextOn; // @synthesize autoBytNextOn=_autoBytNextOn;
@property(copy, nonatomic) CDUnknownBlockType showNext; // @synthesize showNext=_showNext;
@property(copy, nonatomic) CDUnknownBlockType showPrevious; // @synthesize showPrevious=_showPrevious;
@property(copy, nonatomic) CDUnknownBlockType balanceHandler; // @synthesize balanceHandler=_balanceHandler;
@property(copy, nonatomic) CDUnknownBlockType colorChangedHandler; // @synthesize colorChangedHandler=_colorChangedHandler;
@property(copy, nonatomic) CDUnknownBlockType flipStyleChangedHandler; // @synthesize flipStyleChangedHandler=_flipStyleChangedHandler;
@property(copy, nonatomic) CDUnknownBlockType fontChangedHandler; // @synthesize fontChangedHandler=_fontChangedHandler;
@property(copy, nonatomic) CDUnknownBlockType niteHandler; // @synthesize niteHandler=_niteHandler;
@property(copy, nonatomic) CDUnknownBlockType brightHandler; // @synthesize brightHandler=_brightHandler;
@property(copy, nonatomic) CDUnknownBlockType settingHandler; // @synthesize settingHandler=_settingHandler;
@property(copy, nonatomic) CDUnknownBlockType catalogHandler; // @synthesize catalogHandler=_catalogHandler;
@property(copy, nonatomic) CDUnknownBlockType sliderHandler; // @synthesize sliderHandler=_sliderHandler;
@property(copy, nonatomic) CDUnknownBlockType backHandler; // @synthesize backHandler=_backHandler;
- (void).cxx_destruct;
- (_Bool)isClickInBlank:(struct CGPoint)arg1;
- (void)rewardClicked:(id)arg1;
- (void)taskButtonClicked:(id)arg1;
- (void)showSlideView:(id)arg1;
- (void)giveGiftClicked:(id)arg1;
- (void)downloadClicked:(id)arg1;
- (void)commentBtnClicked:(id)arg1;
- (void)shareInViewer:(id)arg1;
- (void)showNext:(id)arg1;
- (void)showPrevious:(id)arg1;
- (void)showBrightView;
- (void)showStyleView;
- (void)tabBarClick:(id)arg1;
- (void)buyBalance:(id)arg1;
- (void)backHandle:(id)arg1;
- (void)sliderChanged:(id)arg1;
- (void)refreshInterface;
- (id)firstLevelSettingView;
- (void)setBorderWithView:(id)arg1 top:(_Bool)arg2 left:(_Bool)arg3 bottom:(_Bool)arg4 right:(_Bool)arg5 borderColor:(id)arg6 borderWidth:(double)arg7;
- (id)slideView;
- (void)enableSlide:(_Bool)arg1;
- (void)hideOthersForNoData:(_Bool)arg1;
- (void)setHasBalance:(unsigned long long)arg1;
- (void)createBannerLab;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

