//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class QRBaseModel, QRColorBorderButton, UIImageView, UILabel, UIView;

@interface QRBookItemView3 : UIControl
{
    _Bool _isShowLine;
    long long _bookType;
    UIImageView *_bookImageView;
    UIImageView *_bookFreeView;
    UIImageView *_bookRankView;
    UILabel *_bookNumberRankLabel;
    UILabel *_bookNameLabel;
    UILabel *_bookDesLabel;
    UIImageView *_bookAuthorView;
    UILabel *_bookAuthorLabel;
    UILabel *_bookBuyoutLabel;
    QRColorBorderButton *_bookCateBtn;
    QRBaseModel *_data;
    UIView *_line;
}

@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) QRBaseModel *data; // @synthesize data=_data;
@property(retain, nonatomic) QRColorBorderButton *bookCateBtn; // @synthesize bookCateBtn=_bookCateBtn;
@property(retain, nonatomic) UILabel *bookBuyoutLabel; // @synthesize bookBuyoutLabel=_bookBuyoutLabel;
@property(retain, nonatomic) UILabel *bookAuthorLabel; // @synthesize bookAuthorLabel=_bookAuthorLabel;
@property(retain, nonatomic) UIImageView *bookAuthorView; // @synthesize bookAuthorView=_bookAuthorView;
@property(retain, nonatomic) UILabel *bookDesLabel; // @synthesize bookDesLabel=_bookDesLabel;
@property(retain, nonatomic) UILabel *bookNameLabel; // @synthesize bookNameLabel=_bookNameLabel;
@property(retain, nonatomic) UILabel *bookNumberRankLabel; // @synthesize bookNumberRankLabel=_bookNumberRankLabel;
@property(retain, nonatomic) UIImageView *bookRankView; // @synthesize bookRankView=_bookRankView;
@property(retain, nonatomic) UIImageView *bookFreeView; // @synthesize bookFreeView=_bookFreeView;
@property(retain, nonatomic) UIImageView *bookImageView; // @synthesize bookImageView=_bookImageView;
@property(nonatomic) long long bookType; // @synthesize bookType=_bookType;
@property(nonatomic) _Bool isShowLine; // @synthesize isShowLine=_isShowLine;
- (void).cxx_destruct;
- (void)showRank:(long long)arg1;
- (void)itemClick:(id)arg1;
- (void)loadData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

