//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QRSegmentedCardlyViewController.h"

#import "QRDriftViewControllerProtocol-Protocol.h"

@class NSString, QRJingXuanSearchView, UIView;

@interface QRJingXuanViewController : QRSegmentedCardlyViewController <QRDriftViewControllerProtocol>
{
    UIView *_headerViewBottomLine;
    QRJingXuanSearchView *_searchView;
}

@property(retain, nonatomic) QRJingXuanSearchView *searchView; // @synthesize searchView=_searchView;
@property(retain, nonatomic) UIView *headerViewBottomLine; // @synthesize headerViewBottomLine=_headerViewBottomLine;
- (void).cxx_destruct;
- (void)backHandle:(id)arg1;
- (void)addSearchView;
- (void)addSearchButton;
- (void)addTitle:(id)arg1;
- (void)addHeaderView;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

