//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class QRBaseModel, QRBookItemView3, UIView;

@interface QRRankListCell : UITableViewCell
{
    QRBookItemView3 *_bookItem;
    QRBaseModel *_data;
    UIView *_titleHeader;
}

+ (double)getCardH;
@property(retain, nonatomic) UIView *titleHeader; // @synthesize titleHeader=_titleHeader;
@property(retain, nonatomic) QRBaseModel *data; // @synthesize data=_data;
@property(retain, nonatomic) QRBookItemView3 *bookItem; // @synthesize bookItem=_bookItem;
- (void).cxx_destruct;
- (void)setIsLast:(_Bool)arg1;
- (void)routerEventWithName:(id)arg1 data:(id)arg2;
- (void)showRank:(long long)arg1;
- (void)loadData:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

