//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class QRBookModel, UIImageView, UILabel, UILongPressGestureRecognizer, UITapGestureRecognizer;

@interface QRShujiaBookItem : UIView
{
    _Bool _isEdit;
    UIImageView *_bgImageView;
    UIImageView *_bookImageView;
    UIImageView *_bookUpdateStatusView;
    UILabel *_bookReadProgressLabel;
    UIImageView *_bookSelectView;
    UIView *_labelBg;
    UILabel *_bookTitleLabel;
    UILabel *_addBookHintLabel;
    UITapGestureRecognizer *_tapPress;
    UILongPressGestureRecognizer *_longPress;
    QRBookModel *_data;
}

@property(nonatomic) _Bool isEdit; // @synthesize isEdit=_isEdit;
@property(retain, nonatomic) QRBookModel *data; // @synthesize data=_data;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPress; // @synthesize longPress=_longPress;
@property(retain, nonatomic) UITapGestureRecognizer *tapPress; // @synthesize tapPress=_tapPress;
@property(retain, nonatomic) UILabel *addBookHintLabel; // @synthesize addBookHintLabel=_addBookHintLabel;
@property(retain, nonatomic) UILabel *bookTitleLabel; // @synthesize bookTitleLabel=_bookTitleLabel;
@property(retain, nonatomic) UIView *labelBg; // @synthesize labelBg=_labelBg;
@property(retain, nonatomic) UIImageView *bookSelectView; // @synthesize bookSelectView=_bookSelectView;
@property(retain, nonatomic) UILabel *bookReadProgressLabel; // @synthesize bookReadProgressLabel=_bookReadProgressLabel;
@property(retain, nonatomic) UIImageView *bookUpdateStatusView; // @synthesize bookUpdateStatusView=_bookUpdateStatusView;
@property(retain, nonatomic) UIImageView *bookImageView; // @synthesize bookImageView=_bookImageView;
@property(retain, nonatomic) UIImageView *bgImageView; // @synthesize bgImageView=_bgImageView;
- (void).cxx_destruct;
- (void)itemTouchedLong:(id)arg1;
- (void)itemClick:(id)arg1;
- (void)resetItemInfo:(id)arg1;
- (void)cleanItemInfo;
- (id)initWithFrame:(struct CGRect)arg1;

@end

