//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QXCardSplitManager : NSObject
{
}

+ (id)splitWithCardDataClass:(Class)arg1 dict:(id)arg2 count:(long long)arg3;

@end

