//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QXChatMsgObjectConverter : NSObject
{
}

+ (id)imageWithEmotionName:(id)arg1;
+ (id)imageUrlForVipLevel:(id)arg1;
+ (id)imageUrlForBadgeLevel:(id)arg1;
+ (id)imageUrlForGuardLevel:(id)arg1;
+ (id)nickNameColorWithBadgeLevel:(id)arg1 guardLevel:(id)arg2;
+ (void)getImageRangeTI:(id)arg1;
+ (id)attributedStringWithContent:(id)arg1 color:(id)arg2;
+ (id)reconnectMsg:(id)arg1;
+ (id)publicNoticeMsg:(id)arg1 color:(id)arg2;
+ (id)useGuardOrBadgeMsg:(id)arg1;
+ (id)anchorRankingSoonMsg:(id)arg1;
+ (id)publicChatMsg:(id)arg1;
+ (id)grabLuckyMoneyMsg:(id)arg1;
+ (id)luckyMoneySysMsg:(id)arg1;
+ (id)sendNoviceGiftMsg:(id)arg1;
+ (id)sendGiftMsg:(id)arg1;
+ (id)lianMaiMsg:(id)arg1;
+ (id)sendStarMsg:(id)arg1;
+ (id)followMsg:(id)arg1;
+ (id)operationMsg:(id)arg1;
+ (id)convertFrom:(id)arg1;

@end

