//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, UIFont;

@interface QXContributionSegmentItem : NSObject
{
    NSString *_title;
    UIFont *_font;
    double _itemWidth;
    double _lineWidth;
    double _itemX;
    double _lineX;
    double _lineMaxX;
}

+ (id)itemWithTitle:(id)arg1;
@property(nonatomic) double lineMaxX; // @synthesize lineMaxX=_lineMaxX;
@property(nonatomic) double lineX; // @synthesize lineX=_lineX;
@property(nonatomic) double itemX; // @synthesize itemX=_itemX;
@property(nonatomic) double lineWidth; // @synthesize lineWidth=_lineWidth;
@property(nonatomic) double itemWidth; // @synthesize itemWidth=_itemWidth;
@property(nonatomic) UIFont *font; // @synthesize font=_font;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)init;

@end

