//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface QXEmptyOrUnloginMessageView : UIView
{
    CDUnknownBlockType _clickedBlock;
    UIImageView *_imgView;
    UILabel *_label1;
}

@property(retain, nonatomic) UILabel *label1; // @synthesize label1=_label1;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView=_imgView;
@property(copy, nonatomic) CDUnknownBlockType clickedBlock; // @synthesize clickedBlock=_clickedBlock;
- (void).cxx_destruct;
- (void)clicked:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)setText:(id)arg1;
- (void)setIcon:(id)arg1;

@end

