//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QiXiuBaseVC.h"

@class NSDictionary, NSString, QXRCTViewController, QXRefreshHeader, UIScrollView;

@interface QXRNContainerVC : QiXiuBaseVC
{
    _Bool _needRefreshHeader;
    NSString *_rnRpage;
    NSDictionary *_params;
    QXRCTViewController *_rnVC;
    QXRefreshHeader *_refreshHeader;
    UIScrollView *_scrollView;
}

@property(nonatomic) __weak UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) QXRefreshHeader *refreshHeader; // @synthesize refreshHeader=_refreshHeader;
@property(retain, nonatomic) QXRCTViewController *rnVC; // @synthesize rnVC=_rnVC;
@property(nonatomic) _Bool needRefreshHeader; // @synthesize needRefreshHeader=_needRefreshHeader;
@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(retain, nonatomic) NSString *rnRpage; // @synthesize rnRpage=_rnRpage;
- (void).cxx_destruct;
- (void)dealloc;
- (id)rpage;
- (void)refreshHeaderDidTriggerRefresh:(id)arg1;
- (id)getScrollViewFromSubview:(id)arg1;
- (void)addRefreshHeader;
- (void)componentDidUpdate;
- (void)viewDidLoad;
- (void)viewWillAppear:(_Bool)arg1;
- (void)buyCarSucceed:(id)arg1;
- (void)loginCompleted:(id)arg1;
- (id)init;

@end

