//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class MPVolumeView, UIView;

@interface QYAirPlayDetector : NSObject
{
    MPVolumeView *volumeButton;
    UIView *airplayButton;
    _Bool isAirPlayAvailable;
    struct CGPoint _centerBottomPoint;
}

+ (void)windowBecomeKeywidow:(id)arg1;
+ (id)defaultDetector;
+ (void)load;
@property(nonatomic) struct CGPoint centerBottomPoint; // @synthesize centerBottomPoint=_centerBottomPoint;
- (void)showAirplayDevicesList;
- (void)changeMyAirPlayPoint;
- (void)updateAirPlayeSheetListFrame;
- (void)dealloc;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)startMonitoring:(id)arg1;
- (void)startMonitoring;
@property(readonly, nonatomic) _Bool isAirPlayAvailable;

@end

