//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class QYApmList;
@protocol OS_dispatch_queue;

@interface QYApmViewControllerTracer : NSObject
{
    NSObject<OS_dispatch_queue> *viewControllerTraceQueue;
    QYApmList *_tracedViewControllers;
}

+ (id)sharedInstance;
@property(retain, nonatomic) QYApmList *tracedViewControllers; // @synthesize tracedViewControllers=_tracedViewControllers;
- (void).cxx_destruct;
- (void)dealloc;
- (void)appWillEnterForeground:(id)arg1;
- (void)appDidEnterBackground:(id)arg1;
- (id)viewControllers;
- (void)traceViewController:(id)arg1;
- (id)init;

@end

