//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSMutableDictionary;
@protocol OS_dispatch_queue;

@interface QYBaiduBIManager : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    NSMutableDictionary *_allInfo;
    NSDate *_lastSendDate;
}

+ (id)sharedInstance;
@property(retain) NSDate *lastSendDate; // @synthesize lastSendDate=_lastSendDate;
@property(retain, nonatomic) NSMutableDictionary *allInfo; // @synthesize allInfo=_allInfo;
- (void).cxx_destruct;
- (id)fetchSSIDInfo;
- (id)installedApps;
- (void)start;
- (id)init;

@end

