//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYAdsModel.h"

@class NSString;

@interface QYCommonOverlayModel : QYAdsModel
{
    _Bool _isCloseable;
    _Bool _needAdBadge;
    NSString *_companionCreativeUrl;
    double _xScale;
    double _yScale;
    double _maxWidthScale;
    double _maxHeightScale;
    long long _width;
    long long _height;
    NSString *_appleId;
    NSString *_appName;
    NSString *_appIcon;
    long long _duration;
}

+ (id)modelWithDictionary:(id)arg1;
@property(nonatomic) long long duration; // @synthesize duration=_duration;
@property(retain, nonatomic) NSString *appIcon; // @synthesize appIcon=_appIcon;
@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *appleId; // @synthesize appleId=_appleId;
@property(nonatomic) _Bool needAdBadge; // @synthesize needAdBadge=_needAdBadge;
@property(nonatomic) long long height; // @synthesize height=_height;
@property(nonatomic) long long width; // @synthesize width=_width;
@property(nonatomic) double maxHeightScale; // @synthesize maxHeightScale=_maxHeightScale;
@property(nonatomic) double maxWidthScale; // @synthesize maxWidthScale=_maxWidthScale;
@property(nonatomic) double yScale; // @synthesize yScale=_yScale;
@property(nonatomic) double xScale; // @synthesize xScale=_xScale;
@property(nonatomic) _Bool isCloseable; // @synthesize isCloseable=_isCloseable;
@property(retain, nonatomic) NSString *companionCreativeUrl; // @synthesize companionCreativeUrl=_companionCreativeUrl;
- (void).cxx_destruct;
- (struct CGRect)getAdFrameBasedPlayerFrame:(struct CGRect)arg1;

@end

