//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "QYEModuleProtocol-Protocol.h"

@class NSString;

@interface QYGLLaunchEngine : NSObject <QYEModuleProtocol>
{
}

+ (id)getInitalPropertiesWithParam:(id)arg1;
+ (void)checkFlieProtection:(id)arg1;
+ (void)redirectNSlogToDocumentFolder;
+ (void)dismissGameliveController:(id)arg1;
+ (void)pushCustomController:(id)arg1 parentController:(id)arg2 closeBlock:(CDUnknownBlockType)arg3;
+ (void)pushController:(id)arg1 parentController:(id)arg2 closeBlock:(CDUnknownBlockType)arg3;
+ (void)gotoGameliveHomepage;
+ (void)gotoGameliveRoomWithParams:(id)arg1 parentController:(id)arg2 closeBlock:(CDUnknownBlockType)arg3;
+ (void)gotoGameliveHomepageWithParams:(id)arg1 parentController:(id)arg2 closeBlock:(CDUnknownBlockType)arg3;
+ (id)parseFetchParams:(id)arg1;
+ (void)handlerLaunchEnginWithParam:(id)arg1;
+ (_Bool)networkError;
+ (id)moduleInfoWithParam:(id)arg1;
+ (void)launchWithParam:(id)arg1;
+ (void)load;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

