//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface QYMCinemaServiceCellView : UIView
{
    UIImageView *_serviceIcon;
    UILabel *_serviceDesc;
    UIView *_line;
    UIImageView *_arrowIcon;
}

@property(retain, nonatomic) UIImageView *arrowIcon; // @synthesize arrowIcon=_arrowIcon;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) UILabel *serviceDesc; // @synthesize serviceDesc=_serviceDesc;
@property(retain, nonatomic) UIImageView *serviceIcon; // @synthesize serviceIcon=_serviceIcon;
- (void).cxx_destruct;
- (void)layoutServiceDescriptionString:(id)arg1 withLineSpacing:(double)arg2;
- (void)layoutCinemaBriefCellView:(id)arg1 withOriginY:(double)arg2;
- (void)layoutCinemaServiceCellView:(id)arg1 withOriginY:(double)arg2 withIcon:(id)arg3;
- (void)layoutCinemaServiceCellView:(id)arg1 withOriginY:(double)arg2 withIcon:(id)arg3 showArrow:(_Bool)arg4;
- (id)initWithFrame:(struct CGRect)arg1;

@end

