//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class QYCinemaMovieClipData, QYCinemaSessionData;

@interface QYMGetMovieCardData : NSObject
{
    QYCinemaSessionData *_movieInfo;
    QYCinemaMovieClipData *_clips;
}

@property(retain, nonatomic) QYCinemaMovieClipData *clips; // @synthesize clips=_clips;
@property(retain, nonatomic) QYCinemaSessionData *movieInfo; // @synthesize movieInfo=_movieInfo;
- (void).cxx_destruct;
- (void)buildWithDictionary:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

