//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UILabel;

@interface QYMOrderDetailServiceView : UIView
{
    UILabel *_serviceTitle;
    UILabel *_serviceTime;
    UILabel *_serviceTel;
}

@property(retain, nonatomic) UILabel *serviceTel; // @synthesize serviceTel=_serviceTel;
@property(retain, nonatomic) UILabel *serviceTime; // @synthesize serviceTime=_serviceTime;
@property(retain, nonatomic) UILabel *serviceTitle; // @synthesize serviceTitle=_serviceTitle;
- (void).cxx_destruct;
- (void)serviceViewAction;
- (void)layoutOrderDetailServiceView;
- (id)creatLabelWithFont:(id)arg1 withTextColor:(id)arg2;
- (void)initOrderDetailServiceView;
- (id)initWithFrame:(struct CGRect)arg1;

@end

