//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSString;

@protocol QYOfflineACOSchemeViewDelegate <NSObject>

@optional
- (void)offlineACOViewDelegateVideo:(long long)arg1 withVideoNum:(long long)arg2;
- (void)offlineACOViewIsUserBackBtn:(_Bool)arg1;
- (void)offlineACOViewManageEditBtn:(int)arg1;
- (void)offlineACOViewOpenFolderWithOperateId:(NSString *)arg1 Title:(NSString *)arg2;
@end

