//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SPActivityIndicatorView;

@interface QYPlayerLoadingView : UIView
{
    SPActivityIndicatorView *indicatorView;
}

- (void).cxx_destruct;
- (struct CGSize)intrinsicContentSize;
- (void)setHidden:(_Bool)arg1;
- (void)commonInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

