//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "IQYDataLoadManagerDelegate-Protocol.h"

@class NSDictionary, NSMutableDictionary, NSString, NSTimer, QYPlayerVideoForwardButton, QYPlayerVideoForwardView, UIImageView, UIView;
@protocol OS_dispatch_queue, QYPlayerVideoForwardControllerDelegate;

@interface QYPlayerVideoForwardController : NSObject <IQYDataLoadManagerDelegate>
{
    long long cols;
    long long rows;
    long long cutImgInterval;
    double perImgInterval;
    double defaultCutImgInterval;
    long long startForwardTime;
    long long endForwardTime;
    _Bool _isOpenForward;
    _Bool _isSetBtnModeCancel;
    _Bool _isFirstDownload;
    _Bool _isFirstLoadData;
    _Bool _isForwarding;
    _Bool _isPauseForward;
    _Bool _shouldHidden;
    int _forwardBtnMode;
    int _screenMode;
    int _progressFind;
    double _durationTime;
    long long _currentTime;
    UIView *_superContentView;
    UIImageView *_videoForwardView;
    long long _curIndex;
    long long _imgCutIndex;
    long long _imgCutMax;
    long long _curIndexShowCount;
    long long _startShowImgIndex;
    long long _endShowImgIndex;
    long long _forwardBtnLeftTime;
    id <QYPlayerVideoForwardControllerDelegate> _delegate;
    NSDictionary *_forwradDic;
    NSMutableDictionary *_downloadQueueDic;
    NSString *_picUrl;
    NSTimer *_forwardTimer;
    NSObject<OS_dispatch_queue> *_downloadImgQueue;
    QYPlayerVideoForwardButton *_forwardStateBtn;
    QYPlayerVideoForwardView *_forwardProgressBar;
    long long _retryTime;
    long long _loadRetryTime;
    long long _curDownloadIndex;
    double _curScale;
}

+ (void)showForwardNeedViewToSuperView:(id)arg1 bySubView:(id)arg2 needRemove:(_Bool)arg3;
+ (id)getForwardNeedView;
+ (void)hideForwardNeedViewToSuperView:(id)arg1;
+ (void)showForwardAlertViewToSuperView:(id)arg1;
+ (id)getCutImgDirByName:(id)arg1;
+ (id)getCutImgPath;
@property(nonatomic) double curScale; // @synthesize curScale=_curScale;
@property(nonatomic) int progressFind; // @synthesize progressFind=_progressFind;
@property(nonatomic) long long curDownloadIndex; // @synthesize curDownloadIndex=_curDownloadIndex;
@property(nonatomic) long long loadRetryTime; // @synthesize loadRetryTime=_loadRetryTime;
@property(nonatomic) long long retryTime; // @synthesize retryTime=_retryTime;
@property(nonatomic) _Bool shouldHidden; // @synthesize shouldHidden=_shouldHidden;
@property(nonatomic) int screenMode; // @synthesize screenMode=_screenMode;
@property(retain, nonatomic) QYPlayerVideoForwardView *forwardProgressBar; // @synthesize forwardProgressBar=_forwardProgressBar;
@property(retain, nonatomic) QYPlayerVideoForwardButton *forwardStateBtn; // @synthesize forwardStateBtn=_forwardStateBtn;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *downloadImgQueue; // @synthesize downloadImgQueue=_downloadImgQueue;
@property(retain, nonatomic) NSTimer *forwardTimer; // @synthesize forwardTimer=_forwardTimer;
@property(retain, nonatomic) NSString *picUrl; // @synthesize picUrl=_picUrl;
@property(retain, nonatomic) NSMutableDictionary *downloadQueueDic; // @synthesize downloadQueueDic=_downloadQueueDic;
@property(retain, nonatomic) NSDictionary *forwradDic; // @synthesize forwradDic=_forwradDic;
@property(nonatomic) __weak id <QYPlayerVideoForwardControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool isPauseForward; // @synthesize isPauseForward=_isPauseForward;
@property(nonatomic) _Bool isForwarding; // @synthesize isForwarding=_isForwarding;
@property(nonatomic) _Bool isFirstLoadData; // @synthesize isFirstLoadData=_isFirstLoadData;
@property(nonatomic) _Bool isFirstDownload; // @synthesize isFirstDownload=_isFirstDownload;
@property(nonatomic) long long forwardBtnLeftTime; // @synthesize forwardBtnLeftTime=_forwardBtnLeftTime;
@property(nonatomic) int forwardBtnMode; // @synthesize forwardBtnMode=_forwardBtnMode;
@property(nonatomic) long long endShowImgIndex; // @synthesize endShowImgIndex=_endShowImgIndex;
@property(nonatomic) long long startShowImgIndex; // @synthesize startShowImgIndex=_startShowImgIndex;
@property(nonatomic) long long curIndexShowCount; // @synthesize curIndexShowCount=_curIndexShowCount;
@property(nonatomic) long long imgCutMax; // @synthesize imgCutMax=_imgCutMax;
@property(nonatomic) long long imgCutIndex; // @synthesize imgCutIndex=_imgCutIndex;
@property(nonatomic) long long curIndex; // @synthesize curIndex=_curIndex;
@property(retain, nonatomic) UIImageView *videoForwardView; // @synthesize videoForwardView=_videoForwardView;
@property(nonatomic) __weak UIView *superContentView; // @synthesize superContentView=_superContentView;
@property(nonatomic) _Bool isSetBtnModeCancel; // @synthesize isSetBtnModeCancel=_isSetBtnModeCancel;
@property(nonatomic) long long currentTime; // @synthesize currentTime=_currentTime;
@property(nonatomic) double durationTime; // @synthesize durationTime=_durationTime;
@property(nonatomic) _Bool isOpenForward; // @synthesize isOpenForward=_isOpenForward;
- (void).cxx_destruct;
- (void)setForwardViewScale:(float)arg1 isFull:(_Bool)arg2;
- (void)setForwardBtnShouldHidden:(_Bool)arg1;
- (void)updateScreenModeByMode:(int)arg1;
- (void)clickForwardStateBtn;
- (void)handleSeekToTime:(double)arg1;
- (void)isNeedDownloadImgByTime:(long long)arg1;
- (void)checkForNeedLoadNextImgByCurPlayTime:(long long)arg1;
- (void)removeAllCutImg;
- (void)removeCutImgByLargeIndex:(long long)arg1;
- (void)saveLocalImgByName:(id)arg1 dirName:(id)arg2 img:(id)arg3;
- (void)picForwardFinish;
- (void)picForwardStart;
- (void)startPicForward;
- (void)cutOriginImageByImage:(id)arg1 byDir:(id)arg2;
- (void)downloadErrorByUrl:(id)arg1;
- (void)dataLoadManagerFailed:(id)arg1;
- (void)dataLoadManagerFinished:(id)arg1;
- (void)downloadImgByDic:(id)arg1;
- (void)downloadNextPicsByIndex:(long long)arg1 isLastTry:(_Bool)arg2;
- (void)loadNextPics;
- (void)createProgressBar;
- (void)createStateBtn;
- (void)disableForward;
- (void)configDataByDic:(id)arg1 duration:(double)arg2 screenMode:(int)arg3;
- (id)initBySuperView:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

