//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDictionary, NSString, Playershare, QYPlayerViewController, UIImage, UIView, UIViewController;

@protocol QYPlayerViewControllerDelegate <NSObject>

@optional
- (void)vPlayInfoLoadFinished:(NSDictionary *)arg1;
- (NSString *)getCurrentVideoSize;
- (UIImage *)getMessageViewBgImage;
- (void)messageReplay:(QYPlayerViewController *)arg1;
- (NSDictionary *)getShareRegisterInfo;
- (NSString *)getShareTypeFrom;
- (NSDictionary *)getExpandPingBackParameter;
- (void)userSwitchPlay:(_Bool)arg1;
- (_Bool)isFromOutside;
- (void)playerControl:(int)arg1 object:(id)arg2;
- (_Bool)isResponseGesture;
- (Playershare *)getPlayerDataShareData;
- (void)doCancelAutoHideAccessoryViews;
- (void)showPingbackWithBlock:(NSString *)arg1 position:(NSString *)arg2 rpage:(NSString *)arg3;
- (void)showToastWithTxt:(NSString *)arg1;
- (_Bool)isUGC;
- (_Bool)isExistPushed;
- (void)setShouldNotPanCancel:(_Bool)arg1;
- (void)showQiXiu:(NSDictionary *)arg1;
- (void)showRead:(NSDictionary *)arg1;
- (void)updateReadyBuy:(NSArray *)arg1;
- (_Bool)isShowPlayerWebView;
- (void)refreshCommenterHeadPhoto;
- (void)continueDingyueForUCard;
- (void)loginDidFinished:(int)arg1;
- (void)afterAccountViewClosedForZanLucky;
- (void)retryPannelDataForVipPlay;
- (void)quitPushForVIP:(QYPlayerViewController *)arg1;
- (void)PushVideoPurchesSuccess;
- (void)backToChatRoomView;
- (void)reloadChatRoom;
- (NSString *)getSubjectFc;
- (void)setShouldRorate:(_Bool)arg1;
- (void)logEventWithParameterDict:(NSDictionary *)arg1;
- (_Bool)isPushed;
- (void)avAirplayActiveSuccess;
- (void)avQuitAirPlay;
- (void)avQuitQimo;
- (void)enableAirPlayBtn:(_Bool)arg1;
- (void)showAirPlayPushView:(_Bool)arg1 withState:(_Bool)arg2;
- (long long)getCurrentPushTime:(QYPlayerViewController *)arg1;
- (void)keeprecord:(NSString *)arg1;
- (_Bool)isHasPopView;
- (void)epgCallBackWithType:(NSString *)arg1 info:(NSDictionary *)arg2;
- (void)loadVIPDataFailed:(QYPlayerViewController *)arg1 message:(id)arg2;
- (void)loadDataFinshForSecond:(QYPlayerViewController *)arg1;
- (void)loadDataFinsh:(QYPlayerViewController *)arg1;
- (_Bool)isPushVideoPlay:(QYPlayerViewController *)arg1;
- (_Bool)checkIsShowCornerAds;
- (void)reOpenPlayer:(QYPlayerViewController *)arg1;
- (void)loadPipDataFailed;
- (void)loadPipDataFinish:(NSString *)arg1;
- (NSDictionary *)getNextTvidForRecord:(QYPlayerViewController *)arg1 order:(long long)arg2;
- (void)showRecommendEndViewByAlbumId:(NSString *)arg1 categoryId:(long long)arg2;
- (_Bool)isPlayFromReplayBtn;
- (void)retryOpenPlayer;
- (void)updateLocalEpisodeByNetworkChange;
- (void)localPlayerNetworkChange:(QYPlayerViewController *)arg1;
- (_Bool)canPlayer:(QYPlayerViewController *)arg1;
- (_Bool)playFailedForPlayer:(QYPlayerViewController *)arg1 isAirplay:(_Bool)arg2;
- (void)updateStartTimeByPlayer:(long long)arg1;
- (void)playerLoadStateChanged:(QYPlayerViewController *)arg1;
- (void)handlePlayAlert:(QYPlayerViewController *)arg1;
- (void)updatePaopaoGuildViewByAdType:(long long)arg1 startTime:(int)arg2 adTime:(float)arg3;
- (void)contentPlaying:(QYPlayerViewController *)arg1 isPreAdsFinish:(_Bool)arg2 isSwitchResTypeForDanmu:(_Bool)arg3;
- (void)initPlayer:(QYPlayerViewController *)arg1;
- (void)preparedToPlay:(QYPlayerViewController *)arg1;
- (_Bool)autoPlay:(QYPlayerViewController *)arg1;
- (UIViewController *)getPlayContentViewController;
- (UIView *)getPlayContentView;
- (void)doubleClickOnPlayer:(QYPlayerViewController *)arg1;
- (void)clickOnPlayer:(QYPlayerViewController *)arg1;
- (void)playerControlViewPinchScreen;
- (void)hidePlayerAccessoryViews;
- (void)showPlayerAccessoryViews;
- (void)playbackTimeChanged:(QYPlayerViewController *)arg1;
- (void)onContentStartPlay:(QYPlayerViewController *)arg1;
- (void)saveAdClickFV:(NSString *)arg1;
- (void)preWatchNoticeStart:(QYPlayerViewController *)arg1;
- (_Bool)is3GforcePlay:(QYPlayerViewController *)arg1;
- (void)AdplayEnd:(long long)arg1;
- (void)AdPlayBegin:(long long)arg1;
- (void)onPlayStuckWithParam:(long long)arg1;
- (void)onPlayerError:(NSDictionary *)arg1;
- (void)showPlayerMessageViewByType:(int)arg1;
- (void)playerNetworkChanged:(QYPlayerViewController *)arg1;
- (_Bool)shouldShowNextTip;
- (NSDictionary *)updateNextPlayInfo;
- (NSDictionary *)getNextVideoInfo:(QYPlayerViewController *)arg1;
- (void)playbackFinshed:(QYPlayerViewController *)arg1;
- (void)stopActivity:(QYPlayerViewController *)arg1;
- (void)startActivity:(QYPlayerViewController *)arg1;
- (void)stopLoading:(QYPlayerViewController *)arg1;
- (void)startLoading:(QYPlayerViewController *)arg1;
- (void)playerStateChanged:(QYPlayerViewController *)arg1;
- (void)closePlayer:(QYPlayerViewController *)arg1;
@end

