//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PlayerBaseCell4CardStyle.h"

#import "SDWebImageManagerDelegate-Protocol.h"

@class NSString, QiShowAdModel, UIButton, UIImageView, UILabel, UIView;
@protocol QYPlayerQiXiuEnterCellDelegate;

@interface QYPlayerQiXiuEnterCell : PlayerBaseCell4CardStyle <SDWebImageManagerDelegate>
{
    QiShowAdModel *_cellData;
    id <QYPlayerQiXiuEnterCellDelegate> _delegate;
    UIImageView *_logoImageView;
    UILabel *_titleLabel;
    UILabel *_descriptionLabel;
    UIButton *_enterButton;
    UIView *_topLineView;
}

@property(retain, nonatomic) UIView *topLineView; // @synthesize topLineView=_topLineView;
@property(retain, nonatomic) UIButton *enterButton; // @synthesize enterButton=_enterButton;
@property(retain, nonatomic) UILabel *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIImageView *logoImageView; // @synthesize logoImageView=_logoImageView;
@property(nonatomic) __weak id <QYPlayerQiXiuEnterCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) QiShowAdModel *cellData; // @synthesize cellData=_cellData;
- (void).cxx_destruct;
- (void)webImageManager:(id)arg1 didFailWithError:(id)arg2 forURL:(id)arg3;
- (void)webImageManager:(id)arg1 didFinishWithImage:(id)arg2 forURL:(id)arg3 userInfo:(id)arg4;
- (void)loadImage:(id)arg1;
- (void)layoutSubviews;
- (void)enterXiuChang:(id)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 styleInfo:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

