//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYPPPubBaseShootViewController.h"

#import "QYPPAlertViewDelegate-Protocol.h"
#import "QYPPPubCameraSetterDelegate-Protocol.h"
#import "QYPPPubVideoFilterDelegate-Protocol.h"

@class NSString, QYPPAlertView_, QYPPPubCameraSetterView, QYPPPubVideoFilterView, QYPPPubVideoShootHandler, UIButton;

@interface QYPPPubShootCallingVC : QYPPPubBaseShootViewController <QYPPPubCameraSetterDelegate, QYPPPubVideoFilterDelegate, QYPPAlertViewDelegate>
{
    _Bool _defaultStatusbarHidden;
    _Bool _isShooting;
    _Bool _rebuildShootHandleWhenViewAppear;
    CDUnknownBlockType _recordDoneBlock;
    NSString *_movieFilePath;
    NSString *_outputFilePath;
    NSString *_materialId;
    NSString *_materialSource;
    QYPPPubVideoShootHandler *_shootHandler;
    QYPPPubCameraSetterView *_cameraSetterView;
    QYPPPubVideoFilterView *_cameraFilterView;
    UIButton *_cancelBtn;
    QYPPAlertView_ *_returnAlert;
}

@property(nonatomic) _Bool rebuildShootHandleWhenViewAppear; // @synthesize rebuildShootHandleWhenViewAppear=_rebuildShootHandleWhenViewAppear;
@property(retain, nonatomic) QYPPAlertView_ *returnAlert; // @synthesize returnAlert=_returnAlert;
@property(nonatomic) _Bool isShooting; // @synthesize isShooting=_isShooting;
@property(nonatomic) _Bool defaultStatusbarHidden; // @synthesize defaultStatusbarHidden=_defaultStatusbarHidden;
@property(retain, nonatomic) UIButton *cancelBtn; // @synthesize cancelBtn=_cancelBtn;
@property(retain, nonatomic) QYPPPubVideoFilterView *cameraFilterView; // @synthesize cameraFilterView=_cameraFilterView;
@property(retain, nonatomic) QYPPPubCameraSetterView *cameraSetterView; // @synthesize cameraSetterView=_cameraSetterView;
@property(retain, nonatomic) QYPPPubVideoShootHandler *shootHandler; // @synthesize shootHandler=_shootHandler;
@property(copy, nonatomic) NSString *materialSource; // @synthesize materialSource=_materialSource;
@property(copy, nonatomic) NSString *materialId; // @synthesize materialId=_materialId;
@property(copy, nonatomic) NSString *outputFilePath; // @synthesize outputFilePath=_outputFilePath;
@property(copy, nonatomic) NSString *movieFilePath; // @synthesize movieFilePath=_movieFilePath;
@property(copy, nonatomic) CDUnknownBlockType recordDoneBlock; // @synthesize recordDoneBlock=_recordDoneBlock;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)filterView:(id)arg1 didSelectFilterAtIndex:(long long)arg2;
- (void)confirmFilterSelect;
- (void)setFirstFilter:(long long)arg1 withSecondFilter:(long long)arg2 withPercent:(double)arg3;
- (void)openFilterSetter;
- (void)setTorchStatus:(_Bool)arg1;
- (void)setCameraPosition:(_Bool)arg1;
- (id)createReturnAlert;
- (void)stopRecord;
- (void)restartProcess;
- (void)addPrompterView;
- (void)startRecord;
- (void)cancelRecord;
- (void)stopPreview;
- (void)startPreview;
- (void)setupShootHandle;
- (_Bool)commandCancel:(id)arg1;
- (void)removeFromParentViewController;
- (void)applicationWillResignActive;
- (void)applicationDidBecomeActive;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)dealloc;
- (void)commonInit;
- (void)initTestData;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

