//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface QYPPViewControllerNavUtility : NSObject
{
}

+ (void)handleNavToReport:(id)arg1 userId:(id)arg2 wallId:(id)arg3 feedId:(id)arg4 sourceType:(id)arg5 voteId:(id)arg6;
+ (void)handleNavToShortVideoCollectVCDefaultNews:(id)arg1;
+ (void)handleNavToShortVideoCollectVCDefaultHot:(id)arg1;
+ (void)handleNavToGeniusVC:(id)arg1 feedData:(id)arg2;
+ (void)handleNavToPublishUserFeed:(id)arg1 feedData:(id)arg2;
+ (void)handleNavToPublishFromUserCircle:(id)arg1 params:(id)arg2;
+ (void)handleNavToReportFromUserCircle:(id)arg1 userId:(id)arg2 wallId:(id)arg3 feedId:(id)arg4;
+ (void)handleNavToMoreVC:(id)arg1 userId:(id)arg2 joinIn:(_Bool)arg3 roomJidB:(id)arg4;
+ (void)handleNavToUserPrivateSettingVC:(id)arg1;
+ (void)handleNavToFansListVC:(id)arg1 userId:(id)arg2;
+ (void)handleNavToUserCircleVCFromChatroom:(id)arg1 userId:(id)arg2 roomJidB:(id)arg3;
+ (void)handleNavToUserCircleVCAutoJoin:(id)arg1 userId:(id)arg2;
+ (void)handleNavToUserCircleVC:(id)arg1 userId:(id)arg2;
+ (void)handleNavToUserVideoDetailVC:(id)arg1 feedData:(id)arg2 rpage:(id)arg3 rfr:(id)arg4 refreshBlock:(CDUnknownBlockType)arg5 deleteBlock:(CDUnknownBlockType)arg6;
+ (void)pushChatRoomWith:(id)arg1 jidStr:(id)arg2;
+ (void)handleNavToPrivateChatListVC:(id)arg1 userId:(id)arg2;
+ (void)handleNavToUserGroupChatListVC:(id)arg1 userId:(id)arg2;
+ (void)handleNavToMyGroupChatListVC:(id)arg1;
+ (void)handleNavToUserCircleListVC:(id)arg1 userId:(id)arg2;
+ (void)handleNavToVideoCollectionVC:(id)arg1 collectionId:(id)arg2;
+ (void)handleNavToStarCircleCollectionsVC:(id)arg1 wallID:(id)arg2;
+ (void)handleNavToPGCCircleVC:(id)arg1 wallID:(id)arg2 andPGCUid:(id)arg3;
+ (void)handleNavToHotEventVC:(id)arg1 eventId:(id)arg2;
+ (void)handleNavToWelfareActivityDetailVC:(id)arg1 welfareId:(id)arg2;

@end

