//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYPPNetRequest.h"

@interface QYPPHttpManager : QYPPNetRequest
{
}

+ (id)shareManager;
- (void)getFeedsDataRequestWithParameters:(id)arg1 requestUrl:(id)arg2 methodType:(long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)dataRequestOperation:(id)arg1 URLString:(id)arg2 methodType:(long long)arg3;
- (id)commonParameters:(id)arg1;

@end

