//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYPPJsonData.h"

@class NSArray;
@protocol Optional><QYPPStarOwnerFeedsGroupData><ConvertOnDemand;

@interface QYPPStarOwnerFeedsData : QYPPJsonData
{
    NSArray<Optional><QYPPStarOwnerFeedsGroupData><ConvertOnDemand> *_feedByGroup;
}

@property(retain, nonatomic) NSArray<Optional><QYPPStarOwnerFeedsGroupData><ConvertOnDemand> *feedByGroup; // @synthesize feedByGroup=_feedByGroup;
- (void).cxx_destruct;

@end

