//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, QYPPTextStorage;

@interface QYPPTextViewCacheModel : NSObject
{
    QYPPTextStorage *_textStorage;
    NSArray *_emotionArr;
    struct CGSize _textViewSize;
}

@property(retain, nonatomic) NSArray *emotionArr; // @synthesize emotionArr=_emotionArr;
@property(retain, nonatomic) QYPPTextStorage *textStorage; // @synthesize textStorage=_textStorage;
@property(nonatomic) struct CGSize textViewSize; // @synthesize textViewSize=_textViewSize;
- (void).cxx_destruct;

@end

