//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class MASConstraint, NSString, QIYIPaopaoAvatarView, QYPPCircleFeedMTLModel, QYPPCommentModel, QYPPCommentReplyView, QYPPCommentTextView, QYPPCommentUserInfoModel, QYPPFansLevelLabel, QYPPUsernameButton, UIButton, UIImageView, UILabel;
@protocol QYPPFeedCommentTableViewCellProtocol;

@interface QYPPFeedCommentTableViewCell : UITableViewCell
{
    double _cellHeight;
    _Bool _isCircleMaster;
    _Bool _showMaster;
    _Bool _isHotComment;
    QIYIPaopaoAvatarView *_avatarIv;
    UIImageView *_masterIv;
    UIImageView *_verificationIcon;
    UILabel *_timeLbl;
    UIImageView *_locationIv;
    UILabel *_locationLbl;
    UILabel *_floorLbl;
    long long _index;
    QYPPCommentTextView *_commentTextView;
    QYPPCommentModel *_comment;
    CDUnknownBlockType _deleteCommentBlock;
    CDUnknownBlockType _longPressedCommentBlock;
    CDUnknownBlockType _showAllContentBlock;
    CDUnknownBlockType _avatarClickBlk;
    CDUnknownBlockType _favoritePingBackBlk;
    CDUnknownBlockType _clickReplyNameBlk;
    CDUnknownBlockType _clickUserNameBlk;
    QYPPUsernameButton *_publishUsernameBtn;
    id <QYPPFeedCommentTableViewCellProtocol> _delegate;
    QYPPCircleFeedMTLModel *_feedModel;
    NSString *_lastPage;
    QYPPCommentReplyView *_replyView;
    UILabel *_replyNameLabel;
    UIButton *_favBtn;
    UILabel *_favNumLbl;
    QYPPFansLevelLabel *_fansLevelView;
    QYPPCommentUserInfoModel *_starInfoModel;
    CDUnknownBlockType _didClickLikeBtnBlk;
    MASConstraint *_timeLabelToLeftConstraint;
    UIImageView *_administratorMark;
    UIButton *_btnAllContent;
}

@property(nonatomic) _Bool isHotComment; // @synthesize isHotComment=_isHotComment;
@property(retain, nonatomic) UIButton *btnAllContent; // @synthesize btnAllContent=_btnAllContent;
@property(retain, nonatomic) UIImageView *administratorMark; // @synthesize administratorMark=_administratorMark;
@property(retain, nonatomic) MASConstraint *timeLabelToLeftConstraint; // @synthesize timeLabelToLeftConstraint=_timeLabelToLeftConstraint;
@property(copy, nonatomic) CDUnknownBlockType didClickLikeBtnBlk; // @synthesize didClickLikeBtnBlk=_didClickLikeBtnBlk;
@property(retain, nonatomic) QYPPCommentUserInfoModel *starInfoModel; // @synthesize starInfoModel=_starInfoModel;
@property(readonly, nonatomic) QYPPFansLevelLabel *fansLevelView; // @synthesize fansLevelView=_fansLevelView;
@property(retain, nonatomic) UILabel *favNumLbl; // @synthesize favNumLbl=_favNumLbl;
@property(retain, nonatomic) UIButton *favBtn; // @synthesize favBtn=_favBtn;
@property(nonatomic) _Bool showMaster; // @synthesize showMaster=_showMaster;
@property(readonly, nonatomic) UILabel *replyNameLabel; // @synthesize replyNameLabel=_replyNameLabel;
@property(readonly, nonatomic) QYPPCommentReplyView *replyView; // @synthesize replyView=_replyView;
@property(retain, nonatomic) NSString *lastPage; // @synthesize lastPage=_lastPage;
@property(retain, nonatomic) QYPPCircleFeedMTLModel *feedModel; // @synthesize feedModel=_feedModel;
@property(nonatomic) __weak id <QYPPFeedCommentTableViewCellProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) QYPPUsernameButton *publishUsernameBtn; // @synthesize publishUsernameBtn=_publishUsernameBtn;
@property(nonatomic) _Bool isCircleMaster; // @synthesize isCircleMaster=_isCircleMaster;
@property(copy, nonatomic) CDUnknownBlockType clickUserNameBlk; // @synthesize clickUserNameBlk=_clickUserNameBlk;
@property(copy, nonatomic) CDUnknownBlockType clickReplyNameBlk; // @synthesize clickReplyNameBlk=_clickReplyNameBlk;
@property(copy, nonatomic) CDUnknownBlockType favoritePingBackBlk; // @synthesize favoritePingBackBlk=_favoritePingBackBlk;
@property(copy, nonatomic) CDUnknownBlockType avatarClickBlk; // @synthesize avatarClickBlk=_avatarClickBlk;
@property(copy, nonatomic) CDUnknownBlockType showAllContentBlock; // @synthesize showAllContentBlock=_showAllContentBlock;
@property(copy, nonatomic) CDUnknownBlockType longPressedCommentBlock; // @synthesize longPressedCommentBlock=_longPressedCommentBlock;
@property(copy, nonatomic) CDUnknownBlockType deleteCommentBlock; // @synthesize deleteCommentBlock=_deleteCommentBlock;
@property(retain, nonatomic) QYPPCommentModel *comment; // @synthesize comment=_comment;
@property(retain, nonatomic) QYPPCommentTextView *commentTextView; // @synthesize commentTextView=_commentTextView;
@property(nonatomic) long long index; // @synthesize index=_index;
@property(retain, nonatomic) UILabel *floorLbl; // @synthesize floorLbl=_floorLbl;
@property(retain, nonatomic) UILabel *locationLbl; // @synthesize locationLbl=_locationLbl;
@property(retain, nonatomic) UIImageView *locationIv; // @synthesize locationIv=_locationIv;
@property(retain, nonatomic) UILabel *timeLbl; // @synthesize timeLbl=_timeLbl;
@property(retain, nonatomic) UIImageView *verificationIcon; // @synthesize verificationIcon=_verificationIcon;
@property(retain, nonatomic) UIImageView *masterIv; // @synthesize masterIv=_masterIv;
@property(retain, nonatomic) QIYIPaopaoAvatarView *avatarIv; // @synthesize avatarIv=_avatarIv;
- (void).cxx_destruct;
- (void)handleDisFavouriteFailedWithMessage:(id)arg1;
- (void)handleDisFavouriteSuccess;
- (void)handleFavouriteFailedWithMessage:(id)arg1;
- (void)handleFavouriteSuccess;
- (void)showAllContent:(id)arg1;
- (void)pingbackWithTypeForClickFav:(unsigned long long)arg1;
- (void)commentFavAction:(id)arg1;
- (void)showFloorNumber:(long long)arg1;
- (void)setCommentUserame:(id)arg1 replyedUsername:(id)arg2;
- (void)setCircleAdministratorMark:(_Bool)arg1;
- (void)showVerification:(_Bool)arg1;
- (void)longPressed:(id)arg1;
- (void)deleteFeedAction;
- (void)avatarClick;
- (double)getCellHeight;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)assignModel:(id)arg1 index:(long long)arg2 isCircleMaster:(_Bool)arg3 isHotComment:(_Bool)arg4;
- (void)assignModel:(id)arg1 index:(long long)arg2 isCircleMaster:(_Bool)arg3;
- (id)setContentWithModel:(id)arg1;
- (void)setStarCommentState;
- (void)showUserIdentityWithComment:(id)arg1;
- (void)showFeedLevelWithComment:(id)arg1;
- (void)addReplyView:(id)arg1 Width:(double)arg2;
- (void)setContentWithCommenterModel:(id)arg1 replyModel:(id)arg2;
- (void)upadeHideFloorLayout;
- (void)updateShowFloorLayout;
- (void)layoutSubviews;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

