//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSArray, NSString, QYPPBrowseCirlceHistoryDataManager, QYPPDefaultView, UITableView;

@interface QYPPBrowseCircleHistoryVC : UIViewController <UITableViewDelegate, UITableViewDataSource>
{
    NSArray *_sectionArr;
    _Bool _hasAddObserver;
    UITableView *_tableView;
    QYPPBrowseCirlceHistoryDataManager *_dataManager;
    QYPPDefaultView *_noDataView;
    id _tableViewObserver;
    struct UIEdgeInsets _contentInsets;
}

@property(nonatomic) _Bool hasAddObserver; // @synthesize hasAddObserver=_hasAddObserver;
@property(nonatomic) __weak id tableViewObserver; // @synthesize tableViewObserver=_tableViewObserver;
@property(retain, nonatomic) QYPPDefaultView *noDataView; // @synthesize noDataView=_noDataView;
@property(retain, nonatomic) QYPPBrowseCirlceHistoryDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) struct UIEdgeInsets contentInsets; // @synthesize contentInsets=_contentInsets;
- (void).cxx_destruct;
- (id)pingbackPage;
- (id)rpage;
- (void)joinWithData:(id)arg1 withSender:(id)arg2;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)scrollToTopAndRefresh;
- (void)handleError:(id)arg1;
- (void)loadMore;
- (void)fetchData;
- (void)showData;
- (void)createNoDataView;
- (void)createUI;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

