//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYPPJsonData.h"

@class NSString;
@protocol Optional;

@interface QYPPCircleTaskRewardSingleData : QYPPJsonData
{
    NSString<Optional> *_display;
    NSString<Optional> *_type;
    NSString<Optional> *_limitNum;
    NSString<Optional> *_everyCondition;
    NSString<Optional> *_everyReward;
    NSString<Optional> *_completeNum;
    NSString<Optional> *_desc;
    NSString<Optional> *_subTitle;
}

@property(retain, nonatomic) NSString<Optional> *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString<Optional> *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString<Optional> *completeNum; // @synthesize completeNum=_completeNum;
@property(retain, nonatomic) NSString<Optional> *everyReward; // @synthesize everyReward=_everyReward;
@property(retain, nonatomic) NSString<Optional> *everyCondition; // @synthesize everyCondition=_everyCondition;
@property(retain, nonatomic) NSString<Optional> *limitNum; // @synthesize limitNum=_limitNum;
@property(retain, nonatomic) NSString<Optional> *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString<Optional> *display; // @synthesize display=_display;
- (void).cxx_destruct;

@end

