//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class UINavigationController;

@interface QYPPRCTBridge : NSObject
{
    long long kickUserPid;
    long long kickUserUid;
    UINavigationController *kickUserNav;
    _Bool _isDebug;
}

+ (void)joinCircleWithNav:(id)arg1 circle:(id)arg2 loginAlert:(id)arg3 joinAlert:(id)arg4 loginSuccessBlock:(CDUnknownBlockType)arg5 joinSuccessBlock:(CDUnknownBlockType)arg6;
+ (_Bool)networkStatus;
+ (void)jumpTopListWithTopURL:(id)arg1;
+ (id)getSettingValueByKey:(id)arg1;
+ (id)generateSignWithParame:(id)arg1 requestPath:(id)arg2;
+ (void)showShareSupportWithModel:(id)arg1 toVC:(id)arg2;
+ (id)addVC;
+ (void)jumpToUserDataWithNavigationController:(id)arg1;
+ (_Bool)isUserStarOrPGC;
+ (void)blockAllAPNS:(_Bool)arg1 finishBlock:(CDUnknownBlockType)arg2;
+ (_Bool)getBlockAPNSStatusFromUserDefault;
+ (id)shareInstance;
@property(nonatomic) _Bool isDebug; // @synthesize isDebug=_isDebug;
- (void).cxx_destruct;
- (void)kickUser;
- (void)actionSheet:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (id)getPaopaoInfoWithJidStr:(id)arg1;
- (void)quitPaopaoWithPid:(long long)arg1 navigation:(id)arg2;
- (void)clearMessageForRoom:(id)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)setBlockStateForGroupChatWithPID:(id)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (void)setBlockStateForUserWithUID:(id)arg1 finishBlock:(CDUnknownBlockType)arg2;
- (_Bool)isPaopaoOwnerWithRoomJID:(id)arg1;
- (double)diffTime;
- (void)paopaoViewShotWithSchema:(id)arg1;
- (void)handleKickWithSchema:(id)arg1 nav:(id)arg2;
- (void)setBlockUserWithSchema:(id)arg1;
- (_Bool)isBlockUserWithJidStr:(id)arg1;
- (void)handleLoginWithSource:(unsigned long long)arg1 nav:(id)arg2;
- (void)reportWithSchema:(id)arg1 nav:(id)arg2 action:(id)arg3;

@end

