//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIScrollViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, QYPPPubModel, QYPPPubResource, UIViewController;

@interface QYPPPubView : UIScrollView <UIScrollViewDelegate>
{
    UIViewController *_parentViewController;
    QYPPPubModel *_publisherModel;
    QYPPPubResource *_pubModel;
    NSArray *_visiableViews;
    NSMutableArray *_widgetViewArray;
    NSMutableArray *_widgetArray;
    struct CGSize _sizeDelta;
}

+ (id)publisherViewWithModel:(id)arg1;
- (void).cxx_destruct;
- (void)pub_setContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)pub_resetContentSize;
- (void)pub_setContenSizeDelta:(struct CGSize)arg1;
- (struct CGSize)pub_intrinsicContentSize;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tapAnyWhereToDismissKeyboard;
- (id)firstResponder;
- (void)willSubmitContent;
- (void)willClosePublisher;
- (void)showKeyboard;
- (void)hideKeyboard;
- (void)layout;
- (void)updateFrame;
- (void)layoutFrame;
- (void)resetUI;
- (void)addSubviewFromViewController:(id)arg1;
- (id)initWithModel:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

