//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSArray, QYPPPrompterTextView, QYPPPubRecordBtnPanel;

@interface QYPPPubBaseShootViewController : UIViewController
{
    QYPPPubRecordBtnPanel *_recordControlPanel;
    QYPPPrompterTextView *_prompterTextView;
    NSArray *_prompterArray;
}

@property(retain, nonatomic) NSArray *prompterArray; // @synthesize prompterArray=_prompterArray;
@property(retain, nonatomic) QYPPPrompterTextView *prompterTextView; // @synthesize prompterTextView=_prompterTextView;
@property(retain, nonatomic) QYPPPubRecordBtnPanel *recordControlPanel; // @synthesize recordControlPanel=_recordControlPanel;
- (void).cxx_destruct;
- (void)showPrompterButton;
- (void)viewDidAppear:(_Bool)arg1;

@end

