//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYReaderBaseCardViewController.h"

@class QRInterFaceBaseModel;

@interface QYReaderCardlyOnSaleViewController : QYReaderBaseCardViewController
{
    QRInterFaceBaseModel *_model;
}

- (void).cxx_destruct;
- (void)responseWithData:(id)arg1 error:(id)arg2;
- (id)requestPath;
- (void)loadDataEx;
- (void)loadData;
- (void)viewDidLoad;

@end

