//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QRReaderJingxuanViewController.h"

@class NSString;

@interface QYReaderCardlyFemaleViewController : QRReaderJingxuanViewController
{
    NSString *_pgrfr;
}

- (void)setPgrfr:(id)arg1;
- (void).cxx_destruct;
- (id)pgrfr;
- (id)gender;
- (id)requestParams;
- (void)viewWillAppear:(_Bool)arg1;

@end

