//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "QYCameraDelegate-Protocol.h"
#import "QYCaptionSearchPresenterProtocol-Protocol.h"
#import "QYPhotoAlbumDelgate-Protocol.h"
#import "QYPicSearchResultVCDelegate-Protocol.h"
#import "QYSearchPresenterPicProtocol-Protocol.h"
#import "QYSearchPresenterProtocol-Protocol.h"
#import "QYTextSearchPresenterProtocol-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSArray, NSString, NSTimer, QYSearchPingbackSendModel;
@protocol QYCameraProtocol, QYPhotoAlbumProtocol, QYSpeechRecognizerProtocol;

@interface QYSearchPresenter : NSObject <QYTextSearchPresenterProtocol, QYSearchPresenterPicProtocol, QYCameraDelegate, QYPhotoAlbumDelgate, QYPicSearchResultVCDelegate, QYCaptionSearchPresenterProtocol, UIAlertViewDelegate, QYSearchPresenterProtocol>
{
    _Bool _hasShowedFeedback;
    NSTimer *_hotQuerysTimer;
    id <QYSpeechRecognizerProtocol> _speechRecognizer;
    QYSearchPingbackSendModel *_clickPingbackModel;
}

+ (id)fromDocIdForCardRcmdCellTextByCard:(id)arg1;
+ (void)sendCardRcmdItemClickRseatBySource:(long long)arg1 index:(unsigned long long)arg2;
+ (void)addRcmdCardToActionCard:(id)arg1 tableView:(id)arg2;
+ (void)requestCardRecommendWordsWithDocID:(id)arg1 completion:(CDUnknownBlockType)arg2;
+ (id)hotQuerys;
+ (id)highlightKeywordsFromString:(id)arg1 keywords:(id)arg2;
+ (void)sendPicSearchResultShowPingback;
+ (void)sendShareBtnClickPingback;
+ (void)sendRecogNewPicBtnClickPingback;
+ (void)sendRetryBtnClickPingback;
+ (void)sendPicSearchResultShareBtnPingbackWithDic:(id)arg1;
+ (_Bool)isVaildImgURLStr:(id)arg1;
+ (void)sendCaptionSearchResultShareBtnPingbackWithDic:(id)arg1;
+ (void)sendHotCaptionItemClickPingback:(long long)arg1;
+ (void)sendCaptionSearchVCShowPingback;
+ (void)sendSpeechSearchViewShowPingback;
+ (void)sendCaptionShareClickPingback;
+ (void)sendVoiceCancelClickPingback;
+ (void)sendVoiceOKClickPingback;
+ (void)sendVoiceRetryClickPingback;
+ (void)sendVoiceSearchClickPingback;
+ (void)sendInputSearchClickPingback;
+ (void)sendCaptionCancelClickPingback;
@property(nonatomic) _Bool hasShowedFeedback; // @synthesize hasShowedFeedback=_hasShowedFeedback;
@property(retain, nonatomic) QYSearchPingbackSendModel *clickPingbackModel; // @synthesize clickPingbackModel=_clickPingbackModel;
@property(retain, nonatomic) id <QYSpeechRecognizerProtocol> speechRecognizer; // @synthesize speechRecognizer=_speechRecognizer;
@property(retain, nonatomic) NSTimer *hotQuerysTimer; // @synthesize hotQuerysTimer=_hotQuerysTimer;
- (void).cxx_destruct;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)searchBarLeftBtnDidPressed:(id)arg1;
- (void)recognizeCompletionWithResult:(id)arg1 error:(id)arg2 isTimeOut:(_Bool)arg3;
- (void)setRootViewAlpha:(double)arg1;
- (void)uploadedImgEditCompleted:(id)arg1 editedImg:(id)arg2;
- (void)setPicSearchResultVC:(id)arg1;
- (id)picSearchResultVC;
- (void)toPicSearchResultVC:(id)arg1 ousSiteUrl:(id)arg2 sourceType:(unsigned long long)arg3 itemIndex:(long long)arg4;
- (void)uploadImg:(id)arg1 completion:(CDUnknownBlockType)arg2 progress:(CDUnknownBlockType)arg3 failed:(CDUnknownBlockType)arg4;
- (void)requestHotSearchPics:(CDUnknownBlockType)arg1;
- (void)picUploadViewCloseBtnPressed;
- (void)picUploadViewBgBtnPressed;
- (void)toPicUploadView:(id)arg1;
- (void)removePicSearchView;
- (void)qyPhotoAlbum:(id)arg1 didFinishPickingMedia:(id)arg2;
- (void)qyPhotoAlbumDidCancel:(id)arg1;
- (void)selectPicFormPhotoAlbum;
- (void)qyCamera:(id)arg1 didFinishPickingMedia:(id)arg2;
- (void)qyCameraDidCancel:(id)arg1;
- (void)takePhoto;
- (void)toPicSearchView;
@property(retain, nonatomic) id <QYPhotoAlbumProtocol> photoAlbumHandler;
@property(retain, nonatomic) id <QYCameraProtocol> cameraHandler;
- (id)init;
- (void)feedbackBtnDidPressed:(id)arg1;
- (void)feedbackCloseBtnDidPressed:(id)arg1;
- (void)closeSearchFeedbackView;
- (void)showSearchFeedbackView;
- (void)showSeachFeedbackByLastCell:(id)arg1 pageInfo:(id)arg2;
- (void)toCaptionSearchResultVCWithCaption:(id)arg1;
- (void)requestMicrophoneAuth:(CDUnknownBlockType)arg1;
- (void)toCaptionSearchView:(long long)arg1;
- (void)requestHotCaptions:(CDUnknownBlockType)arg1;
- (id)hotCaptionsForSpeechSearchPage;
- (id)hotCaptionsForDefaultPage;
- (void)removeCaptionSearchView;
- (void)setHotCaptions:(id)arg1;
@property(readonly, copy, nonatomic) NSArray *hotCaptions;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

