//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIImage;

@protocol QYSearchViewProtocol <NSObject>
- (void)showCaptionSearchView:(_Bool)arg1;
- (void)showPicSearchGuideView;
- (void)showPicUploadView:(_Bool)arg1 uploadingImg:(UIImage *)arg2;
- (void)showSwitchedViewByIndex:(unsigned long long)arg1 isAutoSwitched:(_Bool)arg2;
- (void)showSearchEnginerSwitchView:(_Bool)arg1;
- (void)showPicSearchView:(_Bool)arg1;
@end

