//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class QYUPlayerAdViewModel, QYUPlayerDataModel, QYUPlayerGlobalShareVideoContext, QYUPlayerTitleViewModel;
@protocol QYUPlayerViewDelegate, QYUPlayerViewMessageDelegate;

@protocol QYUPlayerViewProtocol
@property(readonly, nonatomic) _Bool isInErrorStatus;
@property(readonly, nonatomic) _Bool isPaused;
@property(readonly, nonatomic) _Bool isLoading;
@property(readonly, nonatomic) _Bool isPlaying;
@property(readonly, nonatomic) unsigned long long screenMode;
@property(retain, nonatomic) QYUPlayerGlobalShareVideoContext *globalShareVideoContext;
@property(nonatomic) __weak id <QYUPlayerViewMessageDelegate> messageDelegate;
@property(nonatomic) __weak id <QYUPlayerViewDelegate> delegate;
@property(retain, nonatomic) QYUPlayerAdViewModel *adViewModel;
@property(retain, nonatomic) QYUPlayerTitleViewModel *titleViewModel;
@property(readonly, nonatomic) QYUPlayerDataModel *currentPlayerDataModel;
- (void)updateView;
- (void)playerViewPreparePlay:(QYUPlayerDataModel *)arg1;
- (void)switchToMiniScreen;
- (void)switchToFullScreen;
- (void)pauseOrStopVideo;
- (void)savePlayTime;
- (void)syncPlayTime;
- (void)playVideoWithPlayType:(unsigned long long)arg1;
- (void)stopVideo;
- (void)pauseVideo;
- (void)playVideo;
@end

