//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QYUTouchView.h"

@class QYBisonAlbum, QYUCardBaseCell, UIImageView, UILabel, UIView;

@interface QYUPaoPaoHomeAvatarView : QYUTouchView
{
    QYBisonAlbum *_bison;
    QYUCardBaseCell *_baseCell;
    UIImageView *_topLeftImageView;
    UIImageView *_avatarImageView;
    UIView *_avatarBorderView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
}

@property(retain, nonatomic) UILabel *subtitleLabel; // @synthesize subtitleLabel=_subtitleLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *avatarBorderView; // @synthesize avatarBorderView=_avatarBorderView;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(retain, nonatomic) UIImageView *topLeftImageView; // @synthesize topLeftImageView=_topLeftImageView;
@property(nonatomic) __weak QYUCardBaseCell *baseCell; // @synthesize baseCell=_baseCell;
@property(retain, nonatomic) QYBisonAlbum *bison; // @synthesize bison=_bison;
- (void).cxx_destruct;
- (void)avatarDidClicked;
- (void)rebuildUI;
- (void)setBison:(id)arg1 andBaseCell:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

