//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RCTPPViewController.h"

@class NSNumber;

@interface RCTPPReportViewController : RCTPPViewController
{
    int _reportType;
    NSNumber *_currentUID;
    NSNumber *_currentPID;
}

@property(nonatomic) NSNumber *currentPID; // @synthesize currentPID=_currentPID;
@property(nonatomic) NSNumber *currentUID; // @synthesize currentUID=_currentUID;
@property(nonatomic) int reportType; // @synthesize reportType=_reportType;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)didReportSuccess;
- (void)initSchemaParser;
- (id)initVoteReportWithVoteId:(id)arg1;
- (id)initCommentReportWithUID:(id)arg1 commentId:(id)arg2 businessType:(int)arg3;
- (id)initFeedReportWithUID:(id)arg1 feedId:(id)arg2 wallId:(id)arg3;
- (id)initGroupChatReportWithPid:(id)arg1;
- (id)initUserReportWithUID:(id)arg1 feedId:(id)arg2 wallId:(id)arg3 pid:(id)arg4;
- (void)viewWillAppear:(_Bool)arg1;

@end

