//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface TipsBaseView : UIView
{
    CDUnknownBlockType _hiddenBlock;
}

- (void).cxx_destruct;
- (void)hide;
- (void)showWithAnimated;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1 block:(CDUnknownBlockType)arg2;

@end

