//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Jul  5 2017 23:13:50).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface YunPanUploadUtils : NSObject
{
}

+ (void)log:(id)arg1 format:(id)arg2;
+ (unsigned long long)fileSizeByFilePath:(id)arg1;
+ (id)fileSuffixWithLocalPath:(id)arg1;
+ (void)setObject:(id)arg1 forKey:(id)arg2 inDict:(id)arg3;
+ (id)encodeURL:(id)arg1;
+ (id)requestParameterFromDict:(id)arg1;
+ (id)coverImagePathWithVideoPath:(id)arg1;
+ (id)uploadTaskHistoryPath;
+ (id)uploadTaskPath;
+ (id)generateIdentifier;
+ (id)uuidString;
+ (id)decoder:(id)arg1 safetyDecodeObjectForKey:(id)arg2;
+ (void)encoder:(id)arg1 safetyEncodeObject:(id)arg2 forKey:(id)arg3;

@end

